### ISSUE TITLE
Porting session timeout detection function on the ASP.NET WebForm to ASP.NET MVC.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#102]
# Requirement
- Session timeout detection function on the ASP.NET WebForm  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L497

Please porting the above function to the following location of ASP.NET MVC.

- MyBaseMVController.OnActionExecuting(ActionExecutingContext filterContext)  
https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseMVController.cs#L116

## Supplement
Session timeout detection function to detect the Session timeout using the session timeout detection cookie. 

- Session timeout detection cookie is generated along with the session cookie in the case of "HttpSessionState.IsNewSession == true".
- Then, Web access is continued in state of "HttpSessionState.IsNewSession == false".
- If session timeout has occurred, only the state of "HttpSessionState.IsNewSession == true" in ASP.NET standard feature.
- But, it is possible to detect session timeout by the session timeout detection cookie existence check in addition to this state.

## Reference
- Sessionタイムアウト検出機能 - Open 棟梁 Wiki  
http://opentouryo.osscons.jp/index.php?Session%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%A2%E3%82%A6%E3%83%88%E6%A4%9C%E5%87%BA%E6%A9%9F%E8%83%BD
- Sessionタイムアウト検出用Cookie - Open 棟梁 Wiki  
http://opentouryo.osscons.jp/index.php?Session%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%A2%E3%82%A6%E3%83%88%E6%A4%9C%E5%87%BA%E7%94%A8Cookie

**Comment by supragyan** [comment]
HODC wants to confirm :
We have implemented as following :
•Session timeout detection cookie is generated when "HttpSessionState.IsNewSession == true".
•Then, Web access is continuing in state of "HttpSessionState.IsNewSession == false".
•If session timeout has occurred, Then HttpSessionState.IsNewSession  sets to true

you have not mark up entire lock (this.SessionLock) mechanism in above comment.
Do we need to implement entire  lock (this.SessionLock) mechanism 
in MyBaseMVController.OnActionExecuting(ActionExecutingContext filterContext) method or only
implement which you marked up (if (sessionTimeOutCheck.ToUpper() == FxLiteral.ON)).
 Please confirm?

**Comment by daisukenishino** [comment]
@supragyan 

(1)
>If session timeout has occurred, Then HttpSessionState.IsNewSession sets to true

If session timeout has occurred, Then FrameworkException will be thrown.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L568

(2)
```C#
lock (this.SessionLock)
```
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L387

Actually, this Step is not required.
This is because the request of the same user with the same session is due to be serialized by ASP.NET.

(3)
```C#
if (sessionTimeOutCheck.ToUpper() == FxLiteral.ON)
```
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L495

This is necessary.
Please define the "FxSessionTimeOutCheck" to appsettings section of app.config.

```XML
<!-- セッションタイムアウト検出機能のon・off  -->
<!-- Select the "turn-on" and "turn-off" of the session timeout detection function. -->
<add key="FxSessionTimeOutCheck" value="on"/> 
```
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/app.config#L37

(4)
- The description of the "HODC" is prohibited.
- Let's use the [GitHub Flavored Markdown (GFM)](https://help.github.com/articles/github-flavored-markdown/).

**Comment by daisukenishino** [comment]
@supragyan 

I forgot an indication of the implementation of the following processing.
- Transition to the Error screen when an exception occurs.
- Delete the session timeout detection cookie in Error screen.

In the WebForm version has been implemented as follows.
- Transition to the Error screen when an exception occurs.
  - https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseController.cs#L792
- Delete the session timeout detection cookie in Error screen.
  - https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/ErrorScreen.aspx.cs#L175

MyBaseController.TransferErrorScreen2 method using HttpContext.Current.Items [FxHttpContextIndex.SESSION_ABANDON_FLAG] is determine whether or not to delete the session timeout detection cookie in ErrorScreen.aspx.cs.

**Comment by yusukemaegawa** [comment]
@supragyan

> Transition to the Error screen when an exception occurs.

You can achieve the above requirement with the following code.

**The following code is prototype.**
**Please modify the following code according to requirements for MyBaseController.**

And I think that the transition destination controller (ErrorController) does not have to extend MyBaseController.

```C#
protected override void OnException(ExceptionContext filterContext)
{
    //base.OnException(filterContext);

    // Store the exception information for a Session.
    Session["Exception"] = filterContext.Exception.ToString();

    // Consider the exception was handled.
    filterContext.ExceptionHandled = true;
    filterContext.HttpContext.Response.Clear();

    // Transit to Error Controller.
    filterContext.Result = new RedirectResult("/Error");
}
```

**Comment by daisukenishino** [comment]
@supragyan

The following is a snippet of the additional migration target.

- MyBaseController.TransferErrorScreen ---> MyBaseMVController.OnException
  - HttpContext can not be used because it uses the redirect in MVC. Please use the Session.
```C#
#region 例外型を判別しエラーメッセージIDを取得

// エラーメッセージ
string err_msg;

// エラー情報をセッションから取得
string err_info;

// エラーのタイプ
string[] arrErrType = ex.GetType().ToString().Split('.');
string errType = arrErrType[arrErrType.Length - 1];

// エラーメッセージＩＤ
string errMsgId = "";

// #21-start
if (errType == "BusinessSystemException")
{
    // システム例外
    BusinessSystemException bsEx = (BusinessSystemException)ex;
    errMsgId = bsEx.messageID;
}
else if (errType == "FrameworkException")
{
    // フレームワーク例外
    FrameworkException fxEx = (FrameworkException)ex;
    errMsgId = fxEx.messageID;
}
else
{
    // それ以外の例外
    errMsgId = "－";
}
// #21-end

#endregion
```
```C#
#region エラー画面に表示するエラー情報を作成

err_msg = System.Environment.NewLine +
    "エラーメッセージＩＤ: " + errMsgId + System.Environment.NewLine +
    "エラーメッセージ: " + ex.Message.ToString();

// #19-start
err_info = System.Environment.NewLine +
    "対象URL: " + HttpContext.Current.Request.Url.ToString() + System.Environment.NewLine +
    "スタックトレース:" + ex.StackTrace.ToString() + System.Environment.NewLine +
    "Exception.ToString():" + ex.ToString();
// #19-end

// Form情報を出力するために、遷移方法をServer.Transferに変更。
// また、情報受け渡しを、HttpContextに変更。

HttpContext.Current.Items.Add(FxHttpContextIndex.SYSTEM_EXCEPTION_MESSAGE, err_msg);
HttpContext.Current.Items.Add(FxHttpContextIndex.SYSTEM_EXCEPTION_INFORMATION, err_info);
```
- ErrorScreen.aspx.cs ---> ErrorController.cs
  - HttpContext can not be used because it uses the redirect in MVC. Please use the Session.
  - HttpContext can not be used because it uses the redirect in MVC.  
Therefore, there is no need to display the Forms information.
```C#
        //画面にエラーメッセージ・エラー情報を表示する-----------------------------

        //エラーメッセージをＨＴＴＰコンテキストから取得
        string err_msg = 
            (string)HttpContext.Current.Items[FxHttpContextIndex.SYSTEM_EXCEPTION_MESSAGE];

        //エラー情報をＨＴＴＰコンテキストから取得
        string err_info = 
            (string)HttpContext.Current.Items[FxHttpContextIndex.SYSTEM_EXCEPTION_INFORMATION];

        //画面にエラーメッセージを表示する
        this.Label1.Text = CustomEncode.HtmlEncode(err_msg);

        //画面にエラー情報を表示する
        this.Label2.Text = CustomEncode.HtmlEncode(err_info);

        // ------------------------------------------------------------------------
```
```C#
        // 画面にセッション情報を表示する------------------------------------------

        //ＨＴＴＰセッション情報
        System.Web.SessionState.HttpSessionState sess = HttpContext.Current.Session;

        if (sess != null)
        {
            //foreach
            foreach (string strKey in sess)
            {
                if (sess[strKey] == null)
                {
                    al_session.Add(new PositionData(strKey, "null"));
                }
                else
                {
                    al_session.Add(new PositionData(strKey, CustomEncode.HtmlEncode(sess[strKey].ToString())));
                }
            }

            //データバインド
            this.Repeater2.DataSource = al_session;
            this.Repeater2.DataBind();
        }

        // ------------------------------------------------------------------------
```
```C#
        // セッション情報を削除する------------------------------------------------

        if ((bool)HttpContext.Current.Items[FxHttpContextIndex.SESSION_ABANDON_FLAG])
        {
            // 2009/09/18-start

            // セッション タイムアウト検出用Cookieを消去
            // ※ Removeが正常に動作しないため、値を空文字に設定 ＝ 消去とする

            // Set-Cookie HTTPヘッダをレスポンス
            Response.Cookies.Set(FxCmnFunction.DeleteCookieForSessionTimeoutDetection());

            // 2009/09/18-end

            try
            {
                // セッションを消去
                Session.Abandon();
            }
            catch (Exception ex2)
            {
                // エラー発生時

                // このカバレージを通過する場合、
                // おそらく起動した画面のパスが間違っている。
                Console.WriteLine("このカバレージを通過する場合、おそらく起動した画面のパスが間違っている。");
                Console.WriteLine(ex2.Message);
            }
        }
```

- ErrorScreen.aspx ---> Index.cshtml

```XML
<body>
    <h1>開発用エラー画面</h1>
    <p>
        システム障害が発生しました。<br/>
        エラーメッセージおよびスタックトレース情報を以下に示します。<br />
        ※ スタック トレースの正確な情報はアクセス トレース ログから確認下さい。<br />
    </p>
    <p>
        本画面は、Form、Session情報をダンプしますので<br />
        本番用エラー画面としては使用しないで下さい（差し替えて下さい）。
    </p>
    <hr />
    <div>
       エラーメッセージ：<br />
       <pre><cc1:WebCustomLabel ID="Label1" runat="server"></cc1:WebCustomLabel></pre>
    </div>
    <hr />
    <div>
       その他の情報：<br />
       <pre><cc1:WebCustomLabel ID="Label2" runat="server"></cc1:WebCustomLabel></pre>
    </div>
```
```XML
       ＨＴＴＰセッション情報の一覧：<br />
        <br />
        <asp:Repeater id="Repeater2" runat="server">
          <HeaderTemplate>
             <table border="1" width="600">
                <tr>
                  <td style="width:300px"><b>キー</b></td>
                  <td style="width:700px"><b>バリュー</b></td>
                </tr>
          </HeaderTemplate>
             
          <ItemTemplate>
             <tr>
                <td style="width:300px"> <%# DataBinder.Eval(Container.DataItem, "key") %> </td>
                <td style="width:700px"> <%# DataBinder.Eval(Container.DataItem, "Value") %> </td>
             </tr>
          </ItemTemplate>
             
          <FooterTemplate>
             </table>
          </FooterTemplate>
             
       </asp:Repeater>
    </div>
</body>
```

**Comment by daisukenishino** [comment]
https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/13
