### ISSUE TITLE
Error of DTO

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#106]
# Windows Store does not support DTTable.
Result of the investigation, There was no problem in the DTO.

## Phenomenon
https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/9

## Countermeasure
https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/9

# Marshaling Error of DTO
@daisukenishino  will correspond this issue.

## Phenomenon
Convert.ToBoolean(""); raises an exception at DTTables.Load.

## Countermeasure
- After I rebuild, the problem has been corrected.
- In addition, there is a problem with dependency.
@daisukenishino will correspond this issue.

    DTTables.StringToDTTables
      ---> DTTables.Load
      ---> CustomMarshaler.PrimitivetypeFromString
      ---> DTColumn.AutoCast

**Comment by supragyan** [comment]
@daisukenishino ,
We will investigate and inform you.

Regards,

**Comment by daisukenishino** [comment]
@supragyan 

Marshaling Error of DTO has been resolved.
I will investigate Windows Store problems tomorrow.

**Comment by daisukenishino** [comment]
@supragyan 
This problem have been moved to the following.
https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/9
