### ISSUE TITLE
Create a root_VS2015 corresponding to the Visual Studio 2015.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#113]
# Requirement
Create a root_VS2015 in accordance with the following procedure.
- Upgrade the solution files in [root_VS2013](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013) by be opened in VS2015.
- Change the targetframework of the project files to .NET4.6.
- Save the upgraded files to root_VS2015 folder.
- Confirm there are no problems by perform [following things](https://github.com/OpenTouryoProject/OpenTouryo/issues/113#issuecomment-139471738).
- Confirm the modified project to work properly.
- Modify the Readme.md as necessary.

https://github.com/OpenTouryoProject/OpenTouryoTemplates

In this work you will use the professional edition of VS2015.

**Comment by daisukenishino** [comment]
# How to check
## Build
- Build all projects.
- To check that the all builded assembly can be executed without any problems.

## Test
### Run the test code and check test result.
- [Public.Test](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Tests/Public.Test)
- [BDLayer.Test](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Tests/BDLayer.Test)
- [Workflow.Test](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Tests/Workflow.Test)

At present, test case in the test code is a not enough.
Therefore, following issue has been registered.

- [Development of test code. #114](https://github.com/OpenTouryoProject/OpenTouryo/issues/114)

### Shortfall of test cases in the test code will be digested using a sample program.
Screen of the [sample program](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx)
- /sample/
  - [/3Tier/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier)
  - [/crud/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/crud)
- /testFxLayerP/
  - [/normal/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/normal)
  - [/nest/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/nest)
  - [/table/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/table)
  - [/wcc/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/wcc)
  - [/withAjax/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/withAjax)
- [/testPublic/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testPublic)
- [/testScreenCtrl/](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testScreenCtrl)

### Verify that it works without problems by perform typical tutorials.
Typical tutorials
- [Tutorial_ASPNET_C#_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_ASPNET_C%23_EN.doc)
- [Tutorial_DPQ_analytical_tool_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_DPQ_analytical_tool_EN.doc)

Also perform the following as necessary.
- [Tutorial_2CS_C#_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_2CS_C%23_EN.doc)
- [Tutorial_3CS_C#_EN.doc](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/2_Tutorial/en/Tutorial_3CS_C%23_EN.doc)

## Diff
- Get the diff of [root_VS2013](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013) and root_VS2015 by WinMarge or TortoiseGit - Diff.
- See the code converted by the upgrade.  
- If the code has been converted, then check that there is no problem.
- Currently it has been found that following files are converted.  
These files are not have problems in many cases at converted.
  - Solution files and Project files (*.sln, *.csproj, *.vbproj)
  - Config files (*.config)  
Unnecessary conversion should be returned to the original.
  - Files that is automatically generated by the Visual Studio Generator (e.g. : *.designer.cs, vb)
  - ,etc. (Please check by comparing the root_VS2013, root_VS2010, root_2012.)

It is possible to perform the [merge task](https://github.com/OpenTouryoProject/OpenTouryo/issues/104) by understanding this.

**Comment by daisukenishino** [comment]
# Delivery time

Delivery time of this issu is the end of October.
Because, there is a project that become user of root_VS2015 ver.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
we will deliver before end of October.
is it ok?
Please confirm.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

We will pass it to the project at the end of October.
Therefor, We expects your perfect delivery on until October 19.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Thank you for the confirmation.

we will try to deliver before October 19.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Exports and lent of MSDN subscription has already been completed.
I will give you the ISO file of the VS 2015 Pro via IPS.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Thank you for the information.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Please share the ISO file of the VS 2015 Pro via IPS. We will start upgradation work.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Export control procedure has not been completed.
This will be completed on September 24 or 25th.
If it was completed, then it will be sent.

I will send the *_web_installer_*.exe rather than the ISO file.
 en_visual_studio_professional_2015_x86_x64_web_installer_6846634.exe

**Comment by daisukenishino** [comment]
# following is pointed out.

## Addition of the following folder is a problem.
- \root_VS2015\programs\C#\Frameworks\Infrastructure\Build
- \root_VS2015\programs\C#\Frameworks\Infrastructure\Temp

## Deletion of the following folder is a problem.
- \root_VS2013\programs\C#\Frameworks\PortableClassLibrary\PCLBusiness\bin
- \root_VS2013\programs\C#\Frameworks\PortableClassLibrary\PCLFramework\bin
- \root_VS2013\programs\C#\Frameworks\PortableClassLibrary\PCLPublic\bin

## .NET Version of the copy source has a problem.
- \root_VS2013\programs\C#\Samples\AsyncSvc_sample\AsyncSvc_sample\AsyncSvc_sample.csproj
-

**Comment by daisukenishino** [comment]
# [5_Build_2CS_sample.bat (VB)](https://github.com/OpenTouryoProject/OpenTouryo/issues/113#issuecomment-148641727)

I think this problem is due to the following.

- 街角のリブロガー [VB.NET]コンパイラ エラー (CS1009、BC30037 など) が発生する  
http://ivis-mynikki.blogspot.jp/2015/08/vbnet-cs1009bc30037.html
- MSDN Blogs  >  Visual Studio サポート チーム blog  
Visual Studio 2015 で Shift JIS エンコーディングされた  
ソース ファイルをビルドするとコンパイラ エラーが発生する場合がある  
http://blogs.msdn.com/b/jpvsblog/archive/2015/08/03/vs2015-shift-jis-encoding.aspx

The following is a list of all of the Shift-JIS encoding files.

```TXT
- CS, VB
  - \root_VS2015\programs\C#\Frameworks\Infrastructure\Public\Win32\EventLogWin32.cs
  - \root_VS2015\programs\C#\Samples\WinAzure_sample\ASPNETWebService\WebRole.cs
  - \root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\WebRole.cs
  - \root_VS2015\programs\VB\Samples\2CS_sample\2CSClientWin_sample\Form1.vb
  - \root_VS2015\programs\VB\Samples\2CS_sample\GenDaoAndBatUpd_sample\Form1.vb
  - \root_VS2015\programs\VB\Samples\2CS_sample\TimeStamp_sample\Form1.vb
  - \root_VS2015\programs\VB\Samples\Bat_sample\SimpleBatch_sample\Module1.vb

- DialogFrame.htm
  - \root_VS2015\programs\C#\Samples\WebApp_sample\ProjectX_sample\Aspx\Framework\DialogFrame.htm
  - \root_VS2015\programs\VB\Samples\WebApp_sample\ProjectX_sample\Aspx\Framework\DialogFrame.htm

  - \root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\Aspx\Framework\DialogFrame.htm
  - \root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\Aspx\Common\testNest\testScreen1bmp1.master
  - \root_VS2015\programs\C#\Samples\WS_sample\WSClient_sample\WSClientWinStore_samples\WSClientSL_sample.Web\Aspx\Framework\DialogFrame.htm
  - \root_VS2015\programs\C#\Samples\WS_sample\WSClient_sample\WSClientSL_samples\WSClientSL_sample.Web\Aspx\Framework\DialogFrame.htm

- TXT
  - Readme
    - \root_VS2015\Readme.md
    - \root_VS2015\programs\C#\Frameworks\Readme.txt
    - \root_VS2015\programs\C#\Samples\WebApp_sample\MVC_Sample\Readme.txt
    - \root_VS2015\programs\C#\Samples\Bat_sample\SimpleBatch_sample\readme.txt
    - \root_VS2015\programs\C#\Samples\Bat_sample\RerunnableBatch_sample\readme.txt
    - \root_VS2015\programs\C#\Samples\Bat_sample\RerunnableBatch_sample2\readme.txt
    - \root_VS2015\programs\C#\Samples\WS_sample\WSClient_sample\WSClientSL_samples\Readme.txt
    - \root_VS2015\programs\C#\Samples\WS_sample\WSClient_sample\WSClientWinStore_samples\Readme.txt

    - \root_VS2015\programs\VB\Samples\2CS_sample\CustCtrl_sample\Readme.txt
    - \root_VS2015\programs\VB\Samples\2CS_sample\GenDaoAndBatUpd_sample\Readme.txt
    - \root_VS2015\programs\VB\Samples\2CS_sample\TimeStamp_sample\Readme.txt
    - \root_VS2015\programs\VB\Samples\2CS_sample\AsyncEvent_sample\Readme.txt

    - \root_VS2015\programs\VB\Samples\Bat_sample\SimpleBatch_sample\readme.txt
    - \root_VS2015\programs\VB\Samples\Bat_sample\RerunnableBatch_sample\readme.txt
    - \root_VS2015\programs\VB\Samples\Bat_sample\RerunnableBatch_sample2\readme.txt

    - \root_VS2015\programs\C#\Samples\2CS_sample\TimeStamp_sample\Readme.txt
    - \root_VS2015\programs\C#\Samples\2CS_sample\GenDaoAndBatUpd_sample\Readme.txt
    - \root_VS2015\programs\C#\Samples\2CS_sample\CustCtrl_sample\Readme.txt
    - \root_VS2015\programs\C#\Samples\2CS_sample\AsyncEvent_sample\Readme.txt
    
  - SQL, XML
    - \root_VS2015\files\resource\Sql\sqlserver\Workflow\SQL\Table\M_User_Insert(sample).sql
    - \root_VS2015\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceInsert.sql
    - \root_VS2015\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceInsert.xml
    - \root_VS2015\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceUpdate.xml
    
  - TestTable.txt
    - \root_VS2015\files\resource\Sql\sqlserver\TestTable.txt
    - \root_VS2015\files\resource\Sql\db2\TestTable.txt
    - \root_VS2015\files\resource\Sql\hirdb\TestTable.txt
    - \root_VS2015\files\resource\Sql\mysql\TestTable.txt
    - \root_VS2015\files\resource\Sql\sqlserver\TestTable.txt
    - \root_VS2015\files\resource\Sql\pstgrs\TestTable.txt
    - \root_VS2015\files\resource\Sql\oracle\TestTable.txt
    - \root_VS2015\files\resource\Test\dpq\query\for regression tests\sqlserver\TestTable.txt
    - \root_VS2015\files\resource\Test\dpq\query\for regression tests\pstgrs\TestTable.txt
    - \root_VS2015\files\resource\Test\dpq\query\for regression tests\oracle\TestTable.txt
    - \root_VS2015\files\resource\Test\dpq\query\for regression tests\mysql\TestTable.txt
    - \root_VS2015\files\resource\Test\dpq\query\for regression tests\hirdb\TestTable.txt
    - \root_VS2015\files\resource\Test\dpq\query\for regression tests\db2\TestTable.txt
    
  - Else
    - \root_VS2015\files\tools\WinMergeFilters\touryo.flt
    - \root_VS2015\files\tools\WinMergeFilters\touryofull.flt
    - \root_VS2015\programs\C#\Frameworks\Tools\DPQuery_Tool\demo.txt
    - \root_VS2015\programs\C#\Frameworks\Tools\DeployZipPackWithHTTP\Command line.txt
    - \root_VS2015\programs\C#\Frameworks\Infrastructure\Public\Csp\SessionDB creation script.txt
```
