### ISSUE TITLE
Development of test code.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#114]
# Requirement
- Public test is terminating abnormally at CI WebSite.  
Some of the test code have ended with failure. Please correct the test code as needed.
- Test case of CRUD test is insufficient.  
  https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Tests/BDLayer.Test/CRUDTest.cs  
  There is a need to add all B layer calls from sampleScreen.aspx as a test case.
  https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/crud/sampleScreen.aspx.cs

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>There is a need to add all B layer calls from sampleScreen.aspx as a test case.
We added all the B layer calls from sampleScreen.aspx as a test case and checked coverage report.
Shall we deliver for your review?
Please let us know.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>Shall we deliver for your review?

Please to send a test code as pullrequest.
Also, we want to confirm the report on the jenkins.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
> Please to send a test code as pullrequest.

we will send pull request from feature branch to nishino branch

> Also, we want to confirm the report on the Jenkins CI Web site.

Since Jenkins configured with GitHub OpenTouryoProject repository. the code changes need to merge into this repository to confirm the reports

**Comment by daisukenishino** [comment]
@kishoreandukuri 

> the code changes need to merge into this repository to confirm the reports.

Oh, I see.

> we will send pull request from feature branch to nishino branch

Please send the pullrequest after the VS2015 support has been merged into OpenTouryoProject/OpenTouryouTemplates.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Thank you for the reply
we will do so
