### ISSUE TITLE
To merge the changes ( - Until December 18)

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#117]
# Requirement
Timing of the release has been imminent.

- The changes to the root folder will be merged as follows.
  - root -> root_easysetup -> root_VS2010 -> root_VS2012 -> root_VS2013 -> root_VS2015

- Do the merge work by refer the following URL as the guide.
  - https://github.com/OpenTouryoProject/OpenTouryo/issues/38
  - https://github.com/OpenTouryoProject/OpenTouryo/issues/104
  - https://github.com/OpenTouryoProject/OpenTouryo/issues/113

**Comment by daisukenishino** [comment]
# Additional requirement
Before the merge work,
please change file's encoding to UTF-8 from Shift_JIS in accordance with the [this contents](https://github.com/OpenTouryoProject/OpenTouryo/issues/113#issuecomment-150105968).

- Target files are existed under [root folder](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root).
- After that, please do merge accordance with the following route. 
  - root -> root_easysetup -> root_VS2010 -> root_VS2012 -> root_VS2013 -> root_VS2015

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Please share the tool if any for converting file's encoding to UTF-8 from Shift_JIS.
we will take this task into next sprint
please let us know.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

We use [Sakura editor](http://sakura-editor.sourceforge.net/),
but I think that can also be in "%windir%\system32\notepad.exe".

The merge work will require a lot of time.
To complete the release work in this year,
I think that it is better to start merge work from the next sprint.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We started merge work, Please let us know from which repositories in GitHub we have to pull the code for latest code changes.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

we added new class 'MyApsBaseLogic' for AsyncProcessingService in OpenTouryo\root\programs\C#\Frameworks\Infrastructure\Business\Business\MyApsBaseLogic.cs

shall we added this class into root_easysetup folder?

Please let us know.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

we changed the messages in the resource file 'OpenTouryo\root_easysetup\programs\C#\Frameworks\Tools\DPQuery_Tool\Resources\Resource.resx'
<b>Before:</>
<data name="STATUS_MSL_CREATED" xml:space="preserve">
    <value>I generated a MySQL Connector / NET.</value>
  </data>
  <data name="STATUS_ODB_CREATED" xml:space="preserve">
    <value>I generated a ODBC.NET.</value>
  </data>
  <data name="STATUS_ODP_CREATED" xml:space="preserve">
    <value>I generated a ODP.NET.</value>
  </data>
  <data name="STATUS_OLE_CREATED" xml:space="preserve">
    <value>I generated a OLEDB.NET.</value>
  </data>
  <data name="STATUS_PGS_CREATED" xml:space="preserve">
    <value>I generated a PostgreSQL Npgsql.</value>
  </data>
<b>After:</b>
<data name="STATUS_MSL_CREATED" xml:space="preserve">
    <value> MySQL Connector was generated / NET.</value>
  </data>
  <data name="STATUS_ODB_CREATED" xml:space="preserve">
    <value>ODBC.NET was generated.</value>
  </data>
  <data name="STATUS_ODP_CREATED" xml:space="preserve">
    <value>ODP.NET was generated.</value>
  </data>
  <data name="STATUS_OLE_CREATED" xml:space="preserve">
    <value>OLEDB.NET was generated.</value>
  </data>
  <data name="STATUS_PGS_CREATED" xml:space="preserve">
    <value>PostgreSQL Npgsql was generated.</value>
  </data>

Please confirm.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

#### https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-154977701
Please unified with BOM.

Because It can be read that the UTF-8 files with BOM is better from the information on the Web site. But, Currently, Visual Studio correctly recognize the character code of most of the existing files without BOM.
 
#### https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-155377539
Please add the file.
The merge work also include adding or removing work of the file.

#### https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-155387721
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/Resources/Resource.resx
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root_easysetup/programs/C%23/Frameworks/Tools/DPQuery_Tool/Resources/Resource.resx

I confirmed 2 files's difference by comparison.
This difference occurred by deletion of "UI improvement" task.
- https://github.com/OpenTouryoProject/OpenTouryo/issues/109
- https://github.com/OpenTouryoProject/OpenTouryo/pull/126

I think that it can merge if there is no problem in the "UI improvement" task.

Is there a problem with the "UI improvement" task ?
If there is a problem, problem is propagated by merge the code that has the problem.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

#117 (comment)
>Visual Studio correctly recognize the character code of most of the existing files without BOM

Yes, but user can exclude this by using the Menu options in the Visual studio
for this reason, we used BOM encoding

#117 (comment)

>Please add the file.
The merge work also include adding or removing work of the file.

Sure, we will add this file

 #117 (comment)
>Is there a problem with the "UI improvement" task ?

we will discuss with the team and merge the changes if there is no problem.

Thank  for your indications.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>for this reason, we used BOM encoding

I see.
Please let views on correspondence to existing files without BOM.

If it need correspondence of add BOM,
please consider such as the corresponding period and, tools that is required for this correspondence.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please let views on correspondence to existing files without BOM.

some of the existing files in OpenTouryo is having BOM.

We already converted all the encoding of existing files to BOM

shall we change it to without BOM.

Please let us know.

**Comment by daisukenishino** [comment]
>some of the existing files in OpenTouryo is having BOM.
>We already converted all the encoding of existing files to BOM

If such a thing, in this time, please convert file with BOM.
In the future, convert to file with BOM from file without BOM.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Sure, we will do so

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>we will discuss with the team and merge the changes if there is no problem.

Please notify the presence or absence of the problem as a [result of the confirmation](https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-156358897).
I reminded that some of the problems was discovered  in [previous merge operation](https://github.com/OpenTouryoProject/OpenTouryo/issues/104).
For this reason, I also scheduled to confirm of the difference between the root and the root_easysetup.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-156358897

>Please add the file.

Does OpenTouryo\root_easysetup supports multiple db?

\<Reference Include="DamDB2">
\<HintPath>..\..\Infrastructure\Build\DamDB2.dll</HintPath>
\</Reference>
\<Reference Include="DamMySQL">
\<HintPath>..\..\Infrastructure\Build\DamMySQL.dll</HintPath>
\</Reference>
 \<Reference Include="DamOraOdp">
\<HintPath>..\..\Infrastructure\Build\DamOraOdp.dll</HintPath>
\</Reference>
\<Reference Include="DamPstGrS">
\<HintPath>..\..\Infrastructure\Build\DamPstGrS.dll</HintPath>
\</Reference>
\<Reference Include="IBM.Data.DB2">
\<HintPath>..\..\Infrastructure\Public\Dll\IBM.Data.DB2.dll</HintPath>
\</Reference>
\<Reference Include="Ionic.Zip">
\<HintPath>..\..\Infrastructure\Public\Dll\Ionic.Zip.dll</HintPath>
\</Reference>
\<Reference Include="log4net">
\<HintPath>..\..\Infrastructure\Public\Dll\log4net.dll</HintPath>
\</Reference>

But in 'OpenTouryo\root\programs\C#\Frameworks\Infrastructure\Business\Business\MyApsBaseLogic.cs ' supports multiple db

we added this class in OpenTouryo\root_easysetup
is this ok?

Please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-156955112

MyApsBaseLogic is added,
after it has been corrected in the same way as MyBaseLogic.

Compare the following differences.

- root > MyBaseLogic.cs
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Business/MyBaseLogic.cs
- root_easysetup > MyBaseLogic.cs
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root_easysetup/programs/C%23/Frameworks/Infrastructure/Business/Business/MyBaseLogic.cs

**Comment by kishoreandukuri** [comment]
@daisukenishino 

In 'OpenTouryo\root_easysetup', project file 'DPQuery_Tool.csproj' is having reference to 'demo.txt' file

Whereas, In 'OpenTouryo\root', project file 'DPQuery_Tool.csproj' is not having reference to 'demo.txt' file
Do we need to keep this file in project file 'DPQuery_Tool.csproj?

Please confirm.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-156956960

"demo.txt" file was added by the [previous commit](https://github.com/OpenTouryoProject/OpenTouryo/commit/7ba525fcd977f886b362cf9276749ec468266d7d).

This is incorrect. Please correct.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-156956920

We did the changes as in the 
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root_easysetup/programs/C%23/Frameworks/Infrastructure/Business/Business/MyBaseLogic.cs

https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-156961620
We removed "demo.txt" file reference in Project file

Thank you for the confirmation

**Comment by SandeepNayak077** [comment]
@daisukenishino 

The [manual transaction controls] (https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/VB/Samples/WebApp_sample/ProjectX_sample/App_Code/testPublic/Business) was missing in root_easysetup.
Do we need to add?
Please confirm.

Shall we also improve build system? 
By adding the [batch file] (https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/C%23/3_Build_PortableClassLibrary.bat) to build portable class library.
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

> #### https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-156991500

>The manual transaction controls was missing in root_easysetup.
>Do we need to add?

No, you do not need to merge these files.

This is unnecessary in root_easysetup that is not have multiple data providers,
because it is a module to test the multiple data providers.

>Shall we also improve build system? 
>By adding the batch file to build portable class library.

Yes, please.
Improvement should be merged.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation.
We will proceed as described in the above comment.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-155387721
>Is there a problem with the "UI improvement" task ?

There is no problem with the "UI improvement" task 
We tested DPQuery_Tool after merge, it is working as expected.

Thanks,

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Improvement of build system contains the following modification:
- Addition of "3_Build_PortableClassLibrary" batch file
- Changing default build tool as MSBuild, by replacing "z_Common" and "z_Common2" file
- Implementing [code](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/C%23/z_Common2.bat) to check x86 or x64 bit OS
- Implementing [code](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/C%23/z_Common.bat) to set environment variable for only root_2013 and root_2015, as per [this comment](https://github.com/Microsoft/msbuild/issues/52#issuecomment-88674094)

Please confirm and let us know.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for [support](https://github.com/OpenTouryoProject/OpenTouryo/issues/119#issuecomment-157327351) regarding the above comment.
We will do so.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-157302087

It is not the appropriate answer as "it is tested.".

I confirmed the changes because worried.
The result, STATUS_XXX_CREATED was converted to the STATUS_DATA_PROVIDER_SELECTED and Literal.DAP_SQL.

- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root_easysetup/programs/C%23/Frameworks/Tools/DPQuery_Tool/Form1.cs#L566
```C#
((ToolStripStatusLabel)this.statBar.Items[0]).Text = this.RM_GetString("STATUS_XXX_CREATED");
```
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/Form1.cs#L608
```C#
((ToolStripStatusLabel)this.statBar.Items[0]).Text = string.Format(this.RM_GetString("STATUS_DATA_PROVIDER_SELECTED"), Literal.DAP_SQL);
```

Therefor, I think that STATUS_XXX_CREATED was removed.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Therefor, I think that STATUS_XXX_CREATED was removed from here.
Yes, In the task 'Improved the UI of DPQuery_Tool', we removed in pull request https://github.com/SymphonyTeleca/OpenTouryo/pull/64

Reason: we optimized all the messages 'STATUS_XXX_CREATED' with single resource key 'STATUS_DATA_PROVIDER_SELECTED' and Literal.DAP_XXX.

Is this problem?

If this is problem, we will change it to old version. 
Please let us know.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>https://github.com/OpenTouryoProject/OpenTouryo/issues/117#issuecomment-157623183
>Is this problem?

There is no problem for fix of Form1 and Resource.resx,
 However, there is a problem in your confirmation and explanation.
 Because it is originally your question, and I spend a lot of time.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>There is no problem for fix of Form1 and Resource.resx,
ok
>However, there is a problem in your confirmation and explanation.
For confirmation, I asked the question.
Next time, I will explain clearly to make you understand.    
>Because it is originally your question, and I spend a lot of time.
Sorry for the inconvenience

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Please review the pull requests related to merge work sent by us.
once you confirm the changes, we will start merge from root_easysetup to root_2010
We are planning to complete the merge work before December 10

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Reviews can not be sufficiently performed.
But, the merge will be performed sequentially.
Because I will check all of the merge tasks using diff that was got using winmerge ultimately.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We missed some of the files in files folder to merge and conversion to UTF-8 from root to root_easyserup.
we have corrected the above and created pull request.
Please merge the pull request
https://github.com/SymphonyTeleca/OpenTouryo/pull/77

**Comment by daisukenishino** [comment]
# About the SQL and XML files that is converted UTF-8.
FxSqlEncoding value of app.config have also been changed.

Therefore,

## (1)
It will be needed that to change the encoding of existing SQL and XML files.
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/files/resource/Sql

## (2)
It is forgotten to change the specification of the encoding attribute to UTF-8 to some of the XML file.
https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2012/files/resource/Sql/sqlserver/AsyncProcessingService/AsyncProcessingServiceUpdate.xml#L1

## (3)
If you change the default value to UTF-8, you must also change the default encoding of SQL and XML file that is generated by tool to UTF-8.

#### DPQuery_Tool
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool

Because DPQuery_Tool are using FxSqlEncoding value of app.config, there is no problem if you change this. 

- Form1.cs  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/Form1.cs#L297
- app.config  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/app.config#L11

#### DaoGen_Tool
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool

Probably it can be specified by the combo box.
Please check the default value of the combo box.

- Form2.cs  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.cs#L969
  - D層定義情報ファイル  
    - this.cmbDDEncoding.SelectedValue = 65001;
  - テンプレート ファイル  
    - this.cmbDTEncoding.SelectedValue = 65001;
    - this.cmbSTEncoding.SelectedValue = 65001;
  - Daoファイル  
    - this.cmbDFEncoding.SelectedValue = 65001;
  - SQLファイル  
    - this.cmbSFEncoding.SelectedValue = 65001;

Please check.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>(2)
It is forgotten to change the specification of the encoding attribute to UTF-8 to some of the XML file.

We will change this to UTF-8 and send pull request.

>(3)
If you change the default value to UTF-8, you must also change the default encoding of SQL and XML file that is generated by tool to UTF-8.

Yes, already the default encoding is UTF-8.  

>DPQuery_Tool
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool
Because DPQuery_Tool are using FxSqlEncoding value of app.config, there is no problem if you change this.

Yes, we also checked there is no problem since FxSqlEncoding value is reading from app.config. 

>DaoGen_Tool
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool
Probably it can be specified by the combo box.
Please check the default value of the combo box.

we checked the default value of the combo box. it is in UTF-8 encoding.
We also checked the generated files, by default the generated files are in UTF-8 encoding.
Since the default value of the combo box is UTF-8.  

Thanks,

**Comment by daisukenishino** [comment]
## Check result of between 01-70 version and the latest version(01-71) of the root folder
@SandeepNayak077 
The following two problems were confirmed.

### The missing files
Please check there is no problem.
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceSelect.sql
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceStatusUpdate.sql
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceUpdate.sql

### [Improvement of the build system](https://github.com/OpenTouryoProject/OpenTouryo/issues/119)
Among these modifications, modifications that except the Nuget correspondence must have been reflected to the root folder. After a review, it had not been changed only root_VS2015 folder. I want you to add the modifications except the Nuget correspondence. I think that I want you to add the modifications except the Nuget correspondence.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> The missing files

We have intentionally deleted the above mentioned file,
Because, those files are unnecessary as per our investigation and testing.
Hence, we are sure about that this not a problem.
Please let us know.

> Improvement of the build system

We have already completed the Improvement of build system in root and root_easysetup with [this pull request #76](https://github.com/SymphonyTeleca/OpenTouryo/pull/76), and it has already been merged in the nishino branch of [SymphonyTeleca/OpenTouryo](https://github.com/SymphonyTeleca/OpenTouryo/tree/nishino).

The pending activity in this task is the @yusukemaegawa 's [pointed out](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/22/files#r46380458).
We will complete this in between the merge activity.

Please let us know, if anything else is missing in this task.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

> #### The missing files
>We have **intentionally deleted** the above mentioned file,
>Because, those files are unnecessary as per our investigation and testing.

Please tell me this circumstances because I had forgotten this circumstances.

> #### Improvement of the build system
>We have already completed the Improvement of build system in root and root_easysetup with [this pull request #76](https://github.com/SymphonyTeleca/OpenTouryo/pull/76), and it has already been merged in the nishino branch of [SymphonyTeleca/OpenTouryo](https://github.com/SymphonyTeleca/OpenTouryo/tree/nishino). 

I see.
I had forgotten sending the pullrequest from "stc/otr/nishi repo" to "otrp/otr/dev repo".
The time being, I will check using the "stc/otr/nishi repo".

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>The time being, I will check using the "stc/otr/nishi repo".
I confirmed that the improvement of build system is already completed at the root folder.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation of 'Improvement of build system' task.

> Please tell me this circumstances because I had forgotten this circumstances.

As per the new specification, 
We have replaced old files (i.e. Incorrect query files) with the following new files:

(1) To select an AsyncTask from the database

<b>Old file:</b>
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceSelect.sql

<b>New file:</b> 
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\SelectTask.sql

(2) To update the <b>status</b> of selected AsyncTask based on the output of UserProgram, and also to update the <b>progress</b> of AsyncTask.

<b>Old file:</b> 
- root\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceStatusUpdate.sql
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\AsyncProcessingServiceUpdate.sql

<b>New file:</b> 
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\UpdateTaskStart.sql
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\UpdateTaskRetry.sql
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\UpdateTaskFail.sql
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\UpdateTaskSuccess.sql
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\UpdateTaskCommand.sql
- \root\files\resource\Sql\sqlserver\AsyncProcessingService\UpdateTaskProgress.sql

We forgot to delete the old files,
While testing in merge task we found that these files are unnecessary.
Please let us know.

**Comment by daisukenishino** [comment]
@SandeepNayak077 
>We forgot to delete the old files,
>While testing in merge task we found that these files are unnecessary.

Thank you for reporting to me.  I'm leaving for the day.
Now, I am performing a review of the procedure document of the Single IDP.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Your welcome. 
Thank for the replay.

**Comment by daisukenishino** [comment]
# Information about the existing differences
I have investigated the current difference.
This information can be used to check the merged work.

## between the root and the root_easysetup
### UOC_ConnectionOpen method
This is due to the reduced data provider.
- \root\programs\C#\Frameworks\Infrastructure\Business\Business\MyBaseLogic.cs
- \root\programs\C#\Frameworks\Infrastructure\Business\Business\MyFcBaseLogic.cs
- \root\programs\C#\Frameworks\Infrastructure\Business\RichClient\Business\MyBaseLogic2CS.cs
- \root\programs\C#\Frameworks\Infrastructure\Business\RichClient\Business\MyFcBaseLogic2CS.cs

**Comment by daisukenishino** [comment]
# Pointed out of after the merge
## Between the root_easysetup and the root_2010

### Leakage of merge
#### Infrastructure
\root\programs\C#\Frameworks\Infrastructure

- \Business\Business\MyApsBaseLogic.cs is not added.
- \ServiceInterface\AsyncProcessingService\
  - AsyncProcessingService.cs is not merged.
  - TMInProcessDefinition.xml is not merged.

#### DPQuery_Tool
\root\programs\C#\Frameworks\Tools\DPQuery_Tool\
- Form1.cs
- Form1.Designer.cs
- Form1.ja-JP.resx
- Form1.resx
- Form2.cs
- Form2.Designer.cs
- Form2.resx
- Form3.cs
- Program.cs

is not merged.

#### AsyncSvc_sample
\root\programs\C#\Samples\AsyncSvc_sample

##### AsyncSvc_sample
- Properties folder is not added.
- Content of LayerB.cs is not merged.
- LayerD.cs is not deleted.

#### TestAsyncSvc_Sample
- Properties folder is not added.
- Content of Program.cs is not merged.

#### ProjectX_sample
\root\programs\C#\Samples\WebApp_sample\ProjectX_sample\
- Framework\Js\common.js


#### Tests\BDLayer.Test
\root\programs\C#\Tests\BDLayer.Test
- BDLayer.Test.nunit is not merged.
- CRUDTest.cs is not merged.

### Unnecessary merge
#### web.config
web.config file have difference.

### Else
#### DPQuery_Tool
- \root\programs\C#\Frameworks\Tools\DPQuery_Tool\
  - .ja-JP.resx of Form2 does not exist.
  - .Designer.cs and .resx of Form3.cs does not exist.

#### Garbled.
- \root_easysetup\programs\C#\Tests\Public.Test\app.config
  - 用 ---> 逕ｨ

**Comment by daisukenishino** [comment]
@kishoreandukuri 
Correction is not complete.

- https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/root_easysetup/
  - programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample\app.config

- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/
  - programs/C%23/Frameworks/Infrastructure/Framework/Util/FxHttpSessionIndex.cs
  - programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/
    - AsyncProcessingService.cs
    - TMInProcessDefinition.xml
  - programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples/WSClientSL_sample.Web/web.config

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>root_VS2013
https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/
/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/
AsyncProcessingService.cs
TMInProcessDefinition.xml
/programs/C%23/Frameworks/Tools/DPQuery_Tool/Form2.Designer.cs
/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerD.cs

The above changes are already present in nishino branch

Please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

#### root_VS2013
##### AsyncProcessingService
https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L380
```C#
AsyncProcessingServiceParameterValue asyncParameterValue = new AsyncProcessingServiceParameterValue("AsyncProcessingService", "StartCopyFromBlob", "StartCopyFromBlob", "SQL",
                                                                                        new MyUserInfo(selectedAsyncTask.UserId, selectedAsyncTask.TaskId.ToString()));
```
##### TMInProcessDefinition.xml
https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMInProcessDefinition.xml#L9
```XML
<Transmission id="AzureStrageCopy" assemblyName="AsyncProcess" className="AsyncProcess.ProcessCopyJob" />
```

##### DPQuery_Tool/Form2.Designer.cs
https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Frameworks/Tools/DPQuery_Tool/Form2.Designer.cs

There is a difference.

###### VS2012
```C#
// 
// button1
// 
this.button1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(163)))), ((int)(((byte)(189)))));
this.button1.ForeColor = System.Drawing.Color.White;
resources.ApplyResources(this.button1, "button1");
this.button1.Name = "button1";
this.button1.UseVisualStyleBackColor = false;
this.button1.Click += new System.EventHandler(this.button1_Click);
// 
// btnGenerateScreens
// 
resources.ApplyResources(this.btnGenerateScreens, "btnGenerateScreens");
this.btnGenerateScreens.Name = "btnGenerateScreens";
this.btnGenerateScreens.UseVisualStyleBackColor = true;
this.btnGenerateScreens.Click += new System.EventHandler(this.btnGenerateScreens_Click);
// 
// Form2
// 
resources.ApplyResources(this, "$this");
this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(249)))), ((int)(((byte)(249)))));
this.Controls.Add(this.btnGenerateScreens);
```
###### VS2013
```C#
// 
// button1
// 
resources.ApplyResources(this.button1, "button1");
this.button1.Name = "button1";
this.button1.UseVisualStyleBackColor = true;
this.button1.Click += new System.EventHandler(this.button1_Click);
// 
// btnGenerateScreens
// 
resources.ApplyResources(this.btnGenerateScreens, "btnGenerateScreens");
this.btnGenerateScreens.Name = "btnGenerateScreens";
this.btnGenerateScreens.UseVisualStyleBackColor = true;
this.btnGenerateScreens.Click += new System.EventHandler(this.btnGenerateScreens_Click);
// 
// Form2
// 
resources.ApplyResources(this, "$this");
this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
this.Controls.Add(this.btnGenerateScreens);
```

#### VS2015
##### TestAsyncSvc_Sample/app.config
https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config

Do erase startup tab.
```C#
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6"/></startup>
```

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Fixed the above pointed out.
Please merge the below pull requests.
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/61
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/62

**Comment by daisukenishino** [comment]
I did finishes of merge work.
- https://github.com/SymphonyTeleca/OpenTouryo/commit/27e077c869177a5038ff482d2d3aa4ec56532c39
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/commit/3e4c859c5745ec6789310da92f747e811bac23f0
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/commit/e0cef088d27a5802f3db53b8266dbdbfc69541d2
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/commit/ea62cd234f19654b73551ee7260a349518ad0af2
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/commit/c1ffd04ea0bf0e43e3f3bb8638525b3e296e32ce

I will send the pullrequest to repository of the [OpenTouryoProject](https://github.com/OpenTouryoProject) from now.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>I will send the pullrequest to repository of the OpenTouryoProject from now.

We will take latest from OpenTouryoProject  and start code changes.

Thank you

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>We will take latest from OpenTouryoProject and start code changes.

This pull request will be merged in to this weekend.
If you hurry, please take out from following.
- https://github.com/SymphonyTeleca/OpenTouryo/tree/nishino
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Sure, We will take from nishino branch and start working on the tasks..

Thank you
