### ISSUE TITLE
Enhance of MyBaseMVController

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#118]
# Requirement
https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseMVController.cs

## Separating the base part and customizations part.
Separating the base part and customizations part by dividing the base class into two.
MyBaseMVController ---> BaseMVController + MyBaseMVController

### The implementation that to move to BaseMVController
Sessiontimeout detection function will be moved to BaseMVController side, and will leave the customizable part to MyBaseMVController.

### Call "base.OnXXXXX()" method manner.
Should call all "base.OnXXXXX()" methods at the beginning of "BaseMVController and MyBaseMVController.OnXXXXX()" method.

But this (position to call the "base.OnXXXXX()" method) is customizable.

The current "System.Web.Mvc.Controller.OnXXXXX()" is an empty implementation for "protected virtual void". Therefore, there is no affected by the change of the calling location.
http://aspnetwebstack.codeplex.com/SourceControl/latest#src/System.Web.Mvc/Controller.cs

### Does not start using the Session. 
When the session does not exist, always IsNewSession becomes true.
Therefore, to start using the session with the session timeout detection cookie issuing.

Fixed two locations.
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseMVController.cs#L137
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseMVController.cs#L153

As follows.

```C#
Response.Cookies.Set(FxCmnFunction.CreateCookieForSessionTimeoutDetection());
Session["FxDummy"] ="dummy"; // Add this line (Please use the FxHttpSessionIndex)
```
#### HTML.Action method 
System.Web.Mvc.RedirectResult method is called in BaseMVController.OnException method.
But it is not possible to redirect action in the child action.

The following error message is displayed.
"Child actions are not allowed to perform redirect actions."

Therefore, need the following modification.

- An exception occurs in the redirection method in child action.  
Issue#17 of OpenTouryoProject-OpenTouryoTemplates  
https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/17

#### Erroneous detection
If to display "partial view" that have the controller, then session timeout detection cookie will exist and IsNewSession property states will be "true" in the second executing controller.

Therefore,  the following is the limitation.
"Child view's Controller that inherited the MyBaseMVController can not be called using the HTML.Action method from main controller that has possibility that directly accessed by URL."

If you implement the main controller that has possibility that directly accessed by URL.
You can adopt the following countermeasure.
- Invoke partial view by using the HTML.partial method.
- Child view's controller does not inherit MyBaseMVController.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Shall we move error screen implementation also into  BaseMVController?

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>Shall we move error screen implementation also into BaseMVController? 

No, [BaseMVController.OnException](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseMVController.cs#L222) should not be moved because there is likely to be customized.

And, the following correspondence should also be performed.

- "404 Not Found" occurs when I run "MVC_Sample".  
https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/16
- An exception occurs in the redirection method in child action.  
https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/17

**Comment by kishoreandukuri** [comment]
@daisukenishino 

> Session["FxDummy"] ="dummy"; // Add this line (Please use the FxHttpSessionIndex)

Each key in FxHttpSessionIndex should set to "dummy"
e.g.Session[FxHttpSessionIndex.AUTHENTICATION_USER_INFORMATION] ="dummy"
Please confirm our understanding

**Comment by daisukenishino** [comment]
@kishoreandukuri 

#### About call manner of "base.OnXXXXX()" method.
The current implementation.
```C#
protected override void OnActionExecuted(ActionExecutedContext filterContext) 
{             
  ・・・Other processing・・・

  string strLogMessage = "OnActionExecuted 前" + " - " + filterContext.Controller.ToString()+ " - " 
                          + filterContext.ActionDescriptor.ActionName; 
  LogIF.InfoLog("ACCESS", strLogMessage); 
  base.OnActionExecuted(filterContext); 
  LogIF.InfoLog("ACCESS", "OnActionExecuted 後"); 
  
  ・・・Other processing・・・
} 
```

↓ ↓ ↓
Please implemented as follows.

```C#
protected override void OnXXXXX(ActionXXXXXContext filterContext) 
{
  base.OnXXXXX(filterContext); // Move call statement of "base.OnXXXXX ()" method to the top location of the method.
  
  ・・・Other processing・・・
  
  // Log-output processing should be moved to the end of method.
  // Please delete log-output processing of the "後".
  // Please leave only log-output processing of the "前". However, Please delete　character of "前".

  string strLogMessage = "OnActionExecuted" + " - " + filterContext.Controller.ToString()+ " - " 
                          + filterContext.ActionDescriptor.ActionName; 
  LogIF.InfoLog("ACCESS", strLogMessage); 
} 
```

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Thank you for the confirmation.

following method is having log info as
 protected override ViewResult View(IView view, object model)
        {
            LogIF.InfoLog("ACCESS", "View 前");
            return base.View(view, model);
        }

shall we keep this by removing 前 as below

 protected override ViewResult View(IView view, object model)
        {
            LogIF.InfoLog("ACCESS", "View");
            return base.View(view, model);
        }

**Comment by daisukenishino** [comment]
@kishoreandukuri 
Please implement as follows.

```C#
protected override ViewResult View(IView view, object model)
{
  return base.View(view, model);
  LogIF.InfoLog("ACCESS", "View");
}
```

**Comment by kishoreandukuri** [comment]
@daisukenishino 

 > return base.View(view, model);
   LogIF.InfoLog("ACCESS", "View");

its good to keep the statement  LogIF.InfoLog("ACCESS", "View"); before return base.View(view, model);
LogIF.InfoLog("ACCESS", "View");
return base.View(view, model);
compiler will show warning 'Unreachable code detected' if we keep statement after return
 return base.View(view, model);
  LogIF.InfoLog("ACCESS", "View");
Please let us know

**Comment by daisukenishino** [comment]
@kishoreandukuri 

At the same time, I want to ask the following changes.

#### The following is execution order of MVC events.

+ Controller.OnAuthentication ( )
+ Controller.OnAuthorization ( )
+ Controller.OnActionExecuting ( )
+ "Action method is performed here."
+ Controller.OnActionExecuted ( )
+ Controller.OnAuthenticationChallenge ( )
+ Controller.OnResultExecuting ( )
+ "ActionResult or ExecuteResult method is performed here."
+ Controller.OnResultExecuted ( )

#### So I want you to performance measurement and log output in the following three locations.

(No.1)
It measure the performance of the Action method.
+ Controller.OnActionExecuting ( )
+ "Action method is performed here."
+ Controller.OnActionExecuted ( )

(No.2)
It measure the performance of the ActionResult or ExecuteResult method.
+ Controller.OnResultExecuting ( )
+ "ActionResult or ExecuteResult method is performed here."
+ Controller.OnResultExecuted ( )

(No.3)
It measure the performance of the Almost server processing.
+ Controller.OnActionExecuting ( )
+ Almost server processing is performed here.
+ Controller.OnResultExecuted ( )

#### For the implementation of the performance measurement process, please refer to the following.

- MyBaseController.UOC_PreAction(FxEventArgs fxEventArgs)
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseController.cs#L400
- MyBaseController.UOC_AfterAction(FxEventArgs fxEventArgs)
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseController.cs#L446
- MyBaseController.UOC_ABEND(Exception ex, FxEventArgs fxEventArgs)
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Presentation/MyBaseController.cs#L723

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Please check, because I had modify it.
https://github.com/OpenTouryoProject/OpenTouryo/issues/118#issuecomment-151769025

**Comment by kishoreandukuri** [comment]
@daisukenishino 

we will change to the following
protected override ViewResult View(IView view, object model)
{
  ViewResult vr = base.View(view, model);
  LogIF.InfoLog("ACCESS", "View");
  return vr;
}

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>At the same time, I want to ask the following changes.

we will do these changes also

**Comment by daisukenishino** [comment]
@kishoreandukuri 

https://github.com/OpenTouryoProject/OpenTouryo/issues/118#issuecomment-151753797
```C#
Response.Cookies.Set(FxCmnFunction.CreateCookieForSessionTimeoutDetection());
Session["FxDummy"] ="dummy"; // Add this line (Please use the FxHttpSessionIndex)
```
For the above correspondence,
you will need to add the following constants to [FxHttpSessionIndex](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Util/FxHttpSessionIndex.cs).

```C#
public const string DUMMY= "Dummy";
```

And, you will use in the following manner.

```C#
Session[FxHttpSessionIndex.DUMMY] ="dummy";
```

This fix should be applied to the following two.
- OpenTouryoProject/OpenTouryoTemplates repository > develop branch > root_VS2012 folder
- OpenTouryoProject/OpenTouryo repository > develop branch >  root folder

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Thank you for the confirmation.

we will do so in both the repositories

**Comment by kishoreandukuri** [comment]
>For the implementation of the performance measurement process, please refer to the following.

To implement  performance measurement process, Can we use below to display performance information?
 string strLogMessage =
                "," + UserInfo.UserName +
                "," + Request.UserHostAddress +
                "," + "<-----" +
                "," + this.ContentPageFileNoEx +
                "," + fxEventArgs.ButtonID +
                "," + "" +
                "," + this.perfRec.ExecTime +
                "," + this.perfRec.CpuTime

Pleae let us know

**Comment by daisukenishino** [comment]
@kishoreandukuri 

OK!

I think that [it](https://github.com/OpenTouryoProject/OpenTouryo/issues/118#issuecomment-153009214) is a well thought out specification.

- The current implementation
  - Start
```C#
426             string strLogMessage = 
427                 "," + UserInfo.UserName + 
428                 "," + Request.UserHostAddress + 
429                 "," + "----->" + 
430                 "," + this.ContentPageFileNoEx + 
431                 "," + fxEventArgs.ButtonID; 
```

  - End
````C#
467             string strLogMessage = 
468                 "," + UserInfo.UserName + 
469                 "," + Request.UserHostAddress + 
470                 "," + "<-----" + 
471                 "," + this.ContentPageFileNoEx + 
472                 "," + fxEventArgs.ButtonID + 
473                 "," + "" + 
474                 "," + perfRec.ExecTime + 
475                 "," + perfRec.CpuTime; 
```
- Implementation after the change
  - Start
```C#
string strLogMessage =
  ", -" +
  "," + Request.UserHostAddress +
  "," + "----->" +
  "," + filterContext.Controller.ToString() +
  "," +  filterContext.ActionDescriptor.ActionName;
  "," + "OnActionExecuting";
```

  - End
```C#
string strLogMessage =
  ", -" +
  "," + Request.UserHostAddress +
  "," + "<-----" +
  "," + filterContext.Controller.ToString() +
  "," +  filterContext.ActionDescriptor.ActionName;
  "," + "OnActionExecuting" +
  "," + perfRec.ExecTime + 
  "," + perfRec.CpuTime; 
```

Since the following properties do not exist in framework of the MVC version.
- UserInfo.UserName
- this.ContentPageFileNoEx
- fxEventArgs.ButtonID
