### ISSUE TITLE
Primary Key in sample screen of 3tier data binding is always editable.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#120]
# Requirement
I think that the ReadOnly property of the TextBox for the Primary Key should be set to **true**.

In [ProductsDetails.aspx.cs](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/ProductsDetail.aspx.cs#L370), there is the following method.

```c#
private void SetControlReadOnly(bool readOnly)
{
    // 編集可否
    // ReadOnly

    // 主キー
    this.txtProductID.ReadOnly = false;

    (The rest is omitted.)
}
```

The ReadOnly property of the TextBox for the Primary Key is always set to **false**.
Therefore, the Primary Key is always **editable**.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Please give us the requirement of this task.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

This issue was moved to [here](https://github.com/OpenTouryoProject/OpenTouryo/issues/119).

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the reply.
We are analyzing the requirement.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Because this fix related to the substance, this fix has been moved to OpenTouryoProject/OpenTouryo.

This Issue will be closed.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>In ProductsDetails.aspx.cs, there is the following method.
private void SetControlReadOnly(bool readOnly)
{
    // 編集可否
    // ReadOnly

    // 主キー
    this.txtProductID.ReadOnly = false;

    (The rest is omitted.)
}

Instead of changing in ProductsDetails.aspx.cs, we change it in DaoGen_Tool auto generation code.

Is this ok? Please let us know.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

We changed to 

this.txtProductID.ReadOnly = true; 

in Detail.aspx.cs, Detail.aspx.vb, _Screen_Detail.aspx.cs and _Screen_Detail.aspx.vb.

Please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

If the auto-generated template have a problem,
you must modify the automatic generation templates in addition to the following modules.

- /root/files/resource/Screen/
  - ProductsDetail.aspx.cs
  - my_tableDetail.aspx.cs
- /root/programs/C# or VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/
  - ProductsConditionalSearch.aspx
  - ProductsConditionalSearch.aspx.cs
  - ProductsDetail.aspx
  - ProductsDetail.aspx.cs
  - ProductsSearchAndUpdate.aspx
  - ProductsSearchAndUpdate.aspx.cs

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Thank you for the confirmation.

We will change the following also

/root/files/resource/Screen/
ProductsDetail.aspx.cs
my_tableDetail.aspx.cs
/root/programs/C# or VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/
ProductsConditionalSearch.aspx
ProductsConditionalSearch.aspx.cs
ProductsDetail.aspx
ProductsDetail.aspx.cs
ProductsSearchAndUpdate.aspx
ProductsSearchAndUpdate.aspx.cs

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Regards.

NOTICE:
Please write carefully using the mark down.
I am frequently fix your posts.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Sure, we will do so
Thank you

**Comment by kishoreandukuri** [comment]
@daisukenishino 

only the below files needed changes with respect to readonly

>/root/files/resource/Screen/
>ProductsDetail.aspx.cs
>my_tableDetail.aspx.cs
>/root/programs/C# or VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/
>ProductsDetail.aspx.cs

Rest of the files no need to change.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

I see. I fixed that.
And, The mark-down is not appropriate.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Thank you
>And, The mark-down is not appropriate.

[Fixed](https://github.com/OpenTouryoProject/OpenTouryo/issues/120#issuecomment-166572128) the markdown. please check

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Please be like this.

>- /root/files/resource/Screen/
  - ProductsDetail.aspx.cs(.vb)
  - my_tableDetail.aspx.cs(.vb)
- /root/programs/C# or VB/Samples/WebApp_sample/ProjectX_sample/Aspx/sample/3Tier/
  - ProductsDetail.aspx.cs(.vb)

**Comment by kishoreandukuri** [comment]
@daisukenishino 
we will correct it

**Comment by kishoreandukuri** [comment]
@daisukenishino 

we have done code commit and created pull request
https://github.com/SymphonyTeleca/OpenTouryo/pull/82

Please merge.
