### ISSUE TITLE
Porting three functions of ASP.NET to ASP.NET MVC.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#129]
# Requirement
Please port several functions of ASP.NET to ASP.NET MVC.

For the realization of above requirements, please modify the program of root_VS2012.

## (1) The function to prevent session timeout.
I think that this function is able to be ported in ASP.NET MVC easily.
The original function is implemented in the following program.

- common.js#L65  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L65

## (2) The function to prevent double submission.
See the following issue.
https://github.com/OpenTouryoProject/OpenTouryo/issues/112

The original function is implemented in the following program.

- common.js#L179  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L179

Please consider the following points on realizing this function.

### Multiple forms
In ASP.NET MVC, one page (View) may have plural forms. And, controller class can not control the attributes of the form in the page (View).
Therefore, like the following samples, this function should be realized by using JavaScript.

- 【ASP.NET】リンクボタンの二度押し防止 - QA@IT  
http://qa.atmarkit.co.jp/q/1401
- ASP.NET & JavaScriptでコード汚染をしないで2度押し防止 - 手抜きぷろぐらまのメモ帳
http://d.hatena.ne.jp/itaosan/20061225/1167025092

I think the there are two realization methods.

- Search all forms in page and add "onsubmit" event handler in form tag.
- Add event lisner in JavaScript file.
Like the following sample.

```js
// In case of using JQuery
$('form').submit(function() {
    // function to prevent double submittion.
});
```

### Ajax.BeginForm
Because original function supports the UpdatePanel of ASP.NET Ajax currently, I think that this function has to support Ajax.BeginForm. See https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-171613308.

## (3) The function to show progress dialog.
I think that this function is able to be ported in ASP.NET MVC easily.
The original function is implemented in the following program.

- common.js#L413  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L413

Because original function does not support the UpdatePanel of ASP.NET Ajax currently, I think that this function does not have to support Ajax.BeginForm.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>(1) The function to prevent session timeout.
>* common.js#L65
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L65

Do we need to implement in the same way as above in MVC_Sample application?

OR

Shall we place the below javascript code in layout view '_CrudSampleLayout.cshtml' of MVC_Sample application?

function HttpPing() {
            var httpObj = jQuery.get("/PingController/ping", null, function () {
                //動作確認用コード(ping先の画面のソースをアラート表示)
                alert(httpObj.responseText);
                alert('test');
            });
        }
        window.setInterval(HttpPing, 5000);

We will create new controller 'PingController.cs' and  view 'ping.cshtml'  for pinging in MVC_sample application.

Is this ok?

Please let us know.

Thank you

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Please create a common.js for MVC.
And, common.js are linked from [_CrudSampleLayout.cshtml](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/Shared/_CrudSampleLayout.cshtml).
```Javascript
<script src="~/Scripts/common.js"></script>
```

Javascript is implemented in common.js file.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

#### (1) The function to prevent session timeout.
Yes, create a 'PingController.cs' and 'ping.cshtml', and then implement the following javascript to 'common.js'.

```JS
function HttpPing() {
            var httpObj = jQuery.get("/PingController/ping", null, function () {
                //動作確認用コード(ping先の画面のソースをアラート表示)
                alert(httpObj.responseText);
                alert('test');
            });
        }
        window.setInterval(HttpPing, 5000);
```

**Comment by daisukenishino** [comment]
@kishoreandukuri 

https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/27

Please modify as follows, because there is no need to return JSON.
In this case, "Index.cshtml" is not required.

```CS
[HttpGet]
public ActionResult Index()
{
  return EmptyResult();
}
```

Since the unit of the second argument of the setInterval method is a millisecond,
please change "5000" to "5 * 60 * 1000" (= 300,000).

```JS
window.setInterval(HTTPPing, 5000, url);
```
 ↓ ↓ ↓
```JS
window.setInterval(HTTPPing, 5 * 60 * 1000, url);
```

Because I want to ride the path of merge, please also change the following modules.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Please give priority to the above-mentioned correspondence.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

We will complete the above and continue merge work

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>We will complete the above and continue merge work

I see.

Please raise the priority of correspondence of the part of except merge task.
- PingController.cs
- Index.cshtml
- common.js

Because fixes to be mixed, I can not merge the following pullrequest.
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/67

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>Please raise the priority of correspondence of the part of except merge task.
Sure, we started working on this

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>return EmptyResult();
the above is implemented as return new EmptyResult();

**Comment by kishoreandukuri** [comment]
@daisukenishino 

We made the [above](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-170782304) changes.

Please merge the pull request
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/68

**Comment by daisukenishino** [comment]
# Additional requirements

>#### (2) The function to prevent double submission.
##### Ajax.BeginForm
Because original function supports the UpdatePanel of ASP.NET Ajax currently, I think that this function has to support Ajax.BeginForm.

We consider that there is no need to support the Ajax extensions that is provided to WebForm in this function. But, currently, we think that following things are problem.
- This function's specification is stopping the screen operation in Ajax communication.
- We are considering possibility that developer will be reportion this as problems.

If so, there is a need that the function can select enable or disable, in the case of the Ajax.

**Comment by daisukenishino2** [comment]
# Test planning.
Please add a button to  the following screen for the test of this function and, Perform test.

- CrudMu  
https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/CrudMu
- CrudMu2  
https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2012/programs/C%23/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Views/CrudMu2

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Shall we start this task now?
Please let us know

**Comment by daisukenishino** [comment]
@kishoreandukuri 
>Shall we start this task now ?

Please as soon as possible undertake additional requirements.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please as soon as possible undertake additional requirements.

Please share the specifications if any

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Also, please share the task list reg mail dated 18-Jan-2015.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>Please share the specifications if any

Specification of the draft does not exist.
I asked you to consider specifications.
Please tell me about purport, if it is difficult for you to consider specification.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>I asked you to consider specifications.

I considered the [Additional requirements](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-171613308) as specifications.

If these are the only specifications then we start working.

As per the [Test Planning](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-172404247) specifications
>Prevent double transmit at the timing of submit.
This function must be able to select enable or disable.
This selection method must be an easy way for developers.
Please consider for propose this method.

We will add button to enable and disable Prevent double transmit at the timing of submit. 
We will create flag variable with value True or false.
If developer clicks on the button we will set flag=true.
Based on this flag  we will call the function of Prevent double transmit

Please confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>If developer clicks on the button we will set flag = true.
Based on this flag we will call the function of Prevent double transmit.

Please tell me how to set the flag.
I think that "usability" and "no limit" of setting method is important for specifications of this function.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please tell me how to set the flag.
We will implement sample code and show it to you in tomorrow's meeting

**Comment by kishoreandukuri** [comment]
@daisukenishino
> Please tell me how to set the flag.

We have to options to set the flag
1. Developer level
2. User level

<b>1. Developer level:</b> 
In this, we will add the following key-value in web.config
 <add key="EnablePreventDoubleSubmit" value="false" />
add following code in the jquery method of from submit in '_CrudSampleLayout.cshtml'
```javascript
PreventDoubleSubmit = '@System.Configuration.ConfigurationManager.AppSettings["EnablePreventDoubleSubmit"].ToString()';
```
As follows:
```javascript
$("form").live("submit", function (event) {
            PreventDoubleSubmit = '@System.Configuration.ConfigurationManager.AppSettings["EnablePreventDoubleSubmit"].ToString()';
            Fx_OnSubmit();
        });
```
We will add flag 'PreventDoubleSubmit' in the following if condition of function Fx_OnSubmit() 
```javascript
 if (navigator.appName == "Microsoft Internet Explorer" || navigator.appVersion.indexOf("Trident") != -1) 
```
As follows:
```javascript
if (PreventDoubleSubmit&& (navigator.appName == "Microsoft Internet Explorer" || navigator.appVersion.indexOf("Trident") != -1))
```
<b>2. User level:</b>
In this, we will add flag variable say 'PreventDoubleSubmit' in common.js
```javascript
var PreventDoubleSubmit = false;
```
We will add flag 'PreventDoubleSubmit' in the following if condition of function Fx_OnSubmit() 
```javascript 
if (navigator.appName == "Microsoft Internet Explorer" || navigator.appVersion.indexOf("Trident") != -1) 
```
As follows:
```javascript
if (PreventDoubleSubmit&& (navigator.appName == "Microsoft Internet Explorer" || navigator.appVersion.indexOf("Trident") != -1))
```
In Index.cshtml of Crud view, we will add following button
`<button id="button12" style="width: 100%">Enable/Disable Prevent Double Submit</button>`
We will also add following javascript code 
```javascript
 $('#button12').click(function () {
            // 結果をクリアする

            if (PreventDoubleSubmit) {
                PreventDoubleSubmit = false;
            }
            else {
                PreventDoubleSubmit = true;
            }
            return false;
        });
```
As per your indications, we are suggesting option 1.
Please confirm.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

I see.

When you enclose text,
Please specify the type, like this.


\`\`\`XML
\`\`\`

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please specify the type, like this.
Sure

**Comment by daisukenishino** [comment]
# Supplement
to the https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-171613308

### Definition
#### Developer
- People that to develop variety modules as *.cs(vb) and *.aspx and *.aspx.cs(vb).
- People that to build systems as the deploy and config.
- This person select "enable or disable" of the "prevent double submission function".

#### User
- Person that operate Web application's screens.
- This person doesn't select "enable or disable" of the "prevent double submission function".

### Requirement
I think that "usability" and "no limit" of selection method is important for specifications of this function.
This specifications should be a convenient specification for developers.

### Implementation
##### POST of HTML.BeginForm
This setting Should be all or nothing.
Therefor, I think that it is better to set in the app.config file.

##### POST of Ajax.BeginForm and jQuery
This implementation should be used a different flag with POST of HTML.BeginForm.
And, it must be able to control to "enable or disable" for each button or event.

- In this case, I think You can use the JavaScript flag.
- But, this selection method of this flag should be considered enough.
  - I think there is no problem that the value of flag is selected by JavaScript.
  - I think The method to control by the event source of control of attributes of the HTML tag is also interesting. But, it might be difficult to get the control of event source in the event handler on  Cross-browser's JavaScript.
  - Also, I think it is good design that the value of flag will be reverted automatically to default value after receiving the response. I think this can be controlled if you can set an event handler for the response.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
Please give priority to this work because subsequent pullrequest is clogged.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Sure, we are giving priority
Right now, I am creating sprint planning sheet.
after sprint planing, I start the work

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Below is our understanding for the [above](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-173037193)
>POST of HTML.BeginForm
This setting Should be all or nothing.
Therefor, I think that it is better to set in the app.config file.

We will use app.config file key value to disable and enable prevent double transmit functionality

>POST of Ajax.BeginForm and jQuery
This implementation should be used a different flag with POST of HTML.BeginForm.

We will use different flag
```javascript
PreventAjaxDoubleSubmit = false;
```
>I think this can be controlled if you can set an event handler for the response.

We will add Ajax.success method to set the value of flag will be reverted automatically to default value.
```javascript
$(document).ajaxSuccess(function() {
  PreventAjaxDoubleSubmit = false;
}); 
```
>And, it must be able to control to "enable or disable" for each button or event.

we will set  PreventAjaxDoubleSubmit = true; in the following method 
```javascript
$("form").live("submit", function (event) {
            PreventDoubleSubmit = true;
            Fx_OnSubmit();
        });
```

Please confirm.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Please confirm the [above](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-173460158)

**Comment by daisukenishino** [comment]
@kishoreandukuri 

## Pointed out to the following code (1)
```javascript
PreventDoubleSubmit = '@System.Configuration.ConfigurationManager.AppSettings["EnablePreventDoubleSubmit"].ToString()';
```
↓　↓　↓
```javascript
PreventAjaxDoubleSubmit = '@GetConfigParameter.GetConfigValue("EnablePreventDoubleSubmit")';
```

##  Pointed out to the following code (2)
>```javascript
$(document).ajaxSuccess(function() {
  PreventAjaxDoubleSubmit = false;
}); 
```

### .ajaxSuccess()
You should use the following events by the events of the execution order.
- .ajaxSend()
- .ajaxComplete()

###### Reference
- jQuery リファレンス：ajaxStart  
http://www.jquerystudy.info/reference/ajax/ajaxStart.html
  - .ajaxSend()  
ページ内で発生したajax通信のリクエストを送る前に実行するfunctionを設定します。
  - .ajaxComplete()  
ページ内で発生したajax通信が（成功/失敗にかかわらず）完了した時に引数のfunctionを実行します。

### .ajaxSend()
###### How to set the parameter
Select the button that should be enabled this feature.

```javascript
if( - Select the button that should be enabled this feature. - )
{
  PreventAjaxDoubleSubmit = true;
}
```

### .ajaxComplete()
###### How to revert the parameter
```javascript
PreventAjaxDoubleSubmit =false;
```

##  Pointed out to the following code (2)
Does not change the PreventAjaxDoubleSubmit flag in the following events.
I think thant this method is for post in HTML.BeginForm. Please use .ajaxSend() to instead at ajax.

>We will set  PreventAjaxDoubleSubmit = true; in the following method 
```javascript
$("form").live("submit", function (event) {
  PreventDoubleSubmit = true;
  Fx_OnSubmit();
});
```

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Thank you for confirmation and clarification.

We will do code changes as [above](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-173828433)

**Comment by daisukenishino** [comment]
@kishoreandukuri 

### Maybe, necessary corrections
I tought that it is require the following modifications by checking your pull request.

```JS
$(function () {
  $('#button1').click(function () {
    // button1 の場合は、GetCountのActionを実行しメッセージ部分を更新する
    $('#form1').attr('data-ajax-update', '#messageResult');
    $('#form1').attr('action', '@Url.Action("GetCount")');

    // If prevent double submission, then sets the flag to true.
    PreventAjaxDoubleSubmit = true;
  
    $('#form1').submit();
    // サブミットが 2 回発生しないよう、false を返す
    return false;
});
```
##### .ajaxSend()
```JS
$(document).ajaxSend(function () {
  if ( PreventAjaxDoubleSubmit  ) {
    // 二重送信フラグの設定
    Ajax_IsProgressed = true;
    Fx_OnSubmit();
  }
}); 
```
##### .ajaxComplete()
```JS
$(document).ajaxComplete(function () {
  // はじめにタイマをクリアする。
  clearTimeout(ProgressDialogTimer);
  // プログレス ダイアログを非表示にする。
  try {
    document.body.removeChild(AjaxMask);
    document.body.removeChild(AjaxProgressDialog);
  } catch (e) {
    //alert( e );//エラー内容
  }

  // 二重送信フラグの設定
  Ajax_IsProgressed = false;
  PreventAjaxDoubleSubmit = false;
}); 
```

### Unknown point
##### .ajaxSend() and ajaxComplete()
- Does this event occurs at Ajax.BeginForm ?
- Does this event occurs at jQuery raw requests ?  
It is needed to add a test case of the jQuery raw requests on the test screen.

**Comment by kishoreandukuri** [comment]
>Does this event occurs at Ajax.BeginForm ?

Yes, This event occurs only at Ajax.BeginForm 

>Does this event occurs at jQuery raw requests ?
No, only for Ajax

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Just to inform you, if we set 
```Javascript
Ajax_IsProgressed = true;
```
Then Progress dialogue will not display.

We have made the [above](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-174367886) changes

Please review the pull request
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/76

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>To be exact, the followings are needed to check while operating for this code.
Therefor, I will check this code while operating.

I had carried out review and operation check and modification to your implementation.

- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/77

But, this code has one problem as far as I know.
It is that the mask stretched at the bottom of the loading dialog is not functioning.
Please send the pullrequest after fix this problem.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>It is that the mask stretched at the bottom of the loading dialog is not functioning.
We will check this 

>Please send the pullrequest after fix this problem.
Sure, we will send pull reuqest

**Comment by daisukenishino** [comment]
@kishoreandukuri 

I was supplemented little to [the explanation](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-174968192).

Please check.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>I was supplemented little to the explanation.

We have checked, we will check the the issue once we complete the planned activities in the sprint

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>It is that the mask stretched at the bottom of the loading dialog is not functioning.
We have done research on the above.
In IE8, the mask is displaying.
In IE9, the mask is not displaying.
We are figuring out to fix this issue in IE9

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>We are figuring out to fix this issue in IE9

We found the solution. This is because opacity is blocking in IE9.
<b>Solution1</b>: hit F12 (debugging console), then F5 (refresh). IE9 pops up a little box: 'Internet Explorer restricted this page from running scripts or ActiveX controls' Click the button 'Allow Blocked content' and your opacity should work.

<b>Solution2</b>:use compatibility mode

 <meta http-equiv="X-UA-Compatible" content="IE=8" >  

For more information, please refer the following

http://stackoverflow.com/questions/11796014/opacity-not-working-in-ie9

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-177843426

Thank you for providing valuable information.

>Our suggestion is to use Solution2

I think that it is not appropriate to use the settings as compatibility mode of IE.
Therefore I think **"solution 2"** is not appropriate.
If the alternative to the mask is not found, We will remove the support of the mask.

Please research a little more alternative.
If the alternative does not exist, please report it.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
You are welcome.
>Please research a little more alternative.
>If the alternative does not exist, please report it.

Sure, we will continue our research and report you

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Sure, we will continue our research and report you

While continuing research, we have found the problem is not because of Opacity.
Below code in common.js method 'Fx_CreateMask()' is having problem
```Java script
   _div.style.height = Fx_getContentsHeight(); //"100%";では、初期表示画面サイズになってしまう。
    _div.style.width = Fx_getBrowserWidth(); //"100%";では、初期表示画面サイズになってしまう。
```
this should be 

```Java script
 _div.style.height = Fx_getContentsHeight()+"px"; //"100%";では、初期表示画面サイズになってしまう。
  _div.style.width = Fx_getBrowserWidth() + "px"; //"100%";では、初期表示画面サイズになってしまう。
```
<b/>Before change:</b>
```Java script 
function Fx_CreateMask() {

    var _div = document.createElement("div");

    _div.style.top = "0px";
    _div.style.left = "0px";
    _div.style.height = Fx_getContentsHeight(); //"100%";では、初期表示画面サイズになってしまう。
    _div.style.width = Fx_getBrowserWidth(); //"100%";では、初期表示画面サイズになってしまう。
    _div.style.position = "absolute";

    // 1000なら最前面だろうという仕様（ToMost相当が無い）
    _div.style.zIndex = "1000";

    // 分かりやすいように半透明 (0に設定しても良い)
    _div.style.opacity = 0.5;
    // IE 8用の透明度の設定(0に設定しても良い)
    _div.style.filter = "alpha(opacity=50)";
    // 分かりやすいように着色(若しくは無色)
    _div.style.backgroundColor = 'gray';

    AjaxMask = _div;
}
```
<b/>After change:</b>
```Java script 
function Fx_CreateMask() {

    var _div = document.createElement("div");

    _div.style.top = "0px";
    _div.style.left = "0px";
    _div.style.height = Fx_getContentsHeight()+"px"; //"100%";では、初期表示画面サイズになってしまう。
    _div.style.width = Fx_getBrowserWidth() + "px"; //"100%";では、初期表示画面サイズになってしまう。
    _div.style.position = "absolute";

    // 1000なら最前面だろうという仕様（ToMost相当が無い）
    _div.style.zIndex = "1000";

    // 分かりやすいように半透明 (0に設定しても良い)
    _div.style.opacity = 0.5;
    // IE 8用の透明度の設定(0に設定しても良い)
    _div.style.filter = "alpha(opacity=50)";
    // 分かりやすいように着色(若しくは無色)
    _div.style.backgroundColor = 'gray';

    AjaxMask = _div;
}
```

We have test the code. Now the mask is displaying in IE9 and other browsers also

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We have done the [above](https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-177916866) changes and created pull request.

Please merge the pull request
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/81

**Comment by daisukenishino** [comment]
@kishoreandukuri 

I have two requests.

- Please check the operation on the IE11.
  - The reason for this is in the change of the support policy of IE. Please check the following if necessary.
    - https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
    - https://www.ipa.go.jp/security/ciadr/vul/20151215-IEsupport.html
  - Acceptance work of this pullrequest will be started when operation was confirmed on the IE11.
- Also, please check the operation of [ProjectX_sample](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L799) on the IE11.  
If there is a problem in the same manner, I will issue this as a new issue.

Please comfirm.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We will check the above and confirm

**Comment by daisukenishino** [comment]
@kishoreandukuri 

> About the supported browsers and versions for testing  at the OpenTouryo Projects.

Please support the latest version of a modern browsers as follows.
- IE11
- Edge
- Chrome
- Firefox
- Safari

Please check only in IE11 for features that use the showModalDialog.
Discontinue of support of old version is not a problem along with the change of support policy.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please check the operation on the IE11.

In IE11 also the mask is dispalying
![image](https://cloud.githubusercontent.com/assets/7530499/12746301/f81ae11e-c9c3-11e5-957a-fc7e5831f058.png)

>Also, please check the operation of ProjectX_sample on the IE11.

In ProjectX_sample on the IE11, the mask is not displaying
![image](https://cloud.githubusercontent.com/assets/7530499/12746336/2506698c-c9c4-11e5-9a0f-ec6481125e9a.png)

**Comment by daisukenishino** [comment]
@kishoreandukuri 
>https://github.com/OpenTouryoProject/OpenTouryo/issues/129#issuecomment-178494652

- Please continue to test in other browsers.  
We will start the acceptance after its completion.
- And, I had issued this as a [new issue](https://github.com/OpenTouryoProject/OpenTouryo/issues/150).

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please continue to test in other browsers.

Sure, we will continue the testing
>And, I had issued this as a new issue.

I checked

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please continue to test in other browsers.

We have tested in the following browsers, the mask is diaplying in MVC_Sample 
Chrome
Firefox
Safari

In ProjectX_sample,  the mask is not displaying on the above browsers

>Edge
We don't have Windows 10 machine to test

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>In ProjectX_sample, the mask is not displaying on the above browsers.

[The issue](https://github.com/OpenTouryoProject/OpenTouryo/issues/150) has been added.

>We don't have Windows 10 machine to install and test on Edge browser.

Because the Edge's share of seems still low,
if working normally on the Chrome,
Currently, I think that there is no problem.

Therefor, I have merged [the pullrequest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/81).

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>The issue has been added.

We have checked and confirmed

>Currently, I think that there is no problem.

Please let us know if there will be any problem

>Therefor, I have merged the pullrequest.
Thank you for accepting the pull request

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Can not be prevented double submission problem might be solved by the following.

see :
- http://www.jquerystudy.info/reference/ajax/ajaxStart.html
- http://ameblo.jp/blueskyame/entry-11071818511.html

It may be possible to prevent the submission by calling the abort() method of the jqXHR object of second argument of ajaxSend() method.

Maybe like this :

```JS
// Enables the functionality of Prevent Double Submit for Ajax.BeginForm based on the button submitted. 
$(document).ajaxSend(function (eo, jqXHRo, settings) {
    // checks and disables progress dialogue if PreventAjaxDoubleSubmit set to true.
    if (PreventAjaxDoubleSubmit) {
        if(Fx_OnSubmit())
        {
            // 二重送信フラグの設定
            Ajax_IsProgressed = true;
        }
        else
        {
            jqXHRo.abort();
        }
    }
});
```

**Comment by daisukenishino** [comment]
@kishoreandukuri 

It could be satisfied the requirements by following implementations.

```JS
// Ajax：処理中かどうか
var Ajax_IsProgressed = false;

// Flag variable for enable/disable "Prevent Double Submit functionality" for Ajax.BeginForm.
var PreventAjaxDoubleSubmit = false;

//  Flag variable for control "Prevent Double Submit functionality" for Ajax.BeginForm.
var IsAborted = false;

// ---------------------------------------------------------------
// Ajaxの開始前イベント処理
// ---------------------------------------------------------------
// Enables the functionality of Prevent Double Submit for Ajax.BeginForm based on the button submitted. 
$(document).ajaxSend(function (eo, jqXHRo, settings) {
    // checks and disables progress dialogue if PreventAjaxDoubleSubmit set to true.
    if (PreventAjaxDoubleSubmit) {
        if ( Fx_OnSubmit() ) {
            // 二重送信フラグの設定
            Ajax_IsProgressed = true;
        }
        else {
            IsAborted = true;
            jqXHRo.abort();
        }
    }
});

// ---------------------------------------------------------------
// Ajaxの終了後イベント処理
// ---------------------------------------------------------------
//$(document).ajaxComplete(function (eo, jqXHRo, settings) {

// ---------------------------------------------------------------
// Ajaxの正常終了後イベント処理
// ---------------------------------------------------------------
// 引数
//     ・第1引数：イベントオブジェクト
//     ・第2引数：jqXHRオブジェクト
//     ・第3引数：ajaxのセッティング情報
// 戻り値  －
// ---------------------------------------------------------------
$(document).ajaxSuccess(function (eo, jqXHRo, settings) {
    // ajax通信が正常終了した場合
    Fx_ClearPreventDoubleSubmissionSettings();
});

// ---------------------------------------------------------------
// Ajaxの異常終了後イベント処理
// ---------------------------------------------------------------
// 引数
//     ・第1引数：イベントオブジェクト
//     ・第2引数：jqXHRオブジェクト
//     ・第3引数：ajaxのセッティング情報
//     ・第4引数：例外オブジェクト
// 戻り値  －
// ---------------------------------------------------------------
$(document).ajaxError(function (eo, jqXHRo, settings, error) {
    // ajax通信が異常終了した場合、

    if (IsAborted)
    {
        // 二重送信防止した場合。
        // ・・・何もしない。
    }
    else
    {
        // その他の異常終了。
        Fx_ClearPreventDoubleSubmissionSettings();
    }
});

// ---------------------------------------------------------------
// 二重送信防止機能の設定を解除
// ---------------------------------------------------------------
// 引数    －
// 戻り値  －
// ---------------------------------------------------------------
function Fx_ClearPreventDoubleSubmissionSettings()
{
    // はじめにタイマをクリアする。
    clearTimeout(ProgressDialogTimer);
    // プログレス ダイアログを非表示にする。
    try {
        document.body.removeChild(AjaxMask);
        document.body.removeChild(AjaxProgressDialog);
    } catch (e) {
        //alert( e );//エラー内容
    }

    // 二重送信フラグの設定
    Ajax_IsProgressed = false;

    //Disables Prevent Double Submit finctionality by setting flag to flase.
    PreventAjaxDoubleSubmit = false;
}
```

@yusukemaegawa 

Please test and [marge](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/31).

##### Notes : 
"Prevent double submission function" is only enabled between events that turn on the flag.
```JS
PreventAjaxDoubleSubmit = true;
```

Please test using following button events.
- $('#button1').click(function () {
- $('#button22').click(function () {
