### ISSUE TITLE
WebProxy.GetDefaultProxy() method is now obsolete.

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#130]
[デプロイ部品](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DeployZipPackWithHTTP/Program.cs#L1869)で、

```cs
WebProxy.GetDefaultProxy();
```

を呼び出していますが、[MSDN](https://msdn.microsoft.com/ja-jp/library/system.net.webproxy.getdefaultproxy(v=vs.110).aspx)には、「メモ: この API は現在使用できません。」との記述があり、代替のメソッドなどに置き換える必要があると思います。

**Comment by daisukenishino** [comment]
@yusukemaegawa 

.NET4.5以降で使用できないようなので、root_VS2012以降は修正する必要がありそうですね。
以下を参考にして修正方法を検討しましたが、このAPIを使用するカバレージを削除するだけで良さそうです。

- [GetDefaultProxy の代替えは？](https://social.msdn.microsoft.com/Forums/ja-JP/eb5d65bd-8646-49f0-b57e-e12bf4c2174d/getdefaultproxy-?forum=netfxgeneralja)
- [WebProxy.GetDefaultProxy() は古い形式です:Gushwell's C# Dev Notes](http://gushwell.ldblog.jp/archives/51829027.html)
- [プロキシサーバーを使用してダウンロードする: .NET Tips: C#, VB.NET](http://dobon.net/vb/dotnet/internet/useproxy.html)

**Comment by daisukenishino** [comment]
- WebRequestの派生クラスであれば、自動的にシステムのプロキシ情報を用いてアクセスする。
- このプロキシ情報は、[DefaultWebProxy](https://msdn.microsoft.com/ja-jp/library/system.net.webrequest.defaultwebproxy.aspx)を
- IWebProxyを独自実装のものに変更したい場合には作る必要があります。

**Comment by daisukenishino** [comment]
@kishoreandukuri 
Please modified as follows.

https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DeployZipPackWithHTTP/Program.cs#L1857

```C#
// Proxyサーバ
if (entry.ProxyURL.ToLower() == "none")
{
    // Proxyサーバなし（null）
    hwReq.Proxy = null;

    // ※ GlobalProxySelection.GetEmptyWebProxy()は古い形式
}
else if (entry.ProxyURL == null || entry.ProxyURL == "")
{
    // Proxyサーバなし（デフォルト）
    //proxy = (WebProxy)GlobalProxySelection.Select;// 古い形式

    proxy = (WebProxy)WebProxy.GetDefaultProxy();// 古い形式
    // Internet Exploreの設定を使用する

}
else
{
    // Proxyサーバあり
    proxy = new WebProxy(new Uri(entry.ProxyURL));
}
```
↓ ↓ ↓
```C#
// Proxyサーバ
if (entry.ProxyURL.ToLower() == "none")
{
    // Proxyサーバなし（null）
    hwReq.Proxy = null;

    // ※ GlobalProxySelection.GetEmptyWebProxy()は古い形式
}
else if (entry.ProxyURL == null || entry.ProxyURL == "")
{
    // 何もしない → DefaultWebProxyプロパティの値を使用する。
}
else
{
    // Proxyサーバあり
    proxy = new WebProxy(new Uri(entry.ProxyURL));
}

```

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Sure, we already added https://github.com/OpenTouryoProject/OpenTouryo/issues/130#issuecomment-167212593 task in the sprint plan.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

The above modified code can be further optimized as follows:

```
else if (entry.ProxyURL == null || entry.ProxyURL == "")
{
    // proxy = (WebProxy)WebProxy.GetDefaultProxy();// 古い形式
    // 何もしない → DefaultWebProxyプロパティの値を使用する。
}
```
↓ ↓ ↓

```
else if (entry.ProxyURL == null || entry.ProxyURL == "")
{
    // proxy = (WebProxy)WebProxy.GetDefaultProxy();// 古い形式
    // 何もしない → DefaultWebProxyプロパティの値を使用する。
    return hwReq;
}
```

<b>Reason:</b>
We know that the value of proxy is null, when the above else-if condition is satisfied,
Then there is no use to again check [this condition](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DeployZipPackWithHTTP/Program.cs#L1880).

Hence, we can skip  [this condition](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DeployZipPackWithHTTP/Program.cs#L1880) check by implementing following line in the above else-if condition.

```
    return hwReq;
```

Please let us know.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

In this case,
I think following decision coverage also should do the coding as following.

```CS
if (entry.ProxyURL.ToLower() == "none")
{
    // Proxyサーバなし（null）
    hwReq.Proxy = null;

    // ※ GlobalProxySelection.GetEmptyWebProxy()は古い形式
    return hwReq;
}
```

But, I prefer to be only one exit.
Since the reason can do the end processing codeing in one place.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> But, I prefer to be only one exit.
> Since the reason can do the end processing codeing in one place.

If this is the case, then there is no modifications required.
We will also prefer for single exit.

However, do not merge the [pull request-88](https://github.com/SymphonyTeleca/OpenTouryo/pull/88).
We will resend the pull request because of [this reason](https://github.com/SymphonyTeleca/OpenTouryo/pull/88#issuecomment-169966380).

**Comment by daisukenishino** [comment]
@SandeepNayak077 

[pull request-88](https://github.com/SymphonyTeleca/OpenTouryo/pull/88) has another problem.

Please check the ["Files changed" tab](https://github.com/SymphonyTeleca/OpenTouryo/pull/88/files).

I think that the feature branch is needed to do pull operation against nishino branch.
Or, There is a need to create feature branch as new from the nishino branch.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you closing the pull request-88.

Please review and merge the [pull request-89](https://github.com/SymphonyTeleca/OpenTouryo/pull/89)
