### ISSUE TITLE
To merge the changes ( - Until March 31)

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#131]
# Requirement
Timing of the release has been imminent.

- The changes to the root folder will be merged as follows.
  - root  
\-> root_2010(.NET3.5) -> root_VS2012(.NET4.5)  
\-> root_VS2013(.NET4.5.1) -> root_VS2015(.NET 4.6)
  - We had deleted the root_easysetup. and We will stop update of this.  
Because some of .NET Framework will be no longer supported at January 12, 2016.  
http://blogs.msdn.com/b/dotnet/archive/2014/08/07/moving-to-the-net-framework-4-5-2.aspx

- Do the merge work by refer the following URL as the guide.
  - https://github.com/OpenTouryoProject/OpenTouryo/issues/38
  - https://github.com/OpenTouryoProject/OpenTouryo/issues/104
  - https://github.com/OpenTouryoProject/OpenTouryo/issues/113
  - https://github.com/OpenTouryoProject/OpenTouryo/issues/117

**Comment by daisukenishino** [comment]
## Additional requests
#### MyBusinessApplicationExceptionMessageResource.resx 
There is "*Resource.designer.* files" that is not auto generating SAMPLE_ERROR method from the following definition and designer tool.

```XML
<data name="SAMPLE_ERROR" xml:space="preserve"> 
<value>Message_SampleError </value> 
</data> 
```
#### Slight change
Because the diff check become cumbersome, unnecessary differences should to be the same by merge.

Example:

##### The difference of only one space.
-\root_VS2012\-\VB\-\TestAsyncSvc_Sample\app.config
```XML
<add key="FxLog4NetConfFile" value="C:\root\files\resource\Log\SampleLogConf.xml" />
```
-\Other\app.config
```XML
<add key="FxLog4NetConfFile" value="C:\root\files\resource\Log\SampleLogConf.xml"/>
```

##### The difference of only one space.
```TXT
The OpenTouryo is support the data provider of various,
```
-\root_VS2013\Readme.md
```TXT
The Open Touryo is support the data provider of various,
```
##### Added position of the property is different.
- \root_VS2010\-\FxHttpSessionIndex.cs
- \root_VS2012\-\FxHttpSessionIndex.cs

**Comment by kishoreandukuri** [comment]
@daisukenishino 

In sprint#44, we have added [Merge task](https://github.com/OpenTouryoProject/OpenTouryo/issues/131).

since this is closed, Please let us know which tasks we have to add in sprint plan.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

This is the operation mistake.
I did reopene this issue.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
About the start of the task.

- You need to reflect the change until the end of February in the merge work.
- Please check whether common.js fixes are merged into all of common.js.  
https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/master
  - ProjectX_sample  
e.g. : /root_VS2015/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js
  - WSClientSL_sample  
e.g. : /root_VS2015/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples/WSClientSL_sample.Web/Framework/Js/common.js
  - WSClientWinStore_samples  
e.g. : /root_VS2015/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/WSClientSL_sample.Web/Framework/Js/common.js
  - WindowsAzureProject  
e.g. : /root_VS2015/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/Framework/Js/common.js
  - And all of vb versions.

**Comment by supragyan** [comment]
@daisukenishino 

W have compared the web.config file of 'ServiceInterface/ASPNETWebService' in between [root](https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/root/programs/VB/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService/web.config#L12) and [root_VS2010](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService/web.Config#L25).
When there is a position mismatch of property then we should merge the base version(i.e. root).

But in this case we think root_VS2010 is correct.
Because the comment description matches the property setting.

Please let us know.

**Comment by supragyan** [comment]
@daisukenishino 

Please confirm the above queries.
So that we can create pull request for merging from root to root_2010 version

Regards

**Comment by daisukenishino** [comment]
@supragyan 

When you have questions of the merge task, then compare between root and root_2010 and root_2012 and root_2013 and root_2015 in **master branch**. you can find answer at there.

**Comment by supragyan** [comment]
@daisukenishino 

ok we will check in master branch

**Comment by daisukenishino** [comment]
# How to verify and test.

### Verify

##### Check the original difference.
Compare between root - root_VS2015 in master branch.

##### Check the difference after the merge.
Compare between root - root_VS2015 in feature branch.

##### Note:
Do not merge the differences of between old and new VS version to the new VS version.

### Test
- Please test using the check list that you previously created.
- Test should be carried out in two places of the "STC / feature branch" and "OTP / develop branch".
- "OTP / develop branch" is tested after merge.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

<h3>Our observations </h3>

<b>Public.csproj</b>

This file contains the Oracle Dam references [here](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Infrastructure/Public/Public.csproj#L76) and [here](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Infrastructure/Public/Public.csproj#L85).
We think, this code must be removed (root_VS2012 --> root_VS2010).

<b>MyBusinessApplicationExceptionMessageResource.Designer.cs</b>(Both C# and VB)

As described in [this comment](https://github.com/OpenTouryoProject/OpenTouryo/issues/131#issuecomment-166493425),
The SAMPLE_ERROR method must be manually added or merged as follows
[root_VS2015](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L67)-->[root_VS2013](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L63)-->[root_VS2012](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L63)-->[root_VS2010](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L63)-->[root](https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/root/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L63)

<b>DummyDaps.cs<b>

[This code](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Tools/DPQuery_Tool/DummyDaps.cs#L45) must be uncommented, to make the uniformity between root_VS2010 and root_VS2012 and root_VS2013 and root_VS2015.

<b>/AsyncSvc_sample/TestAsyncSvc_Sample/app.config <b>(Only in VB)

The value of FxSqlEncoding property must be changed from "shift_jis" to "utf-8" as follows.
[root_VS2012](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2012/programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config#L15)-->[root_VS2010](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config#L15)-->[root](https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/root/programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config#L15)

Please confirm our above understandings.
If this understanding is correct we will make the above changes and create additional pull request.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>##### Public.csproj
This file contains the Oracle Dam references [here](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Infrastructure/Public/Public.csproj#L76) and [here](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Infrastructure/Public/Public.csproj#L85).
We think, this code must be removed (root_VS2012 --> root_VS2010).

Yes, please do so.
OpenTouryoTemplates does not browse the additional dams that they aren't included standard dam.

>##### MyBusinessApplicationExceptionMessageResource.Designer.cs (Both C# and VB)
As described in [this comment](https://github.com/OpenTouryoProject/OpenTouryo/issues/131#issuecomment-166493425),
The SAMPLE_ERROR method must be manually added or merged as follows
[root_VS2015](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L67)-->[root_VS2013](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L63)-->[root_VS2012](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2012/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L63)-->[root_VS2010](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L63)-->[root](https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/root/programs/C%23/Frameworks/Infrastructure/Business/Resources/MyBusinessApplicationExceptionMessageResource.Designer.cs#L63)

Yes, if this comment exists only in VS2015, this should be reflected by the above path.

>##### DummyDaps.cs
[This code](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Tools/DPQuery_Tool/DummyDaps.cs#L45) must be uncommented, to make the uniformity between root_VS2010 and root_VS2012 and root_VS2013 and root_VS2015.

Yes, this is not DamOraODP on ODP.NET, this is DamOraClient on System.Data.OracleClient.
System.Data.OracleClient is deprecated at .NET 4.0.
Therefore, DamOraClient should be removed from root_VS2010.
And, this comment out of dummy type should be removed.

>##### /AsyncSvc_sample/TestAsyncSvc_Sample/app.config <b>(Only in VB)
The value of FxSqlEncoding property must be changed from "shift_jis" to "utf-8" as follows.
[root_VS2012](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2012/programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config#L15)-->[root_VS2010](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config#L15)-->[root](https://github.com/SymphonyTeleca/OpenTouryo/blob/nishino/root/programs/VB/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config#L15)

Yes, please do so.
Please also check the encoding of the SQL file, just in case.

・・・

I was merged all pullrequest of this merge task.
https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44

I will check this with master and nishino branches by the [above method](https://github.com/OpenTouryoProject/OpenTouryo/issues/131#issuecomment-197704696) from now.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have modified according to the above comment and created [pull request#139](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/139) and [pull request#112](https://github.com/SymphonyTeleca/OpenTouryo/pull/112).
Please review and merge.

> Please also check the encoding of the SQL file, just in case.

Okay we will check the encoding of the SQL files and report you if there is any problem.

> I was merged all pullrequest of this merge task.
> OpenTouryoProject/OpenTouryoTemplates#44

Thank you for the information.
Please let know your observations.

**Comment by daisukenishino** [comment]
# Result of check the original (master) difference.
## root <---> root_easysetup(3.5)
### README.md
- About deploy of root folder.
- About deploy of provider.

### Due to removed dam
#### UOC_ConnectionOpen(CSharp and VB)
- MyApsBaseLogic.UOC_ConnectionOpen
- MyBaseLogic.UOC_ConnectionOpen
- MyFcBaseLogic.UOC_ConnectionOpen
- MyBaseLogic2CS.UOC_ConnectionOpen
- MyFcBaseLogic2CS.UOC_ConnectionOpen

#### DPQuery_Tool
- DummyDaps.cs (Commented out of dummy type was removed.)
- Form1.cs (The actual type of OracleClient was commented out.)

#### ProjectX_sample(CSharp and VB)
- \App_Code\testPublic
- \Aspx\testPublic

### *Resource.Designer.cs
- PublicExceptionMessageResource.Designer.cs (Runtime Version)
- DPQuery_Tool\Resources\Resource.Designer.cs (gen equal en or ja)

### *.config

#### app.config
##### Most of Samples(CSharp and VB)
- connectionStrings section

#### web.config
##### ASPNETWebService (CSharp and VB)
- connectionStrings section
- ★ "<add assembly="IBM.Data.DB2" is exsisted at only VB version.

##### ProjectX_sample(CSharp and VB)
- connectionStrings section

## root_easysetup(3.5) <---> root_VS2012

### README.md
- New Architecture is supported.
- Changed to Template from the main body.

### Problems
- ★ FxHttpSessionIndex.cs(position)
- ★ FxSqlEncoding in "VB"\Samples\AsyncSvc_sample\TestAsyncSvc_Sample\app.config (root and root_2010) is wrong(shift_jis).
- ★ MyBusinessApplicationExceptionMessageResource.Designer.vb of root_easysetup don't have SAMPLE_ERROR.

### WPFToolkit is deleted(CSharp and VB)
- \Samples\2CS_sample\2CSClientWPF_sample\Window1.xaml
- \Samples\WS_sample\WSClient_sample\WSClientWPF_sample\Window1.xaml
- \Samples\WS_sample\WSClient_sample\WSClientWPFbap_sample\Page1.xaml

### JSON Service Interface
- \Samples\WebApp_sample\ProjectX_sample
  - \App_Code\
    - IJSONService.cs
    - JSONService.svc.cs
  - \Aspx\testFxLayerP\table\
    - testJQGridJson.aspx
    - testJQGridJson.aspx.cs
  - \Content
  - \Scripts
  - \WebService

### Support new Architecture
#### MVC is added
##### Infrastructure
- MyBaseMVController.cs(.vb)
- BaseMVController.cs( ★ vb version is not exist. )

##### Samples
- MVC_Sample
- SPA_Sample
- build batch
  - 3_Build_Framework.bat
  - 10_Build_WebApp_sample.bat

#### StoreApp is added
##### Samples
- WSClientWinStore_samples

### *.config
#### web.config
##### ASPNETWebService
- configSections section
- compilation section
- assemblies section is deleted.
- pages section is deleted.
- httpHandlers section is deleted.
- httpModules section is deleted.
- system.codedom section is deleted.
- system.webServer section is deleted.
- runtime section is deleted.

##### ProjectX_sample
- configSections section
- compilation section
- assemblies section is deleted.
- pages section is deleted.
- httpHandlers section is deleted.
- httpModules section is deleted.
- system.codedom section is deleted.
- system.webServer section is deleted.
- runtime section is deleted.
- system.serviceModel.services section is added.
- system.serviceModel.behaviors section is added.
- system.serviceModel.serviceHostingEnvironment section is added.
- system.serviceModel.bindings section's format is changed(vb ver isn't changed).
- system.serviceModel.client section's format is changed(vb ver isn't changed).

## root_2012 <---> root_VS2013
Can not be found only a small difference and the version information.

### README.md
Setup procedure is changed.

### Support new Architecture
#### Azure is added
- WinAzure_sample

## root_2013 <---> root_VS2015
Can not be found only a small difference and the version information.

### *.Designer.cs
Generated code is canged to en from ja.

- MyBusinessApplicationExceptionMessageResource.Designer.cs(.vb)
- MyBusinessSystemExceptionMessageResource.Designer.cs(.vb)
- FrameworkExceptionMessageResource.Designer.cs
- PublicExceptionMessageResource.Designer.cs
- \programs\C#\Frameworks\Tools
  - \DeployZipPackWithHTTP\Resources\Resource.Designer.cs
  - \DaoGen_Tool\Resources\Resource.Designer.cs
  - \DPQuery_Tool
    - \Properties\Resources.Designer.cs
    - \Resources\Resource.Designer.cs

- \programs\C#\Samples
  - \2CS_sample\GenDaoAndBatUpd_sample\Properties\Resources.Designer.cs
  - \WS_sample\WSClient_sample\AuthServiceClient
    - \Properties\Settings.Designer.cs
    - \Web References\ASPNETWebService\Reference.cs

- And, most of the Application.Designer.vb

**Comment by daisukenishino** [comment]
# Check the difference after the merge (nishino).
I will conduct on April 4.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Please fix after checking the above pointed out.
https://github.com/OpenTouryoProject/OpenTouryo/issues/131#issuecomment-204337599

**Comment by daisukenishino** [comment]
# [Check the difference between "original" and "after the merge".](https://github.com/OpenTouryoProject/OpenTouryo/issues/131#issuecomment-197704696)

I will check in today .

**Comment by daisukenishino** [comment]
@SandeepNayak077 

- Did you execute the [test](https://github.com/OpenTouryoProject/OpenTouryo/issues/131#issuecomment-197704696) ?
- I will check all the build procedure using build *.bat.
- I will merge the current pullrequests after the check has been completed.
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44
  - https://github.com/OpenTouryoProject/OpenTouryo/pull/170
- After merge to ["OTP / develop branch"](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/), I will request you test of the "OTP / develop branch".

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> Did you execute the test ?

Yes we have tested.

> After merge to "OTP / develop branch",
> I will request you straightforward test of the "OTP / develop branch".

Please let us know once its done.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Please let us know once its done.

Since the review will take up to 8 April,
therefore, you should test in "nishino branch" rather than "develop branch".

**Comment by supragyan** [comment]
@daisukenishino 

>https://github.com/OpenTouryoProject/OpenTouryo/issues/131#issuecomment-204292088
DummyDaps.cs
Therefore, DamOraClient should be removed from root_VS2010.

But DamOraClient still present(uncomment) in root_VS2010.
https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2010/programs/C%23/Frameworks/Tools/DPQuery_Tool/DummyDaps.cs#L45

Do we need to remove it or do we need to keep it as?

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

maybe I will delete this in the future.
But, please keep status quo.

see :
- https://www.infoq.com/news/2009/06/oracleclient_deprecated
- https://www.infoq.com/jp/news/2009/06/oracleclient_deprecated

**Comment by supragyan** [comment]
@daisukenishino 

While performing merging activity from 2012 to 2013 we came across below observations:

### DamSqlDBWithMultiShard
 - We found [DamSqlDBWithMultiShard.sln](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlDbWithMultiShard/DamSqlDbWithMultiShard.sln) has created inside [DamSqlDBWithMultiShard project](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlDbWithMultiShard) 
 - MSBuild Nuget correspondence has implemented separate for DamSqlDbWithMultiShard project.

To maintain consistency with other [Dam project](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Public/Db) do we need to move DamSqlDBWithMultiShard.sln from [DamSqlDbWithMultiShard](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlDbWithMultiShard) to [AllDam.sln](https://github.com/OpenTouryoProject/OpenTouryoTemplates/blob/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Public/Db/AllDam.sln) and also remove Nuget coresponence from [here](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2012/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlDbWithMultiShard)

Please confirm.
