### ISSUE TITLE
Problem has been reported that Loading-dialogbox does not appear when submit on Firefox.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#134]
# Requirement
Problem has been reported that Loading-dialogbox does not appear when submit on Firefox.
Please confirm that the Loading-dialogbox will be displayed with the latest version of Firefox.

Because this is support for the develop project of user, please corresponding quickly.

For this reason, Please confirm by using.

- [/ProjectX_sample/Aspx/testFxLayerP/normal/testScreen1.aspx.btnButton23](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/normal/testScreen1.aspx.cs#L966).

If the dialog does not appear, please increase the interval of sleep.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

>Because this is support for the develop project of user, 

Please carry out this investigation as soon as possible.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

Currently, I am working on the issue '(1) The function to prevent session timeout.'.

Shall I stop working on the above and start working on https://github.com/OpenTouryoProject/OpenTouryo/issues/134#issuecomment-167486873

Please let us know.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Yes, please stop.
Task #134 is priority than the task #129.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

We will stop #129 and start #134

Thank you

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>Please confirm that the Loading-dialogbox will be displayed with the latest version of Firefox.

Yes, We confirmed.

In Firefox latest version 36.0,  Loading-dialogbox is displaying. But immediately the dialogue box is closing.

**Comment by kishoreandukuri** [comment]
@daisukenishino 

We have taken evidence.
Please check

![firefoxprogressdialogue](https://cloud.githubusercontent.com/assets/7530499/12015024/359da9f6-ad5c-11e5-8950-9cd17707c8fa.png)

**Comment by daisukenishino2** [comment]
@kishoreandukuri 

>But immediately the dialogue box is closing.

Dialog will be displayed after a lapse of a [specified time](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L402) after the post.
When the request of the postback is responded,
Since the HTML is changed, dialog disappears.

if so, I think that there is no problem.
I get the information of the isolate the cause from the project.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>if so, I think that there is no problem.

Yes, There is no problem
 
>I get the information of the isolate the cause from the project.
Please share the information with us so that we will fix the issue if any.

Thanks and Regards

**Comment by daisukenishino** [comment]
@kishoreandukuri 

As a result of the confirmation to the developer,
this is caused that the code was forgotten to revert from debug during development.

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Please tell me about how to use the following site.
https://cloud.githubusercontent.com/assets
I think that this site is useful.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Sure, We will check and let you know

Thank you

**Comment by kishoreandukuri** [comment]
@daisukenishino 

>Please tell me about how to use the following site.
>https://cloud.githubusercontent.com/assets

This site is used for uploading files like pdf, xls, docx etc. in the GitHub issues comments.

For uploading these files, we have to drag and drop the file into the Github comment text box.
Then Github automatically upload these files in the url  'https://cloud.githubusercontent.com/assets/7530499/12015024/359da9f6-ad5c-11e5-8950-9cd17707c8fa.png'

For example,  please check the comment https://github.com/OpenTouryoProject/OpenTouryo/issues/134#issuecomment-167494940

We have copied the screen shot using the above approach.

Please read the url for more information
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests
http://blog.davidebbo.com/2014/11/using-issues-for-github-pages-screenshots.html

**Comment by daisukenishino** [comment]
@kishoreandukuri 

![default](https://cloud.githubusercontent.com/assets/5975160/12167260/7a1185b6-b56e-11e5-9028-dac601f4c1a2.png)

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Yes, We can use image and other files also in comments.

Thank you
