### ISSUE TITLE
HttpUtility.UrlEncodeUnicode() method is now obsolete.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#136]
# Current status
HttpUtility.UrlEncodeUnicode() method is now obsolete.
- https://msdn.microsoft.com/en-us/library/system.web.httputility.urlencodeunicode.aspx  
Note: This API is now obsolete.
- https://msdn.microsoft.com/ja-jp/library/system.web.httputility.urlencodeunicode.aspx  
メモ: この API は現在使用できません。

## Investigation result
- URLエンコード、URLデコードを行う: .NET Tips: C#, VB.NET  
http://dobon.net/vb/dotnet/internet/urlencode.html
- Don't use .NET System.Uri.UnescapeDataString in URL Decoding  
ASP.NET 2.0 and IIS 6.0 - Site Home - MSDN Blogs  
http://blogs.msdn.com/b/yangxind/archive/2006/11/09/don-t-use-net-system-uri-unescapedatastring-in-url-decoding.aspx
- URLのエンコードとデコードに関するメソッド。  
http://blogs.wankuma.com/iijimas/archive/2008/08/25/154163.aspx
- [HttpUtility.UrlEncodeUnicode()](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Str/CustomEncode.cs#L1049) method.
  - https://msdn.microsoft.com/ja-jp/library/system.web.httputility.urlencodeunicode.aspx
  - https://msdn.microsoft.com/ja-jp/library/system.web.httputility.urldecode.aspx

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Please modified as follows.

https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Str/CustomEncode.cs#L1049

```C#
#pragma warning disable

/// <summary>Urlエンコードする。</summary>
/// <param name="input">Url</param>
/// <returns>UrlエンコードされたUrl</returns>
/// <remarks>
/// URLエンコードとは
/// http://ja.wikipedia.org/wiki/URLエンコード
/// 
/// 用途は、クエリ文字列の
/// ・変数名
/// ・変数値
/// などに限定する。
/// （デコードはASP.NETでは自動になるため、不要である。）
/// </remarks>
public static string UrlEncode(string input)
{
    return HttpUtility.UrlEncodeUnicode(input);
}

/// <summary>Urlデコードする。</summary>
/// <param name="input">UrlエンコードされたUrl</param>
/// <returns>UrlデコードされたUrl</returns>
public static string UrlDecode(string input)
{
    return HttpUtility.UrlEncodeUnicode(input);
}

#pragma warning restore
```
↓ ↓ ↓
```C#
/// <summary>Urlエンコードする。</summary>
/// <param name="input">Url</param>
/// <returns>UrlエンコードされたUrl</returns>
/// <remarks>
/// URLエンコードとは
/// http://ja.wikipedia.org/wiki/URLエンコード
/// 
/// 用途は、クエリ文字列の
/// ・変数名
/// ・変数値
/// などに限定する。
/// （デコードはASP.NETでは自動になるため、不要である。）
/// </remarks>
public static string UrlEncode(string input)
{
    return HttpUtility.UrlEncodeUnicode(input);
}

/// <summary>Urlデコードする。</summary>
/// <param name="input">UrlエンコードされたUrl</param>
/// <returns>UrlデコードされたUrl</returns>
public static string UrlDecode(string input)
{
    return HttpUtility.UrlDecode(input); // changed.
}
```

**Comment by daisukenishino** [comment]
@kishoreandukuri 

There was a problem in the above [UrlDecode method](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Str/CustomEncode.cs#L1072).
Tell me why that can not be detected in the [test code of the current](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Tests/Public.Test/Str/StringConverterTest.cs).

**Comment by kishoreandukuri** [comment]
@daisukenishino
>Tell me why that can not be detected in the test code of the current.

In the test code we have given input as string 'google.com'.
Because of this problem not detected.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
I noticed the presence of the mistake.
```CS
public static string UrlDecode(string input)
{
    return HttpUtility.UrlDecode(input); // This has been modified because there was a bug.
}
```
↓ ↓ ↓
```CS
public static string UrlDecode(string input)
{
    return HttpUtility.UnescapeDataString(input); // This has been modified because there was a bug.
}
```

**Comment by daisukenishino** [comment]
>https://github.com/OpenTouryoProject/OpenTouryo/issues/136#issuecomment-176711007
In the test code we have given input as string 'google.com'.
Because of this problem not detected.

I can not understand this becasue description is not enough.

@yusukemaegawa 
Can you understand this reason ?

@kishoreandukuri 
Please explain using the [test code](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Tests/Public.Test/Str/CustomEncodeTest.cs#L315).

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We have used the following wrong test cases
```javascript
public IEnumerable<TestCaseData> TestUrlEncodeTest
        {
            get
            {
                yield return new TestCaseData("hello").SetName("TestID-000N");
                yield return new TestCaseData("google.com").SetName("TestID-001N");
            }
        }
````
Above test code didn't detect the problem

**Comment by daisukenishino** [comment]
@kishoreandukuri 

I am wondering why these test cases are wrong.
I think that this reason maybe "assertion" is not implemented. Is this correct ?

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Assertion is implemented. But the test case to test the encoding is not implemented.
The test case should include url with encoding character
eg.
https://www.google.co.in/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8

**Comment by daisukenishino** [comment]
@kishoreandukuri 

I see.
In the future, we will add this issue to the "[issue](https://github.com/OpenTouryoProject/OpenTouryo/issues)".

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Please add the issue, we will correspond it

**Comment by daisukenishino** [comment]
@kishoreandukuri 
I have registered the [new issue](https://github.com/OpenTouryoProject/OpenTouryo/issues/152).

**Comment by daisukenishino** [comment]
@kishoreandukuri 
I noticed the presence of the mistake.
```CS
public static string UrlDecode(string input)
{
    return HttpUtility.UrlDecode(input); // This has been modified because there was a bug.
}
```
↓ ↓ ↓
```CS
public static string UrlDecode(string input)
{
    return HttpUtility.UnescapeDataString(input); // This has been modified because there was a bug.
}
```

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>I request to send pull request that has been modified.
We will send the pull request after completing sprint planning

**Comment by kishoreandukuri** [comment]
@daisukenishino 

return HttpUtility.UnescapeDataString(input);
↓ ↓ ↓
 return Uri.UnescapeDataString(input);

Please confirm.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
In MSDN, it is advicing not to use the method 'UnescapeDataString'

Please check the below url
http://www.ms.com/default.aspx?Products=Windows%26Office&Price=%24200&Comment=In%20Stock&sign=%2b

**Comment by daisukenishino** [comment]
@kishoreandukuri 

URLエンコード、URLデコードを行う: .NET Tips: C#, VB.NET~
http://dobon.net/vb/dotnet/internet/urlencode.html
- URLエンコードのまとめ
  - .NET Framework 4.5以降  
RFC3986に基づいたURLエンコードを行う時は、Uri.EscapeDataStringメソッドを使います。RFC3986に基づいたURLエンコードで、予約文字をエンコードしない時は、Uri.EscapeUriStringメソッドを使います。
  - .NET Framework 2.0～4.0  
RFC2396に基づいたURLエンコードを行う時は、Uri.EscapeDataStringメソッドを使います。RFC2396に基づいたURLエンコードで、予約文字をエンコードしない時は、Uri.EscapeUriStringメソッドを使います。
  - .NET Framework 1.1以前  
HttpUtility.UrlEncodeメソッドを使ってURLエンコードができます。
Uri.EscapeUriStringとUri.EscapeDataStringメソッドは、半角スペースを「%20」にエンコードします。HttpUtility.UrlEncodeメソッドは、半角スペースを「+」にエンコードします。

- URLデコードのまとめ
  - URLデコードを行うには、HttpUtility.UrlDecodeメソッドを使います。
  - Uri.UnescapeDataStringメソッドは「+」を半角スペースに変換しないため、URLデコードに使用すべきではありません。どうしても使用する場合は、デコードする文字列の「+」を半角スペース（あるいは、「%20」）に変換してから使用します。

**Comment by daisukenishino** [comment]
@kishoreandukuri 
- Summary of URL-encoded
  - .NET Framework 4.5 or later
     - HttpUtility.UrlEncodeUnicode() method is obsolete.
     - Perform the URL encoding based on the RFC3986.
     - When performing URL-encode based on RFC3986, use the Uri.EscapeDataString method.
     - When do not encode reserved characters, use the Uri.EscapeUriString method.
  - .NET Framework 2.0 - 4.0
     - You can URL-encode using HttpUtility.UrlEncode method.
     - Perform the URL encoding based on the RFC2396.
     - When performing URL-encode based on RFC2396, use the Uri.EscapeDataString method.
     - When do not encode reserved characters, use the Uri.EscapeUriString method.
  - .NET Framework 1.1  or earlier
     - You can URL-encode using HttpUtility.UrlEncode method.
     - Uri.EscapeUriString and Uri.EscapeDataString method encodes a space to the "%20".
     - HttpUtility.UrlEncode method encodes a space to the "+".
- Summary of URL-decode
  - To do URL decode, use the HttpUtility.UrlDecode method.
  - Uri.UnescapeDataString method does not convert the "+" to a space, this should not be used in the URL-decode.

The following is correct.
https://github.com/OpenTouryoProject/OpenTouryo/issues/136#issuecomment-167224215

The following was a incorrect.
https://github.com/OpenTouryoProject/OpenTouryo/issues/136#issuecomment-178955122

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>The following is correct.
>#136 (comment)

We will keep the following code
```Javascript
public static string UrlDecode(string input)
{
    return HttpUtility.UrlDecode(input); // This has been modified because there was a bug.
}
```
Please confirm.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
As per the [above](https://github.com/OpenTouryoProject/OpenTouryo/issues/136#issuecomment-179176312) comments, we have reverted the changes of [code](https://github.com/OpenTouryoProject/OpenTouryo/issues/136#issuecomment-178955122).

Please merge the pull request
https://github.com/SymphonyTeleca/OpenTouryo/pull/95

**Comment by daisukenishino** [comment]
@kishoreandukuri 

[This pullrequest](https://github.com/SymphonyTeleca/OpenTouryo/pull/95) will be merged after the [previous pullrequest](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/30) have been merged.
