### ISSUE TITLE
The captions of DaoGen_Tool are unhelpful.

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#139]
The captions of DaoGen_Tool are unhelpful.
Please improve the captions to become clear.

In [Form2.ja-JP.resx](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.ja-JP.resx), there are the following definitions.

```xml
  <data name="cbxOnlyTableMaintenance.Text" xml:space="preserve">
    <value>テーブルメンテナンスのみ1</value>
  </data>
  <data name="cbxTableMaintenance.Text" xml:space="preserve">
    <value>テーブルメンテナンス（*.aspx、*.aspx.cs、TableAdapter.cs）</value>
  </data>
  (snip)
  <data name="gbxDTO.Text" xml:space="preserve">
    <value>項目移送用の型を生成する（エンコーディングはDaoと同じになる</value>
  </data>
```

- How are "テーブルメンテナンスのみ1" and "テーブルメンテナンス（*.aspx、*.aspx.cs、TableAdapter.cs）" different?

- What is the meaning of "項目移送用の型"?
I think that "DTO" is better.
(I think that "DTO" is a more general term.)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

#### Meaning of the caption

##### "テーブルメンテナンスのみ1" at cbxOnlyTableMaintenance
Dao will be also generated in addition to the "*.aspx, *.aspx.cs, *TableAdapter.cs"

##### "テーブルメンテナンス（.aspx、.aspx.cs、TableAdapter.cs）" at cbxTableMaintenance 
- Dao will not be generated.
- Only the "*.aspx, *.aspx.cs, *TableAdapter.cs" will be generated.

#### Type for item transportation
>I think that "DTO" is a more general term.

I also think so.
I plan to change this to "DTO".

**Comment by daisukenishino** [comment]
# Contents of changes

#### cbxOnlyTableMaintenance.Text  
###### [Form2.resx](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.resx#L997)
```XML
<value>Only table maintenance</value>
```
↓ ↓ ↓
```XML
<value>Only table maintenance (Only screen will be generated, Dao and SQL and DTO will not be generated.)</value>
```
###### [Form2.ja-JP.resx](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.ja-JP.resx#L146)
```XML
<value>テーブルメンテナンスのみ1</value>
```
↓ ↓ ↓
```XML
<value>テーブルメンテナンスのみ (画面のみ生成され, Dao、SQL、DTOは生成されません。)</value>
```

#### cbxTableMaintenance.Text
###### [Form2.resx](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.resx#L424)
```XML
<value>Table Maintenance (*. Aspx, *. Aspx.cs, TableAdapter.cs)</value>
```
↓ ↓ ↓
```XML
<value>Table Maintenance (Generate screens.)</value>
```
###### [Form2.ja-JP.resx](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.ja-JP.resx#L149)
```XML
<value>テーブルメンテナンス（*.aspx、*.aspx.cs、TableAdapter.cs）</value>
```
↓ ↓ ↓
```XML
<value>テーブルメンテナンス (画面を生成します。)</value>
```

**Comment by yusukemaegawa** [comment]
@daisukenishino 

How are "テーブルメンテナンスのみ (画面のみ生成され, Dao、SQL、DTOは生成されません。)" and "テーブルメンテナンス (画面を生成します。)" different?

# suggestion
```xml
<value>テーブルメンテナンスのみ1</value>
```
↓↓↓
```xml
<value>テーブルメンテナンス画面のみ生成します。（Dao, SQL, DTOは生成しません）</value>
```

```xml
<value>テーブルメンテナンス（*.aspx、*.aspx.cs、TableAdapter.cs）</value>
```
↓↓↓
```xml
<value>テーブルメンテナンス画面, Dao, SQL, DTOを生成します。</value>
```

**Comment by daisukenishino** [comment]
@yusukemaegawa 
Thank you for your [suggestion](https://github.com/OpenTouryoProject/OpenTouryo/issues/139#issuecomment-172401014).
It has been changed to the correct message by checking of [source code](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.cs)


Please check the https://github.com/OpenTouryoProject/OpenTouryo/issues/139#issuecomment-171937652.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Do we need to work on this task?
Please let us know

**Comment by daisukenishino** [comment]
@kishoreandukuri 
>Do we need to work on this task?

Yes, you do.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Thank you for the confirmation

**Comment by daisukenishino** [comment]
@kishoreandukuri 
We added the contents of the changes to gbxDTO.Text.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We will check and do the changes

**Comment by daisukenishino** [comment]
@kishoreandukuri 

It is difficult to check the [differences](https://github.com/SymphonyTeleca/OpenTouryo/pull/94/files) of this pullrequest, therefor, I can't accept this pullrequest.

In case of you use the Visual Studio as editor, I think that there is a possibility that the order of items in the *.resx file that is automatically generated will be changed significantly. Therefor, please modify original file using a text editor in accordance with the contents of #139 with pinpoint.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>It is difficult to check the differences of this pullrequest, therefor, I can't accept this pullrequest.

After changing captions, the captions becoming big on the screen. we need to change the position of the controls to fit the captions on the screen.
![image](https://cloud.githubusercontent.com/assets/7530499/12749268/7d026b2a-c9d5-11e5-8362-0454a596795c.png)

We have made these changes. because of this differences are showing as more.

**Comment by daisukenishino** [comment]
@kishoreandukuri 
I see. It is unavoidable.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
Thank you for the support
