### ISSUE TITLE
To support data providers of "Elastic Database of Azure SQL Database".

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#144]
# Requirement
To support data providers of **"Elastic Database of Azure SQL Database"**.

### Support
Implement DamSqlDbWithMultiShard.cs to corresponding to data providers of **"Elastic Database of Azure SQL Database"**.
- Because DamSqlDbWithMultiShard.cs require another data provider  **"Azure.SqlDatabase.ElasticScale.Client.dll"**.
- Therefor, [DamSqlDbWithMultiShard](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlDbWithMultiShard) should be created as separate project.

### Research
Research the data providers of **"Elastic Database of Azure SQL Database"**.

##### About feature
My research result is here.
- Elastic Scale, Elastic Database Pool - マイクロソフト系技術情報 Wiki  
http://techinfoofmicrosofttech.osscons.jp/index.php?Elastic%20Scale%2C%20Elastic%20Database%20Pool

##### About difference of API and implementation
I want to know the API and implementation difference between using normal **"System.Data.SqlClient"** and using **"Azure Elastic client library"** for **"Data Dependent Routing"** and **"Multi-Shard Queries"** functions.
- These are using following classes in **Microsoft.Azure.SqlDatabase.ElasticScale.Query** name space.
  - [MultiShardConnection](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.query.multishardconnection.aspx) should be compared with [SqlConnection](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.aspx)
  - [MultiShardCommand](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.query.multishardcommand.aspx) should be compared with [SqlCommand](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.aspx)
  - [MultiShardDataReader](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.query.multisharddatareader.aspx) should be compared with [SqlDataReader](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqldatareader.aspx)
- List the non-standard function of ADO.NET data provider for Azure Elastic client library.
  - Added Features, e.g. : 
    - Array bind function
    - FetchSize property
  - Unsupported Features
- Consider whether it is possible to develop [Dam](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Db/) by researching the functionality and interfaces that is required support.

### Target framework
Change the target directory depending on the .net version that is supported by the **"Azure.SqlDatabase.ElasticScale.Client.dll"**. Therefor, please investigate the version of .NET to support the **"Azure.SqlDatabase.ElasticScale.Client.dll"**.
- root_VS2010 ( .NET3.5 )
- root_VS2012 ( .NET4.5 )
- root_VS2013 ( .NET4.5.1 )
- root_VS2015 ( .NET4.6 ),etc.

**Comment by daisukenishino** [comment]
# The sample as research results.
Please provide a sample because the research results is not enough.

https://github.com/OpenTouryoProject/SampleProgram/tree/master/Azure/ElasticDatabase

**Comment by daisukenishino** [comment]
@supragyan 

The information that I need is whether it is possible to wrap the DML execution function of the Elastic Database Client Library by the DamSqlDED like [DamSqlSvr](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlSvr.cs).

I confirmed the sample that provided by you.
url : xxx
```C#
 // Open and execute the command with retry for transient faults. Note that if the command fails, the connection is closed, so
 // the entire block is wrapped in a retry. This means that only one command should be executed per block, since if we had multiple
 // commands then the first command may be executed multiple times if later commands fail.
 SqlDatabaseUtils.SqlRetryPolicy.ExecuteAction(() =>
 {
     // Looks up the key in the shard map and opens a connection to the shard
     using (SqlConnection conn = shardMap.OpenConnectionForKey(customerId, credentialsConnectionString))
     {
         // Create a simple command that will insert or update the customer information
         SqlCommand cmd = conn.CreateCommand();
         cmd.CommandText = @"
         IF EXISTS (SELECT 1 FROM Customers WHERE CustomerId = @customerId)
             UPDATE Customers
                 SET Name = @name, RegionId = @regionId
                 WHERE CustomerId = @customerId
         ELSE
             INSERT INTO Customers (CustomerId, Name, RegionId)
             VALUES (@customerId, @name, @regionId)";
         cmd.Parameters.AddWithValue("@customerId", customerId);
         cmd.Parameters.AddWithValue("@name", name);
         cmd.Parameters.AddWithValue("@regionId", regionId);
         cmd.CommandTimeout = 60;

         // Execute the command
         cmd.ExecuteNonQuery();
     }
 });
```
I thought that base class of B layer maybe necessary.
Because this is similar as the design of the layer B corresponding to the "System.Transactions.TransactionScope" that it is designed in the past.

**Comment by daisukenishino** [comment]
# My research result
## Transaction
- Azure SQL Database を使用したエラスティック データベース トランザクションの概要 (プレビュー)  
https://azure.microsoft.com/ja-jp/documentation/articles/sql-database-elastic-transactions-overview/

## Retry policy

## Relationship of "transaction" and "retry policy".

**Comment by daisukenishino** [comment]
# My research result 2

### Transaction (Elastic database transactions)
- Azure SQL Database を使用したエラスティック データベース トランザクションの概要 (プレビュー)  
https://azure.microsoft.com/ja-jp/documentation/articles/sql-database-elastic-transactions-overview/
- Overview of Elastic Database Transactions with Azure SQL Database
https://azure.microsoft.com/en-us/documentation/articles/sql-database-elastic-transactions-overview/

#### Overview
- Elastic database transactions allow execute transactionnal process that span several databases in SQL DB.
- Elastic database transactions for SQL DB are available for .NET applications using ADO .NET and integrate with the familiar programming experience using the **System.Transaction** classes.
- To start developing applications using elastic database transactions, install **.NET Framework 4.6.1 or a later version**.
- **MS-DTC** is not available for PaaS application in Azure, the ability to coordinate distributed transactions has been directly integrated into SQL DB.
- Elastic database transactions use **"two-phase commit"** to ensure transaction atomicity across databases.
  - It is a good fit for transactions that involve less than 100 databases at a time within a single transaction.
  - These limits are not enforced, but one should expect performance and success rates for elastic database transactions to suffer when exceeding these limits.

#### Scenario
##### Multi-database applications in Azure SQL DB
- The scenario that DB sharding isn't used.  
And, the scenario that it is using the two or more DB instance.
- These scenario is required **"two-phase commit"**.  
Elastic database transactions is execute **"two-phase commit"** directly.

```C#
using (var scope = new TransactionScope())
{
    using (var conn1 = new SqlConnection(connStrDb1))
    {
        conn1.Open();
        SqlCommand cmd1 = conn1.CreateCommand();
        cmd1.CommandText = string.Format("insert into T1 values(1)");
        cmd1.ExecuteNonQuery();
    }

    using (var conn2 = new SqlConnection(connStrDb2))
    {
        conn2.Open();
        var cmd2 = conn2.CreateCommand();
        cmd2.CommandText = string.Format("insert into T2 values(2)");
        cmd2.ExecuteNonQuery();
    }

    scope.Complete();
}
```

##### Sharded database applications in Azure SQL DB
- The scenario that DB sharding is used.
And, the scenario that it is using the two or more DB instance.
  - **Single tenancy patterns**  
Process with more than two tenant at **single tenancy patterns**.
  - **Multi tenancy patterns**  
Process with one tenant that span several databases at **multi tenancy patterns**.
- These scenario is required **"two-phase commit"**.  
Elastic database transactions is execute **"two-phase commit"** directly.

```C#
using (var scope = new TransactionScope())
{
    using (var conn1 = shardmap.OpenConnectionForKey(tenantId1, credentialsStr))
    {
        conn1.Open();
        SqlCommand cmd1 = conn1.CreateCommand();
        cmd1.CommandText = string.Format("insert into T1 values(1)");
        cmd1.ExecuteNonQuery();
    }

    using (var conn2 = shardmap.OpenConnectionForKey(tenantId2, credentialsStr))
    {
        conn2.Open();
        var cmd2 = conn2.CreateCommand();
        cmd2.CommandText = string.Format("insert into T1 values(2)");
        cmd2.ExecuteNonQuery();
    }

    scope.Complete();
}
```

### Retry policy

### Relationship of "transaction" and "retry policy".

**Comment by daisukenishino** [comment]
# Research result 3
### Difference of API and implementation
API and implementation difference between using normal "sqlClient" and using "Azure Elastic client library" for "Data Dependent Routing" and "Multi-Shard Queries" functions.

The experience with the **multi-shard query** APIs follows these steps:
Create a MultiShardConnection.
Create a MultiShardCommand for a MultiShardConnection.
Execute the command.
Consume the results through the MultiShardDataReader.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I can not associate DamSqlDED with "Azure SQL Database Elastic Pool" or "Azure SQL Database Elastic Scale".
Please name new Data Access Manager more understandable name.

e.g.
DamSqlDbElasticScale
DamAzureDbElasticScale
etc.

I think that the above names are long, but are easy to understand.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

How about this? 
```C#
class DamSQLElasticScale
```

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>How about this? 
>```C#
>class DamSQLElasticScale
>```

Personally speaking, "DamSql**Db**ElasticScale" is better...
(Because the name of dll to use is "Azure.Sql**Database**.ElasticScale.Client.dll"...)

And, you should use pascal casing. (See [this article](https://msdn.microsoft.com/en-us/library/ms229043.aspx).)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Dam that will be developed this time was decided in today's meeting that it will be limited to the ability to execute the "Multi-Shard Queries" . Therefor, This new Dam does not have the ability to run the "Data Dependent Routing". Because, [it is possible to support Dependent Routing" by modify only a little the DamSqlSvr](https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-191762321).

So I am trying to naming as follows.
```C#
class DamSqlDb4MultiShard
```
How about this?

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I see.
But, I feel something strange about "DamSqlDb**4**MultiShard".
I think that the new dam means "Data Access Manager for Azure SQL Database **using** Multi Shard Query". (not **for** Multi Shard Query.)

So, How about the following name?
```C#
class DamSqlDbWithMultiShard
```

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I renamed DamSqlDED to DamSqlDbWithMultiShard.
```C#
class DamSqlDbWithMultiShard
```

**Comment by yusukemaegawa** [comment]
@daisukenishino 

OK, I understood it.

**Comment by daisukenishino** [comment]
@supragyan 

After [the research](https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-191762321), I had scheduled to ask the sample program development.
In this sample program, replaced by the Dam the process of [Microsoft's sample program](https://github.com/OpenTouryoProject/SampleProgram/tree/master/Azure/ElasticDatabase/ElasticDB_Sample).

##### "Data Dependent Routing"
Processing of "Data Dependent Routing" will be replaced by DamSqlSvr.

##### "Multi-Shard Queries"
Processing of "Multi-Shard Queries" will be replaced by DamSqlDbWithMultiShard.

##### "Elastic database transactions" and "Retry policy"
This time, we will conduct only investigation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-197257333
> After the research, I had scheduled to ask you the sample program development.
> In this sample program, replaced by the Dam the process of the Microsoft's sample program.

Create Dam project or class that suites the [Microsoft's sample program](https://github.com/OpenTouryoProject/SampleProgram/tree/master/Azure/ElasticDatabase/ElasticDB_Sample).

> Processing of "Data Dependent Routing" will be replaced by DamSqlSvr.

Do we need to create separate Dam project for Data Dependent Routing process?
or 
Shall we modify the existing DamSqlSvr to match the Data Dependent Routing process?

There after, using this Dam project create sample program for Data Dependent Routing process.

> Processing of "Multi-Shard Queries" will be replaced by DamSqlDbWithMultiShard.

- Create new DamSqlDbWithMultiShard project for Multi-Shard Queries.
- There after, using this Dam project create sample program for Multi-Shard Queries.

> This time, we will carry out only investigation.

Perform the investigation on "Elastic database transactions" and "Retry policy" for both Data Dependent Routing process and Multi-Shard Queries.

Please confirm our understanding as mentioned above.
And please let us know if any additional tasks to be carried out along with this.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Do we need to create separate Dam project for Data Dependent Routing process?
or 
Shall we modify the existing DamSqlSvr to match the Data Dependent Routing process?

Yes, it will be only to modify the DamSqlSvr for correspond to the "Data Dependent Routing".

>- Create new DamSqlDbWithMultiShard project for Multi-Shard Queries.
- There after, using this Dam project create sample program for Multi-Shard Queries.

Yes, DamSqlDbWithMultiShard will be developed for Multi-Shard Queries

After performed above, replaced the process of the Microsoft's sample program by the Dams (fixed DamSqlSvr and new DamSqlDbWithMultiShard).

>Perform the investigation on "Elastic database transactions" and "Retry policy" for both Data Dependent Routing process and Multi-Shard Queries.

Yes, it is OK in the only investigation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation.
We will plan accordingly.

**Comment by supragyan** [comment]
@daisukenishino 
\> I want you to investigate correspondence with DataAdapter and TableAdapter in MultiShardCommand.
\>I think that it can't be supported possibly.

We did research on DataAdapter in MultiShardCommand class but we did not find any DataAdapter API like [MultiShardConnection](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.query.multishardconnection.aspx),[MultiShardCommand](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.query.multishardcommand.aspx),[MultiShardDataReader](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.query.multisharddatareader.aspx).
That means MultiShardQuery not supported DataAdapter API.

We think probably MultiShardDataReader API can be used as alternative of MultiShardDataAdapter.

Please confirm our understanding.

**Comment by supragyan** [comment]
@daisukenishino 

We did research on Transaction but all important points are already updated  [here](https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-191718562),

Other than this do we need to research on any specific transaction related topics(enumerators,properties etc.)

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

>Other than this do we need to research on any specific transaction related topics(like enumerators,properties etc.)

Not required.
I want you to embark on the development of the **"DamSqlDbWithMultiShard"** as the next task.

**Comment by supragyan** [comment]
@daisukenishino 

Thank you for confirmation.

\>I want you to embark on the development of the "DamSqlDbWithMultiShard" as the next task.
OK,we will start the development of the "DamSqlDbWithMultiShard".

**Comment by supragyan** [comment]
@daisukenishino 

Please put this code in [Relationship of "transaction" and "retry policy".](
https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-191718562)

             private static void AddCustomerAndOrder(
             ShardMap shardMap,
             string credentialsConnectionString,
             int customerId,
                string name,
                int regionId,
           int productId
            )
        {
            // Open and execute the command with retry for transient faults. Note that if the command fails, the connection is closed, so
            // the entire block is wrapped in a retry. This means that only one command should be executed per block, since if we had multiple
            // commands then the first command may be executed multiple times if later commands fail.           
            int MaxRetries = 10;
            int DelayMS = 100;
            RetryPolicy policy = new RetryPolicy<SqlAzureTransientErrorDetectionStrategy>(MaxRetries,
                                                 TimeSpan.FromMilliseconds(DelayMS));
            policy.ExecuteAction(() =>
          {
              TransactionOptions tso = new TransactionOptions();
              tso.IsolationLevel = IsolationLevel.ReadCommitted;

              using (TransactionScope ts = new TransactionScope(TransactionScopeOption.Required, tso))
              {
                  // Looks up the key in the shard map and opens a connection to the shard
                  using (SqlConnection conn = shardMap.OpenConnectionForKey(@customerId, credentialsConnectionString))
                  {
                      // Create a simple command that will insert or update the customer information
                      SqlCommand cmd = conn.CreateCommand();
                      cmd.CommandText = @"
                    IF EXISTS (SELECT 1 FROM Customers WHERE CustomerId = @customerId)
                        UPDATE Customers  SET Name = @name, RegionId = @regionId
                                WHERE CustomerId = @customerId                        
                            
                    ELSE
                        INSERT INTO Customers (CustomerId, Name, RegionId)
                              VALUES (@customerId, @name, @regionId)";
                      cmd.Parameters.AddWithValue("@customerId", customerId);
                      cmd.Parameters.AddWithValue("@name", "abc");
                      cmd.Parameters.AddWithValue("@regionId", regionId);
                      cmd.CommandTimeout = 60;

                      // Execute the command
                      cmd.ExecuteNonQuery();
                  }

                  using (SqlConnection conn = shardMap.OpenConnectionForKey(@customerId, credentialsConnectionString))
                  {
                      // Create a simple command that will insert a new order
                      SqlCommand cmd = conn.CreateCommand();

                      // Create a simple command
                      cmd.CommandText = @"INSERT INTO dbo.Orders (CustomerId, OrderDate, ProductId)
                                        VALUES (@customerId, @orderDate, @productId)";
                      cmd.Parameters.AddWithValue("@customerId", customerId);
                      cmd.Parameters.AddWithValue("@orderDate", DateTime.Now.Date);
                      cmd.Parameters.AddWithValue("@productId", productId);
                      cmd.CommandTimeout = 60;

                      // Execute the command
                      cmd.ExecuteNonQuery();
                  }
                  ts.Complete();
              }
          });
        }

**Comment by daisukenishino** [comment]
@supragyan 

Thank you. [It](https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-206129366) has merged [here](https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-191718562).

**Comment by supragyan** [comment]
@daisukenishino 

We are implementing new project DamSqlDbWithMultiShard using MultiShardQuery APIs.
Below methods are not supported in MultiShardQuery API.
- ExecuteScalar
- ExecuteNonQuery
- DataAdapter
- Transaction

So implementation code for the above will not be available in DamSqlDBWithMultiShard project.

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

### For the methods for data access
It will be corresponding using **"NotImplementedException"**.

- ExecuteScalar
- ExecuteNonQuery
- DataAdapter

#### About the transaction
There is possibility that it is good specification that the calling of the method to be **"swing and miss"**. This is because, it sharing the code in [UOC_ConnectionOpen()](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Business/MyFcBaseLogic.cs#L140) and [DoBusinessLogic()](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Business/BaseLogic.cs#L180).

This implementation does not convey clearly that the Dam does not support the transaction to the user. But, **"swing and miss"** is needed as commonization to operate it in an existing frame.

- Transaction

**Comment by supragyan** [comment]
@daisukenishino 

Thank you for confirmation.
Ok. We understood.

\>>It will be corresponding using "NotImplementedException".
- ExecSelectScalar

So we implemented as following:
 
    public override object ExecSelectScalar()
        {
            throw new NotImplementedException(PublicExceptionMessage.NOT_IMPLEMENTED);
        }   
We implemented same as above for ExecuteNonQuery and DataAdapter.

\>This implementation does not convey clearly that the Dam does not support the transaction to the user. But, "swing and miss" is needed as commonization to operate it in an existing frame.
- Transaction

So we have implemented as following:

                public override void BeginTransaction(DbEnum.IsolationLevelEnum iso)
        {
            // 分離レベル設定のチェック
            if (iso == DbEnum.IsolationLevelEnum.NoTransaction)
            {
                // トランザクションを開始しない（nullのまま）。
            }
            else if (iso == DbEnum.IsolationLevelEnum.DefaultTransaction)
            {
                // 規定の分離レベルでトランザクションを開始する。
                // this._tx = this._cnn.BeginTransaction();  
                LogIF.InfoLog("DamSql-Multishard", "Transaction not supported");
            }
            else if (iso == DbEnum.IsolationLevelEnum.ReadUncommitted)
            {
                // 非コミット読み取りの分離レベルでトランザクションを開始する。
                // this._tx = this._cnn.BeginTransaction(IsolationLevel.ReadUncommitted);
                LogIF.InfoLog("DamSql-Multishard", "Transaction not supported");
            }
            else if (iso == DbEnum.IsolationLevelEnum.ReadCommitted)
            {
                // コミット済み読み取りの分離レベルでトランザクションを開始する。
                // this._tx = this._cnn.BeginTransaction(IsolationLevel.ReadCommitted);
                LogIF.InfoLog("DamSql-Multishard", "Transaction not supported");
            }
            else if (iso == DbEnum.IsolationLevelEnum.RepeatableRead)
            {
                // 反復可能読み取りの分離レベルでトランザクションを開始する。
                //  this._tx = this._cnn.BeginTransaction(IsolationLevel.RepeatableRead);
                LogIF.InfoLog("DamSql-Multishard", "Transaction not supported");
            }
            else if (iso == DbEnum.IsolationLevelEnum.Serializable)
            {
                // 直列化可能の分離レベルでトランザクションを開始する。
                //  this._tx = this._cnn.BeginTransaction(IsolationLevel.Serializable);
                LogIF.InfoLog("DamSql-Multishard", "Transaction not supported");
            }
            else if (iso == DbEnum.IsolationLevelEnum.Snapshot)
            {
                // スナップショット分離レベルでトランザクションを開始する。
                // this._tx = this._cnn.BeginTransaction(IsolationLevel.Snapshot);
                LogIF.InfoLog("DamSql-Multishard", "Transaction not supported");
            }
            else if (iso == DbEnum.IsolationLevelEnum.User)
            {
                // 無効な分離レベル（ユーザ指定）。
                throw new ArgumentException(
                    PublicExceptionMessage.DB_ISO_LEVEL_PARAM_ERROR_USR);
            }
            else if (iso == DbEnum.IsolationLevelEnum.NotConnect)
            {
                // 2009/03/29 -- 追加したNotConnectの対応（このコードブロック）。

                // 無効な分離レベル（NotConnect指定）。
                throw new ArgumentException(
                    PublicExceptionMessage.DB_ISO_LEVEL_PARAM_ERROR_NC);
            }
            else
            {
                // 通らない予定
            }

            // 分離レベル（iso）をメンバ変数に保存
            _iso = iso;
        }

At the moment in the above code we have commented the code related to Transaction method(Begin Transaction).Eventually we will remove it from the code.

Is this ok?
Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

>- ExecSelectScalar

Please do so.

>- Transaction

Good.

However, I think that you should choose the log level that is the lowest so that a filter is possible.
In addition, I think that the logger should use default logger("ACCESS").

```CS
LogIF.InfoLog("DamSql-Multishard", "・・・");
```
▼ ▼ ▼
```CS
LogIF.DebugLog("ACCESS", "・・・");
```

**Comment by supragyan** [comment]
@daisukenishino 
Thank you for confirmation.

\>\>However, I think that you should choose the log level that is the lowest so that a filter is possible.
\>\>In addition, I think that the logger should use default logger("ACCESS").
We will do so.

**Comment by supragyan** [comment]
@daisukenishino  

In DamSqlDBWithMultiShard project,we have implemented following:
- MultiShardConnection
- MultiShardCommand
- MultiShardDataReader
- Transaction

And in Sample application we implemented below methods :
- GetShardMap
- GetShards

So the details about Shards such as ShardMap,ShardName are passed from Sample application to Dam.

Please let us know if there is any change is required.

**Comment by daisukenishino** [comment]
@supragyan 

Not enough.

### Sample program
The sample program is implemented as follows.
- [MultiShardQuerySample.ExecuteMultiShardQuery()](https://github.com/OpenTouryoProject/SampleProgram/blob/master/Azure/ElasticDatabase/ElasticDB_Sample/ElasticScaleStarterKit/MultiShardQuerySample.cs#L27)
- [Program.TryGetShardMap()](https://github.com/OpenTouryoProject/SampleProgram/blob/master/Azure/ElasticDatabase/ElasticDB_Sample/ElasticScaleStarterKit/Program.cs#L349)
- [ShardManagementUtils.TryGetShardMapManager()](https://github.com/OpenTouryoProject/SampleProgram/blob/master/Azure/ElasticDatabase/ElasticDB_Sample/ElasticScaleStarterKit/ShardManagementUtils.cs#L19)

### Correspondence method

### Reference
- [MultiShardConnection Constructor (IEnumerable(Shard), String) (Microsoft.Azure.SqlDatabase.ElasticScale.Query)](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.query.multishardconnection.multishardconnection.aspx)
- [MultiShardConnection.Shards Property (Microsoft.Azure.SqlDatabase.ElasticScale.Query)](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.query.multishardconnection.shards.aspx#P:Microsoft.Azure.SqlDatabase.ElasticScale.Query.MultiShardConnection.Shards)
- [Shard Class (Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement)](https://msdn.microsoft.com/en-us/library/microsoft.azure.sqldatabase.elasticscale.shardmanagement.shard.aspx)

**Comment by supragyan** [comment]
@daisukenishino 

\>\>Explanation is insufficient.
I have provided only the overview of implementation plan.

\>\>MultiShardQuerySample

\>\>The sample program is implemented as follows.

MultiShardQuerySample.ExecuteMultiShardQuery()
Program.TryGetShardMap()
ShardManagementUtils.TryGetShardMapManager()

Yes we already implemented as above only.

\>The business project must not be added reference settings of "Microsoft.Azure.SqlDatabase.ElasticScale.Client.dll" by the default.

Yes we have not added Microsoft.Azure.SqlDatabase.ElasticScale.Client.dll reference in Business project.To achieve Shards in Business project we passing object in Business project.

\>Implement a static utility function to get shard from a ShardMapName in "DamSqlDbWithMultiShard".
We asked this [#144 comment](https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-212912595)  to confirm on ShardMapName
Because we implemented the static function to get shard from a ShardMapName in Sample application.
Now we will move this function to "DamSqlDbWithMultiShard" project.

**Comment by daisukenishino** [comment]
@supragyan 

I am thinking that your work is favorable by referring your comment.

**Comment by supragyan** [comment]
@daisukenishino 

We completed the implementation of  Data Dependent Routing in Dam project.
For that we have created new Data Dependent Routing class in DamSqlDBWithMultiShard project as 
[151 pullrequest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/151) instead of modifying DamSqlSvr class.
Because if we implement in DamSqlSvr class then Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement dll needs to be installed in DamSqlSvr class.
So we implemented Data Dependent Routing functionality in DamSqlDbWithMultiShard project.

Please confirm.

**Comment by daisukenishino** [comment]
@supragyan 

>https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-191762321
- DamSqlSvr.DamSqlConnection  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Db/DamSqlSvr.cs#L108
```C#
/// <summary>SqlConnection（読み取り専用）</summary>
/// <remarks>必要に応じて利用する。</remarks>
public SqlConnection DamSqlConnection
{
    get
    {
        // コネクションを戻す
        return _cnn;
    }
}
```
▼▼▼
```C#
/// <summary>SqlConnection</summary>
/// <remarks>必要に応じて利用する。</remarks>
public SqlConnection DamSqlConnection
{
    get
    {
        // コネクションを戻す
        return _cnn;
    }
   get
    {
        // コネクションを設定
        _cnn = value;
    }
}
```
I think that I can correspond by the already commented method.

**Comment by daisukenishino** [comment]
@supragyan 

Since this modification is great I've created a new [nishino_ED branch](https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino_ED).
I close the once all the pull requests, please resend the pull request to [nishino_ED branch](https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino_ED).

**Comment by daisukenishino** [comment]
@supragyan 

We do not want to create the Dam for DataDependentRouting. This is because, if solving the problem that to get a connection of DataDependentRouting, it is possible to diverted DamSQLSvr in this simple way.

- MyFcBaseLogic
```C#
( (DamSqlSvr) dam ).DamSqlConnection = MultiShardConfiguration.GetDataDependentRoutingConnection(connstring);
```

- DamSqlDbWithMultiShard.csproj
```C#
public class MultiShardConfiguration
{
  public static SqlConnection GetDataDependentRoutingConnection(string connstring)
  {
    return MultiShardConfiguration.TryGetShardMap().OpenConnectionForKey(MultiShardConfiguration.customerId, connstring);
  }
}
```

**Comment by supragyan** [comment]
@daisukenishino 
Yes we understood same in yesterday's call.
Earlier we also thought to implement in MyFcBaseLogic class instead of modify in new DamSQLDBWithMultiShard project.But as per [this comment ](https://github.com/OpenTouryoProject/OpenTouryo/issues/144#issuecomment-214076847),we have not customized in MyFcBaseLogic class.

So after discussion in yesterday's call, we have modified in MyFcBaseLogic, MultiShardConfiguration, DamSqlSvr class.

And also created pull request as [153 pullrequest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/153) which contains DamSqlDbWithMultiShard project with only MultiShard changes.,[154 pullrequest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/154) which contains only MyFCBaseLogic changes to support both MultiShard and DataDependentRouting,[155 pull reuest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/155) which contains DamSqlSvr changes.

From these pull requests,[155 pull reuest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/155) has been merged.
So please review  [153 pullrequest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/153) , [154 pull reuest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/155) and [21 pull request](https://github.com/SymphonyTeleca/SampleProgram/pull/21) .

Let us know.

**Comment by daisukenishino** [comment]
@supragyan 

I see.
These pull requests  will be merged after performing the following.

https://github.com/SymphonyTeleca/SampleProgram/pull/20#issuecomment-214970024

>>But, I have one question.
Is this the sample can be operated by the same procedure as the original sample?

>Yes this the sample can be operated by the same procedure as the original sample.
We have added MultiShardQuery execution with our Dam project in same existing sample because till yet we have not implemented DataDependentRouting for creating Shards.

Please get the evidence by confirm the procedure.
And, please check that there are no problems by review within your team.

**Comment by supragyan** [comment]
@daisukenishino 

\>Please get the evidence by confirm the procedure.
We created evidence and uploaded in IPServer.

Location in the IP server:
[/V-RW/PJ2/Delivery/20160506]
 
File Name:
Evidence_multishard-datadependentrouting.docx

Please review

**Comment by daisukenishino** [comment]
@supragyan 

>https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/154

The review is now complete.
Please check my pointed out.

**Comment by supragyan** [comment]
@daisukenishino 

\>\>Please report the corresponding status of ElasticDB tomorrow.
We have modified [here] as per your all valuable comments.

Please review.

Still if anything missing we will discuss on meeting
