### ISSUE TITLE
Path is too long.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#145]
# Requirement
## Phenomenon

There is no problem when you deploy directly under C drive, but when it is deployed to the following Users directory, then an error occurs that the "path is too long".
- "C:\"
- "C:\Users\XXXXX"

## Trend
Recently, Visual Studio supports Github.
User can clone a repository on Github by Visual Studio.

- Visual Studio 2013の Git を使う① GitHubへPushするまで - Planetleaf.com Lab.  
http://lab.planetleaf.com/git/push-to-github-from-visual-studio-2013.html
- Visual Studio 2013の Git を使う② GitHubからCloneする - Planetleaf.com Lab.  
http://lab.planetleaf.com/git/clone-repos-with-visual-studio-2013-from-github.html

Following default path is used when you clone repository from GitHub.
- "C:\"
- "C:\Users\UserName\Source\Repos\RepositoryName"

Therefor, there is a high possibility that users encounter this problem.

## Modification 
Modify this problem that is caused this error after discover the long path.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We started working on this issue.
Shall we check this issue in VS2010, VS2012 and VS2015 also? 
Please let us know.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
We have done research on this.
Windows OS is having long path restriction, Microsoft has restricted the file path to 260 characters.
Please refer <b>Submodule introduces long paths -> Unable to commit through Team Explorer</b> in the link
https://visualstudiogallery.msdn.microsoft.com/abafc7d6-dcaa-40f4-8a5e-d6724bdb980c/view/Discussions/4 

Please refer the link for solutions
https://support.code42.com/CrashPlan/4/Troubleshooting/Windows_File_Paths_Longer_Than_255_Characters

**Comment by daisukenishino** [comment]
@kishoreandukuri 

The above is a known.

I asked you to investigate the presence of 260 or more characters of the path.
I am considering changing the folder structure after discover the path.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>There is no problem when you deploy directly under C drive, but when it is deployed to the following >Users directory, then an error occurs that the "path is too long".

Please teach the following.
 
- What is the program that generated "Path is too long" error?
(OS? .NET Framework? OpenTouryo? Or Other?)
- When "Path is too long" error occurs?
(When user clicks some button? When developer deploy OpenTouryo to some folder? Or Other?)

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>The above is a known.
 
Ok. We have confirmed the cause of the problem.

>I asked you to investigate the presence of 260 or more characters of the path.

This is the path exceeding 260 characters
<b>C:/Users/sandukur/Source/Repos/OpenTouryoTemplates4/root_VS2012/programs/C#/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/WSClientWinStore_sample/Service References/MuServiceReference/WSClientWinStore_sample.MuServiceReference.CallResponse.datasource</b>

We tried to count the number of characters using excel sheet, we got the following error
![image](https://cloud.githubusercontent.com/assets/7530499/12940169/81f06dc2-cfec-11e5-814c-bd1d872a63f7.png)

Total length of the above path is:<b>263</b>

**Comment by daisukenishino** [comment]
@kishoreandukuri 

Thank you for reporting.

Only one path ?　Is there else path ?

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Thank you for reporting.

You are welcome

>Only one path ?　Is there else path ?

We got this error only in one path as above

**Comment by daisukenishino** [comment]
@kishoreandukuri 

> We got this error only in one path as above

Please extract all of the path.
And please pick up all of the long path.

**Comment by kishoreandukuri** [comment]
@daisukenishino 
>Please extract all of the path.
And please pick up all of the long path.

Sure, we will work on this after completing the [task](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/30#issuecomment-182163230)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

> Please teach the following.

"unzip" and "git clone", etc will be failed by constraint of file path length of the every Windows OS.

This problem has been reported from the old days.

In this issue, we will correspod to prevent the problem occurrence by to shoten the path length if the user uses the Github cooperation function of VS2015. The default path of this feature is the "C:\Users\UserName\Documents\GitHubVisualStudio\RepositoryName".

If  it is set as follows,
- UserName : XXXXXXXXXX(10 characters)
- RepositoryName : OpenTouryoTemplates

Then, the number of characters at this time is 68 characters.
- C:\Users\XXXXXXXXXX\Documents\GitHubVisualStudio\OpenTouryoTemplates

The length of the longest path must be adjusted so as not to exceed the 255.

**Comment by daisukenishino** [comment]
# Finalized
Because Silverlight has already been deleted, Store app will be only target of this modifiticaion.

### How to fix
I'm going to modify like this.

- 220 + 69 = 286 characters  
root_VS2015/programs/C#/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/WSClientWinStore_sample/ServiceReferences/SbServiceReference/WSClientWinStore_sample.SbServiceReference.SelectAll_DSResponse.datasource

▼ ▼ ▼

- 177 + 69 = 246 characters  
root_VS2015/programs/C#/Samples/WinStore_samples/WinStore_sample/Service References/SbServiceReference/WinStore_sample.SbServiceReference.SelectAll_DSResponse.datasource

This path fit within 255 characters.

### Fix procedure
##### Move the folder.
- src :  
root_VS2015/programs/C#/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/
- dst :  
root_VS2015/programs/C#/Samples/WSClientWinStore_samples/

##### Change the folder name as follows.
WSClientWinStore ---> WinStore

##### Replace the strings in these files by "Grep&Replace" as follows.
WSClientWinStore ---> WinStore

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/145#issuecomment-193180002

Thank you for finalizing this task.
We will add it in the current plan.

> Change the folder name

In this solution, there is a project [WSClientSL_sample.Web](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2015/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/WSClientSL_sample.Web).

Does this project name is also required to change like <b>WinStoreSL_sample.Web</b>?
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Does this project name is also required to change like WinStoreSL_sample.Web?
Please confirm.

It is a good proposal.
Please check, since I modified [the procedure](https://github.com/OpenTouryoProject/OpenTouryo/issues/145#issuecomment-193180002).

By the way, "SL" is abbreviation of the "Silverlight".

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>By the way, "SL" is abbreviation of the "Silverlight".

"SL" may not be a general abbreviation of Silverlight.
The article of "SL" in wikipedia does not describe Silverlight.

　SL - Wikipedia
　https://en.wikipedia.org/wiki/SL

**Comment by SandeepNayak077** [comment]
@daisukenishino 
@yusukemaegawa 

We will modify according to [this procedure](https://github.com/OpenTouryoProject/OpenTouryo/issues/145#issuecomment-193180002).
If the procedure is modified, please notify us.

We have planned to do this correspondence to root_VS2012 - root_VS2015.
Does our understanding is correct?
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>If the procedure is modified again, please notify us.

OK. We will do so.

>We have planned to do this correspondence to root_VS2012 - root_VS2015.
Does our understanding is correct?

Yes, you should modifiy VS2012-2015 that is included Store App

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Rename of namespace is required [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/files/resource/Xml/TMInProcessDefinition.xml#L14) for developer understanding.
And also because the silverlight support is depricated. 

Shall we change as following?
WSClient<b>SL</b>_sample.Web --> WSClient_sample.Web

Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Rename of namespace is required here for developer understanding.
And also because the silverlight support is depricated.

I see.
The error message of the previous report was due to the latebounding using this XML difinition.

>Shall we change as following?
WSClientSL_sample.Web --> WSClient_sample.Web


Yes, please.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have renamed the namespace of silverlight client.
We have created [pull request-106](https://github.com/SymphonyTeleca/OpenTouryo/pull/106).

Please merge the code.
