### ISSUE TITLE
When the path includes a blank character, build using the batch file fails.

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#146]
# Summary

When user arranges the OpenTouryo at the path that includes a blank character, the following code fails.
I think that it is necessary to modify the build batch files.

```bat
@rem --------------------------------------------------
@rem Get the path to the executable file.
@rem --------------------------------------------------
set CURRENT_DIR=%~dp0
```

# Details
For example, when user arranges the OpenTouryo at "C:\Users\xxx\Documents\Visual Studio 2015\Projects", the following program will be executed.

```bat
set CURRENT_DIR=C:\Users\xxx\Documents\Visual Studio 2015\Projects\root\program\C#
```

Because the path is not enclosed in quotation marks, the following error occurs.

'C:\Users\xxx\Documents\Visual' is not recognized as an internal or external command, operable program or batch file.

Therefore, I think that the build batch files should be modified as follows.

```bat
@rem --------------------------------------------------
@rem Get the path to the executable file.
@rem --------------------------------------------------
set CURRENT_DIR="%~dp0"
```

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Please tell us the PullRequest corresponding to this issue.
We are considered as follows. All of pullrequests exist in the following?

- OpenTouryo
  - https://github.com/SymphonyTeleca/OpenTouryo/pull/97
- OpenTouryoTemplates
  - https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/84
  - https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/85
  - https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/86

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/146#issuecomment-183145096

Yes, those are correct pull requests of this task.
Please review and let us know.
