### ISSUE TITLE
Refactoring and quality Improvement (1)

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#149]
# Requirement
These pointed out items have potential that will be refactored.

## Please correct the following defects.
- #### [No1](#issuecomment-178399677) : Canceled.
- #### [No2](#issuecomment-192104950) : Completed.
- #### [No3](#issuecomment-197089822) : Canceled.
- #### [No4](#issuecomment-226071783) : Completed.
- #### [No5](#issuecomment-231352897) : Completed.
- #### [No6](#issuecomment-238152818) : Completed.

## The targets are below the repositories.
- [OpenTouryoProject/OpenTouryo](https://github.com/OpenTouryoProject/OpenTouryo/)
- [OpenTouryoProject/OpenTouryoTemplates](https://github.com/OpenTouryoProject/OpenTouryoTemplates)
  - Modifications are merged from **OpenTouryo**.
  - Therefore, to modify the **OpenTouryoTemplates** in case that does not exist in the **OpenTouryo**.

I got the best opportunity by the V2 release.
Therefore, at the time of release of V2, only fix "v2prep" branch in the following repository.
- [OpenTouryoProject/OpenTouryo "v2prep" branch](https://github.com/OpenTouryoProject/OpenTouryo/tree/v2prep)

**Comment by daisukenishino** [comment]
##### 
https://github.com/OpenTouryoProject/OpenTouryo/blob/master/root/programs/C%23/Frameworks/Infrastructure/CustomControl/Control/WebCustomTextBox.cs#L317

```c#
public bool Validate(out List<string> result)
{
    // フラグ
    bool hasError = false;
    // 結果
    result = new List<string>();

    // omit

    hasError = true;
    result.Add(CmnCheckFunction.xxx);

    // omit

    return !hasError;
}
```

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I've registered this to the [issue](https://github.com/OpenTouryoProject/OpenTouryo/issues/149).

**Comment by daisukenishino** [comment]
Missing number occurs because the file has been deleted by the https://github.com/OpenTouryoProject/OpenTouryo/issues/157.

Truncate the file number as follows.
```
12_Build_WinStore_sample.bat ---> 11_Build_WinStore_sample.bat
```

- Location
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2012/programs/C%23
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013/programs/C%23
  - https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2015/programs/C%23

**Comment by daisukenishino** [comment]
https://github.com/OpenTouryoProject/OpenTouryo/pull/160#discussion_r56259746

It is meaningless that you assign the return value of showModalDialog method to variable ret.
```JS
  var ret = window.showModalDialog(dialogFrameUrl.value, args, style);
  ret = Fx_GetCookie("fx_window_returnValue");
```
▼ ▼ ▼
```JS
  window.showModalDialog(dialogFrameUrl.value, args, style);
  var ret = Fx_GetCookie("fx_window_returnValue");
```

**Comment by daisukenishino** [comment]
Nuget correspondence generated the following warning.

```TXT
"...root_VS2013\programs\C#\Frameworks\Infrastructure\Public\Public.csproj" (既
定
のターゲット) (4) ->
(CoreCompile ターゲット) ->
  IO\ZipBase.cs(282,17): warning CS0618: 'Ionic.Zip.ZipFile.UseUnicodeAsNecessa
ry' は古い形式です: 'Beginning with v1.9.1.6 of DotNetZip, this property is obso
lete.
 It will be removed in a future version of the library. Your applications shoul
d  use AlternateEncoding and AlternateEncodingUsage instead.' [C:\root_VS2013\p
rograms\C#\Frameworks\Infrastructure\Public\Public.csproj]

    1 個の警告
    0 エラー
```

**Comment by daisukenishino** [comment]
##### LayerD

- https://github.com/OpenTouryoProject/SampleProgram/pull/19/files#r65655188
- https://github.com/OpenTouryoProject/SampleProgram/pull/19/files#r65494120
- https://github.com/OpenTouryoProject/SampleProgram/pull/19/files#r65498786

**Comment by daisukenishino** [comment]
##### LayerD

The paramSign of PostgreSQL is changed to "@" from ":" at the https://github.com/OpenTouryoProject/OpenTouryo/commit/a517e310822741119304d2b513d9ad3ab6829611

In this case, a SQL files of sample are also necessary to change.
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/files/resource/Sql/pstgrs

**Comment by daisukenishino** [comment]
### Improved the UI of DaoGen_Tool

#### Unification of terminology
- D layer -> Data tier
- automatic generation tool -> (Data tier) generator

#### "select data provider" section in Form2
- Include a data provider infomation to the D layer definition information file.
- And, delete "select data provider" section in Form2.

**Comment by supragyan** [comment]
@daisukenishino 

>Unification of terminology
D layer -> Data tier
automatic generation tool -> (Data tier) generator

Ok.We will update this.
Please suggest Japanese translation value for **Data tier generator** key.

**Comment by daisukenishino** [comment]
@supragyan 

[The work](https://github.com/OpenTouryoProject/OpenTouryo/issues/149#issuecomment-238152818) is in another issue.
Therefore, this work is not included in the work until end of September.
