### ISSUE TITLE
Remove a samples of the Silverlight and XBAP for to end this support.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#157]
# Requirement
We want to end Silverlight and XBAP support.

Because new introduction is a little,
but there is alot of maintenance work.

Therefore, We remove the following projects.

##### [root](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/)
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWPFbap_sample

##### [root_VS2010](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2010)

- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2010/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2010/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWPFbap_sample

##### [root_VS2012](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2012)

- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2012/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2012/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWPFbap_sample

##### [root_VS2013](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013)

- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWPFbap_sample
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013/programs/C%23/Samples/WinAzure_sample
  - /ProjectX_sample (ProjectX_sample itself does not deleted.)
    - WebService
    - Silverlight.js
    - WSClientSL_sampleTestPage.aspx
    - WSClientSL_sampleTestPage.html
  - WSClientSL_sample

##### [root_VS2015](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2015)

- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2015/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2015/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWPFbap_sample
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2015/programs/C%23/Samples/WinAzure_sample
  - /ProjectX_sample (ProjectX_sample itself does not deleted.)
    - WebService
    - Silverlight.js
    - WSClientSL_sampleTestPage.aspx
    - WSClientSL_sampleTestPage.html
  - WSClientSL_sample

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/157#issue-137531461
> https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/develop/root_VS2013/programs/C%23/Samples/WinAzure_sample/ProjectX_sample (ProjectX_sample itself does not deleted.)

<h4>Our understanding</h4>

Except the <b> /WinAzure_sample/ProjectX_sample/</b>, all other projects in the WinAzure_sample solution must be deleted.
- /WinAzure_sample
 - /ASPNETWebService (Delete)
 - /ProjectX_sample (<b>Do not delete</b>)
 - /WSClientSL_sample (Delete)
 - /WindowsAzureProject (Delete)

Or
While deletion care should be taken care that the <b>/WebApp_sample/ProjectX_sample/ </b> must not be deleted.

please confirm our understanding.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>please confirm our understanding.

- /WebApp_sample/ProjectX_sample/ must not be deleted.
- Delete the other than /WinAzure_sample/ProjectX_sample.
- However, please delete some of the files related to Silverlight in the /WinAzure_sample/ProjectX_sample.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/157#issuecomment-191023926
> Delete the other than /WinAzure_sample/ProjectX_sample.

If we delete other than the /WinAzure_sample/ProjectX_sample/ like the cloud project /WinAzure_sample/WindowsAzureProject/,
Then only the /WinAzure_sample/ProjectX_sample/ remains in the solution.

That means, the <b>/WinAzure_sample/ProjectX_sample/</b> becomes the azure cloud project.
Please correct me if I am wrong.

> https://github.com/OpenTouryoProject/OpenTouryo/issues/157#issuecomment-191023926
> However, please delete some of the files related to Silverlight in the /WinAzure_sample/ProjectX_sample.

Ok we understood about this part.
In the /WinAzure_sample/ProjectX_sample/ project, 
we must delete only the files which are related to Silverlight application.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Please correct me if I am wrong.

**/WinAzure_sample/WindowsAzureProject/** must not be deleted.
This is because, this project is a mandatory file to Azure Paas project.
Therefore, leaving the **/WinAzure_sample/ProjectX_sample/** and **/WinAzure_sample/WindowsAzureProject/** in the **/WinAzure_sample/**.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/157#issuecomment-191117439

Yes, that's why, we were in the dilemma.

Thank you for the information.
We will continue this correspondence.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We are requesting to review the [2013_WinAzure_sample](https://github.com/SymphonyTeleca/OpenTouryoTemplates/commit/d210c865ce66220fd8ddcca8974540d158873c18) and the [2015_WinAzure_sample](https://github.com/SymphonyTeleca/OpenTouryoTemplates/commit/7c2946a46db892214fab6a579f92a20a6bf34afb) code commit.
Please let us know if there is anything wrong.

If there is no problem, then please merge the pull request [103](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/103) and [104](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/104).

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Instruction was not clear about **/WinAzure_sample**.

It was clarified as follows.

- **/WinAzure_sample**
  - **/WindowsAzureProject** (Do not delete)  
    - **/WindowsAzureProject** must not be deleted.  
    - This is because, this project is a mandatory file to Azure Paas project.
  - **/ProjectX_sample** (Do not delete)
    - **/ProjectX_sample** must not be deleted.
    - However, please delete some of the files related to Silverlight in the **/ProjectX_sample**.
      - WebService
      - Silverlight.js
      - WSClientSL_sampleTestPage.aspx
      - WSClientSL_sampleTestPage.html
  - **/ASPNETWebService** (Do not delete)  
Because this project is used from X for 3 tier layering.
  - **/WSClientSL_sample** (Delete)

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/157#issuecomment-191566348

Ok, thank you for the information.
We will modify accordingly.
