### ISSUE TITLE
Some of the problem of asynchronous processing service are found at the acceptance.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#164]
# Report problems

##### Connection String
The default value of this project is the following.
```
Data Source=localhost\sqlexpress;Integrated Security=SSPI;Initial Catalog=AsyncProcessingServiceDB;
```

The following settings have a problem of different from default value.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/app.config
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/app.config

##### XML definition
The default value should be set with the sample program rather than **"azure strage copy"**.

https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMProtocolDefinition.xml#L30
```
<Transmission id="AzureStrageCopy" protocol="1"/>
```
▼ ▼ ▼
```
<Transmission id="AsyncSvc_sample" protocol="1"/>
```

https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/TMInProcessDefinition.xml
```
<Transmission id="AsyncSvcSample" assemblyName="AsyncSvc_sample" className="AsyncSvcSample.LayerB" />
```

### Behavior
If there is a problem with the connection string,
then the following behavior was showed.

Modify the program by analyze the problem.

##### Start Service
This service would be started successfully from the SCM.
- It should fail to start.

##### Stop Service
In addition, This service could not be stopped from the SCM.
- Do not fail to stop.

**Comment by daisukenishino** [comment]
# Modify the sample program
To Modify the behavior of the sample program for respond to a variety of test cases.

#### Remove the comment to enable the loop.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs#L224

#### Handle the following condition branch in the default case of switch in loop.

##### Throw BusinessSystemException at 1% probability
Then, this task will be terminated.

##### Throw BusinessApplicationException at 10% probability
It will be retried by be returned in the management table queue.

##### Increments the progress rate.
###### Progress rate of 100%
Successful completion by return from the method.

###### Progress rate is less than 100%
Continue the loop after update the progress rate of the management table.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

<h3>Solution</h3>
> https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issue-141826042
> Behavior
> Start Service

The above explained behavior can be eleminated by implementing followings:

**1.** Creating a thread safe property [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L130).
```CS
// <summary>Asynchronous Processing Service initializaion flag (thread-safe)</summary>
private volatile bool _isAsyncProcessInitialized = false;
```

**2.** Creating a method to set the Asynchronous Processing Service initializaion property [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L639).
```CS
/// <summary>
/// Sets Asynchronous Processing Service initialization flag by checking prerequisites
/// </summary>
public void SetAsyncProcessInit()
{
    try
    {
        // Checks for successful connection to the database.
        AsyncProcessingServiceParameterValue asyncParameterValue = new AsyncProcessingServiceParameterValue("AsyncProcessingService", "TestConnection", "TestConnection", "SQL",
                                                                                new MyUserInfo("AsyncProcessingService", "AsyncProcessingService"));        
        LayerB layerB = new LayerB();
        layerB.DoBusinessLogic((BaseParameterValue)asyncParameterValue, DbEnum.IsolationLevelEnum.NoTransaction);

        // Asynchronous Processing Service initializes successfully without any errors
        this._isAsyncProcessInitialized = true;
    }
    catch (Exception ex)
    {
        // Service Failed due to unexpected exception.
        this._isAsyncProcessInitialized = false;
        LogIF.ErrorLog("ASYNC-SERVICE", string.Format(GetMessage.GetMessageDescription("E0000"), ex.Message.ToString()));
    }
}
```
**3.** Call the above method in the service constructor [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L160).
**4.**  Using **_isAsyncProcessInitialized** property, check inside service events (Start, Stop, Pause) to continue to serve their purpose.
- [OnStart](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L195): Before creating main thread, check the property and stop the service.
- [OnStop](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L219) & [OnPause](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L233): If main thread was not created, skip the override feature and stop the service.  


> https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issue-141826042
> Behavior
> Stop Service

The above behavior can be eleminated by including excetion handling statements (<b>try-catch</b> block) in the <b>StopAsyncProcess</b> method [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L605). 

Please let us know your opnion.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issuecomment-222928797

I think that there is no need to add the **SetAsyncProcessInit** method.
I think that it is sufficient to add a **new flag** to **MainThreadInvoke** method.

##### New flag :
- This flag is for manage the status of main thread.
- Change the contents of the start process and end process by the state of the flag.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issuecomment-222946299

If we add only flag, the service will start, throws an exception, terminate main thread and never returns.
And, we cannot call **Stop()** method inside main thread.
However, service can be stopped using SCM without errors.

If we call **Stop()** method inside main thread, 
The service may enters into deadlock state.
In this state, we cannot stop service using SCM or uninstall properly using command prompt.
It must be stopped by Task manager or restarting the system.

Please confirm and let us know our understanding.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Onstop event has not been completed, if connection string was wrong. This is maybe due to a occurrence connection exception by the problem of the connection string in Onstart event.

I think that it is good if service can identify this by the new flag in OnStart event.
Thereby it can be controlling so as not to perform the DB connection in OnStop event.

Please let us know your opnion.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issuecomment-223178779

Yes the above procedure can be done without any problem.

In this case, the user must manually stop the service in the SCM by checking logs.
As the requirement given [here](https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issue-141826042) (**"It should fail to start."**), cannot be achived.
Because the new flag is detected in **MainThreadInvoke** instead of **OnStart**.

If the **"It should fail to start."** behavior is not required, then we will proceed with the [above procedure](https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issuecomment-223178779).
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

At that time, I thought as **"It should fail to start."**.
But it will not be able to detect all of the various problems as shutdown of the DB by **"TestConnection"**.
For this reason, I think that this method in the **OnStart** event is not perfect for stop reliably.
Therefore, I recommend the way that to record the state of the main thread by flag at [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService/AsyncProcessingService.cs#L347).

**Comment by SandeepNayak077** [comment]
@daisukenishino 

As we have discussed in the meeting today (03-Jun-2016),
Updated [this comment](https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issuecomment-222928797) by changing the following:
- Renamed flag name from **_isAsyncProcessInitialized** to **_isServiceException**.
- Renamed method name from **SetAsyncProcessInit** to **SetServiceException**
- Discribed about **TestConnection** method in point **(5)** 

Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I think that it is required to detect the problem
  by also adding such a flag in the **MainThreadInvoke** method.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation.
Yes, we will also set **_isServiceException** flag in the **MainThreadInvoke** method

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I see.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issuecomment-203190553

The following implementations are done, to Modify the behaviour of the sample program for respond to a variety of test cases.

**1.** Creating the following member variables [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs#L77).
```CS
// Task progress rate
private int ProgressRate;

// Constant values
const int STOP_STATE = 3;
const int ABORT_STATE = 10;
const int SUCCESS_STATE = 100;
```

**2.** Creating a new method to generate random progress rate [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs#L253).
```CS
/// <summary>
///  Generates task new progress rate based on last progress rate in increasing order.
/// </summary>
/// <param name="lastProgressRate">Last progress rate</param>
/// <returns>New progress rate</returns>
private int GenerateProgressRate(int lastProgressRate)
{
    Random randProgressRate = new Random();
    return randProgressRate.Next(lastProgressRate + 1, SUCCESS_STATE + 1);
}
```

**3.** Replacing loop comment with the following **while-loop** statement, which starts [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs#L224) and ends [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs#L248).
```CS
while (true)
```

**4.** Modifying **default** case with the following code [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs#L240).
```CS
default:
    // Generates new progress rate of the task.
    ProgressRate = this.GenerateProgressRate(ProgressRate);

    // Update the progress rate in database.
    this.UpdateProgressRate(taskID, userReturnValue, ProgressRate);

    if (ProgressRate == STOP_STATE)
    {
        // Update ABORT command to DB
    }
    else if (ProgressRate == ABORT_STATE)
    {
        // Update STOP command to DB
    }
    else if (ProgressRate == SUCCESS_STATE)
    {
        // Task is completed sucessfully.
        return;
    }

    // Sleeps the thread, to minimize the CPU utilization.
    System.Threading.Thread.Sleep(this.NumberOfSeconds * 1000);
    break;
```

**5.** Initializing the value of **ProgressRate**, to handle **Resume** process [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample/LayerB.cs#L201).
```CS
if (userReturnValue.CommandId == (int)AsyncProcessingServiceParameterValue.AsyncCommand.Stop)
{
    // Retry task: to resume asynchronous process in the middle of the processing.
    this.ResumeProcessing(userParameterValue.TaskId, userReturnValue);

    // Get updated progress rate from DB.
    ProgressRate = 50;
}
else
{
    // Otherwise, implement code to initiating a new task. 
    //...
    // Hence, initializing progress rate to zero.
    ProgressRate = 0;
}
```

Please let us know your opinion.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Its very difficult and rare case to pick up STOP_STATE and ABORT_STATE value from 1 to 100 random values.
So, we create an ArrayList to hold multiple values of STOP_STATE and ABORT_STATE.
Example:
```CS
// Random values will be added to ArrayList at the runtime.
// The following initialized values are just an example.
ArrayList stopStates = {1, 3, 56}; // 3% random values 
ArrayList abortStates = {10, 25, 36, 68, 71}; // 5% random values and that were not added to stopStates.
```

The above approach produces more chance to respond to various test cases of sample program.
Please let us know your opinion.

We can also send the **stopStates** and **abortStates** from user application instead of **arrayData** [here](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/AsyncSvc_sample/TestAsyncSvc_Sample/Program.cs#L75).
Please let us know your opinion.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

```CS
Random rnd = null;
int randomNumber = 0;

// BusinessSystemException
rnd = new Random();
randomNumber = rnd.Next(100);
if(randomNumber < 3)
{
    throw new BusinessSystemException(・・・);
}

// BusinessApplicationException
rnd = new Random();
randomNumber = rnd.Next(100);
if(randomNumber < 10)
{
    throw new BusinessApplicationException(・・・);
}

// Generates new progress rate of the task.
ProgressRate = this.GenerateProgressRate(ProgressRate);
```

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the support.
Our understanding was as same as you explained,
The only modification in the implementation is replacing the constant values to configuration settings.
- **STOP_STATE** (Constatnt) ==> **StopPercentage** (Config setting)
- **ABORT_STATE** (Constatnt) ==> **AbortPercentage** (Config setting)

> https://github.com/OpenTouryoProject/OpenTouryo/issues/164#issuecomment-224404892

As discussed in the meeting, 
A **proposal** of implementing the StopPercentage and AbortPercentage with **ArrayList** is **not required**.
