### ISSUE TITLE
Improved the UI of DaoGen_Tool

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#166]
# Requirement

### Image 
~~Paste its image, after it is established.~~
It has been sent by the IP server.

##### The problem of btnDaoAndSqlGen.Text
Consider the modification of the following wording.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form1.resx#L498
```XML
<data name="btnDaoAndSqlGen.Text" xml:space="preserve">
  <value>-Generate ~ Dao · SQL file</value>
</data>
```

##### The problem of caption
- 棟梁 ≠ master builder
- 棟梁 = touryo
![daogen_tool](https://cloud.githubusercontent.com/assets/9585990/14272045/09419b70-fb3a-11e5-870e-969f1418a5e3.png)

### Other request
Please create video after this improvement.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

The image has been sent by the IP server. Hide the tab of the header part, you should be modified to transition with the button. The program changes will be minimal by this.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/166#issuecomment-225155545

Sure, we will be get ready with the **DaoGen_tool.exe** and we will discuss in the next meeting.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

As discussed over the call today (15-Jun-2016),
#### Common points:
- Due to the limitation in the WinForms edges of button and Forms cannot be curved and it will be rectangular in shape.

#### Form1 changes: 
- There must not be any change in the functionality of **Debug window**, but there might be change in the UI based on **main window** background color.
- Add resource for **English** translation for **Debug window**
 - Checkbox: **"Debug"**
 - Tabs: **"Tab1", "Tab2", "Tab3"**

#### Form2 changes:
- We will look for workaround to match the functionality according to the new UI.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/166#issuecomment-226141497

I see.

**Comment by supragyan** [comment]
@daisukenishino 

## Questions for Form2 changes
### OPTIONS tab
![options](https://cloud.githubusercontent.com/assets/9566037/16380955/9b50687c-3c97-11e6-897c-5bb0a5a77e1b.PNG)

**OK button**
When user click on OK button,the below two possibilities are there:
- It should close the OPTIONS tab and open STEP 2 tab

or

- It generates aspx screens from Options tab itself.

As of now we have implemented as per first option.

**Cancel button**
When user click on Cancel button,the below two possibilities are there:
- It should cancel the OPTIONS tab and open STEP 2 tab

or

- It cancels only selected fields of OPTIONS tab.

As of now we have implemented as per second option. 

Please inform our understanding.
If there is no problem then we will create pull request.

**Comment by supragyan** [comment]
@daisukenishino 

## Form2 screen changes
![options1](https://cloud.githubusercontent.com/assets/9566037/16384531/dabfe906-3ca6-11e6-8ec9-bd94a9fce52f.PNG)

###  Select Data Provider
To achieve Select Data Provider section as per above screen
- We have removed groupbox
- Modified code without using groupbox

###  Oracle ODP.Net
To achieve Oracle ODP.Net section as per above screen
- We have removed groupbox
- We have used label for separator
- Modified code without using groupbox

Same as above for TogenerateDTO groupbox and Table Maintanance screen groupbox.
Because if we use groupbox then we can not achieve acreen as per above UI.

Please confirm our implementation process.

**Comment by supragyan** [comment]
@daisukenishino 

We have modified as per below to improve DaoGen tool UI:

**Note** :We have pointed out the differences as compared between old and new DaoGen tool.

# Form1 changes

## UI and Code cnangs

### Form1.Text
**UI changes**
- Renamed Form1 text value

  Master builder: D layer automatic generation tool- D layer definition information file generation
▼ ▼ ▼
D layer automatic generation tool

**Code changes**
  - No code changes

### MenuStrip control changes
**UI changes**
- Removed Restart_ToolStripMenuItem and Close_ToolStripMenuItem from Menustrip1
- Renamed Restart_ToolStripMenuItem text to STEP1

**Code changes**
- Removed Restart_ToolStripMenuItem_Click and Close_ToolStripMenuItem_Click events.
```CS
 #region メニューの処理

        /// <summary>やり直す（再起動）</summary>
        private void Restart_ToolStripMenuItem_Click(object sender, EventArgs e)
        {
            Application.Restart();
        }

        /// <summary>閉じる</summary>
        private void Close_ToolStripMenuItem_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        #endregion
```
### Button control changes
**UI changes**
- btnGetSchemaInfo.Text

  Schema information acquisition
▼ ▼ ▼
acquisition

  Size, color has changed

- btnListTable.Text

  ▼ Get table list to connect to the DB ▼
▼ ▼ ▼
Get Table List

  Size,Color has changed

- btnDelTable.Text

  Delete Selected Tables
▼ ▼ ▼
Delete

  Size,Color has changed

- btnLoadColumn.Text

  Load Column info
▼ ▼ ▼
Load

  Size,Color has changed
- btnSetPrimaryKey.Text

  Set primary key of selected table
▼ ▼ ▼
Set

  Size,Color has changed

- btnDaoDefinitionGen.Text
  ▼Generate D layer definition info▼
▼ ▼ ▼
Generate

  Size,Color has changed

- btnDaoAndSqlGen.Text

  -Generate ~ Dao · SQL file
▼ ▼ ▼
Go to STEP 2

  Size,Color has changed

**Code changes**
  - No code changes

Old screen

![1](https://cloud.githubusercontent.com/assets/9566037/16488208/16cb212a-3eed-11e6-9bb2-668a35eb57d6.png)

new screen

![1](https://cloud.githubusercontent.com/assets/9566037/16488227/2bc2a922-3eed-11e6-9ac3-223377c8a48d.PNG)

# Form2 Changes

## UI and Code changes

### Form2.Text

**UI changes**
 - Renamed the text

   Master builder: D layer automatic generation tool - D layer, Dao · SQL file generation
▼ ▼ ▼
D layer automatic generation tool - D layer, Dao · SQL file generation

### menuStrip1

  Removed Close_ToolStripMenuItem from Menustrip1

### TabPage1.Text
  Renamed text Step1 to STEP2

### TabPage2.Text
  Renamed text Step2 to OPTIONS

**Code changes**
-  Form2.Desiner.cs

  Modify as below code to display only STEP 2 i.e TabPage1 
```CS
            resources.ApplyResources(this.tabControl1, "tabControl1");
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
```
▼ ▼ ▼
```CS
 resources.ApplyResources(this.tabControl1, "tabControl1");
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
```

### Groupbox changes
 - gbxInput

   btnSetDaoDefinition.Text

    Select Folder Path
▼ ▼ ▼
Folder

     btnSetDaoDefinition size and color has changed.

      btnSetSourceTemplate.Text

      Specifies  Root Folder Path
▼ ▼ ▼
Folder

 - gbxDaoTemplateLanguage
  Remove gbxDaoTemplateLanguage groupbox 
  Added rbnDTL_CS and rbnDTL_VB radio button controls separately.

 - gbxDaoTemplateEncoding
  Remove gbxDaoTemplateEncoding groupbox
  Added new lblEncodingDao label
  Added cmbDDEncoding separately.

 - gbxSqlTemplateEncoding
   Remove gbxSqlTemplateEncoding groupbox
   Added new lblSql label
   Added cmbSTEncoding separately.

- Button control changes

 - btnDaoAndSqlGen changes

  Move the location of btnDaoAndSqlGen control from Form to Tabpage1
  Rename the text of btnDaoAndSqlGen
  - Generate Dao · SQL, DTO File -
▼ ▼ ▼
Generate Program

 - Options button

   Added new Options button to display Tabpage2

- Code changes
```CS
private void btnOptions_Click(object sender, EventArgs e)
        {
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Controls.Remove(this.tabPage1);
        }
```

 - OK button

  Added new OK button to store the options changes and redirects to the STEP2

- Code changes
```CS
 private void btnOK_Click(object sender, EventArgs e)
        {
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Remove(this.tabPage2);
        }
```

 - Cancel button

   Added new Cancel button to cancel the options settings and redirects to the STEP2

- Code changes
```CS
 private void btnCancel_Click(object sender, EventArgs e)
        {
            switch (this.strDAP)
            {
                case "OLE":
                    this.rbnOLE.Checked = true;
                    break;
                case "ODB":
                    this.rbnODB.Checked = true;
                    break;
                case "Oracle":
                    this.rbnODP.Checked = true;
                    break;
                case "DB2":
                    this.rbnDB2.Checked = true;
                    break;
                case "MCN":
                    this.rbnMySQL.Checked = true;
                    break;
                case "PstGrS":
                    this.rbnPstgrs.Checked = true;
                    break;
                default:
                    this.rbnSQL.Checked=true;
                    break;
            }

            if (this.cbxOnlyTableMaintenance.Checked || this.cbxTableMaintenance.Checked)
            {
                this.cbxOnlyTableMaintenance.Checked = false;
                this.cbxTableMaintenance.Checked = false;
            }
            if (cbxOnlyDTO.Checked || this.cbxEntity.Checked || this.cbxTypedDataSet.Checked)
            {
                this.cbxOnlyDTO.Checked = false;
                this.cbxEntity.Checked = false;
                this.cbxTypedDataSet.Checked = false;
            }
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Remove(this.tabPage2);
        }
```

new screen
STEP2 tab
![2](https://cloud.githubusercontent.com/assets/9566037/16513483/ce565af4-3f82-11e6-8c0c-827f47c39915.PNG)
Options tab
![3](https://cloud.githubusercontent.com/assets/9566037/16513500/e6712d4e-3f82-11e6-9606-2349e4c34193.PNG)

**Comment by supragyan** [comment]
@daisukenishino 

## New Proposal for DaoGen tool

- STEP1
▼ ▼ ▼
Generate File

- **Search button** should be display to search specific tables

- **Table list** should pe propagated as below screen.
 - From left table list select the specific table for which screens needs to be generate.

![x](https://cloud.githubusercontent.com/assets/9566037/16521450/98e278b2-3fb4-11e6-9ef0-355ca1b8da34.PNG)

- **Generate button**
When click Generate button, one pop up should be display as "Are you sure to continue to generate schema files "

  **Note**
We will discuss about the pop up message later.

- Go to Step2
▼ ▼ ▼
Continue

- STEP 2
▼ ▼ ▼
Generate CRUD Screens

- DLayer Definition File,Source Template File,Output File should be mandatory field.

- Once click **Generate Program** without selecting above filelds it should not allow.

Please confirm our proposals.

**Comment by supragyan** [comment]
@daisukenishino 

We have not provided Japanese Translated terms for strings which newly added in DaoGen tool.
Will you provide these translated terms or we will take help from our internal translator.

If you can provide then we will share the list of new terms.

Please let us know.

**Comment by daisukenishino** [comment]
@supragyan 

Please explain modification points in the next meeting.

**Comment by daisukenishino** [comment]
@supragyan 

>https://github.com/OpenTouryoProject/OpenTouryo/issues/166#issuecomment-229943638

Get the help of a translator.
We will review the screen shot of the screen after the change.

**Comment by daisukenishino** [comment]
@supragyan 

Ctrl+Alt+PrintScreen is useful to get a screen shot of the window.

**Comment by supragyan** [comment]
@daisukenishino 

We have added Japanese translation for newly added keys in DaoGen tool.

And we did code commit to [#135](https://github.com/SymphonyTeleca/OpenTouryo/pull/135) because this pull request has not closed.

Please review and let us know.
