### ISSUE TITLE
How to reflect partially the difference of IE11 correspondence of the "01-72" version on the "01-71" version  ?

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#169]
# Requirement
It become difficult that import partially the IE11 correspondence of the "01-72" version on the "01-71" version. Because 01-72 version is also carried out to change URL for VS2013 support. I think that it can uptake the difference of IE11 correspondence of the "01-72" as the following procedure.

Please check.

### Procedure of partial upgrade
- Replace to the  latest [common.js](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js)
- Replace to the latest [DialogFrame.htm](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/Framework/DialogFrame.htm)
- Update of **"all the master pages"** partially by latest [master pages (*.mater)](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testBlankScreen.master#L14).  
Uptake the following additional part partially.

```HTML
<head id="Head1" runat="server">
・・・
    <!-- Resolve URL in the javascript-->
    <script type="text/javascript">
        var baseUrl = "<%= ResolveUrl("~/") %>";
    </script>
```

# Result
### Procedure of partial upgrade
There is no problem in above procedure.
The upgraded code have been tested.

### Examples of partial upgrade
see :https://github.com/OpenTouryoProject/OpenTouryo/compare/01-71...PartialUpgradeOfIE11Fromv01-71

**Comment by SandeepNayak077** [comment]
@daisukenishino 

<h3>Our understanding</h3>

1. Perform the difference check of all the <b>common.js</b> files and update it with [this latest code](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js).
2. Perform the difference check of all the <b>DialogFrame.htm</b> files and update it with [this latest code](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/Framework/DialogFrame.htm#L7).
3. Perform the difference check of all the <b>master pages (*.mater)</b> and update it with [this latest code](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testBlankScreen.master#L14).

Please confirm and let us know.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

This task is in order to support the corresponding partial importation of IE11 correspondence of "01-72" to user of "01-71". Finally, I would like to present the simple procedure to the user.

I want you to check the validity of this procedure.
And I want you to fix the procedure if there is a problem.

>1. Perform the difference check of all the <b>common.js</b> files and update it with [this latest code](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js).

The difference check is not required for the procedure.
Because I want to simplify the import procedure.

>2. Perform the difference check of all the <b>DialogFrame.htm</b> files and update it with [this latest code](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/Framework/DialogFrame.htm#L7).

The difference check is not required for the procedure.
Because I want to simplify the import procedure.

>3. Perform the difference check of all the <b>master pages (*.mater)</b> and update it with [this latest code](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/Common/testBlankScreen.master#L14).

This file must be imported by differential uptake.
In the master page, to import the following part.
```HTML
<head id="Head1" runat="server">
・・・
    <!-- Resolve URL in the javascript-->
    <script type="text/javascript">
        var baseUrl = "<%= ResolveUrl("~/") %>";
    </script>
```

**Comment by SandeepNayak077** [comment]
<h3>Procedure:</h3>
1. Download the "01-71" version ([here](https://github.com/OpenTouryoProject/OpenTouryo/releases)).
2. Upload this to a new feature branch.
3. Compare this new feature branch with "01-72" version or current "nishino" branch.
4. Merge required code (i.e. IE11 and URL issue related files) to feature branch.
5. Commit the code and report the feature branch name to @daisukenishino.
6. @daisukenishino can review the code with the latest commit logs and merge it to the actual "01-71" version.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>4 . Merge required code (i.e. IE11 and URL issue related files) to feature branch.

For here, please select the method that the procedure is simplified.
I think [the above procedure](https://github.com/OpenTouryoProject/OpenTouryo/issues/169#issue-145593475) is simple.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Yes sure, once its done we will inform the branch name.
Thank you for the confirmation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

As we have discussed in the call today,
We have updated our understanding in the [above comment](https://github.com/OpenTouryoProject/OpenTouryo/issues/169#issuecomment-206314448) with <b>Target</b> and <b>Out of scope</b> column.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have updated the [above comment](https://github.com/OpenTouryoProject/OpenTouryo/issues/169#issuecomment-206314448) with <b>Review link</b> column.
Please review partially upgraded code and let us know.
