### ISSUE TITLE
Converting a Web Site Project to a Web Application Project.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#173]
# Requirement
ProjectX_sample has been created as a WebSite of ASP.NET WebForms.
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample

### Recommend Web application
Microsoft seems to recommend web application for the new development using Visual Studio after 2012. Therefore, I want to change the Web site to the Web application at root folder.

- Web Application Projects versus Web Site Projects in Visual Studio  
https://msdn.microsoft.com/en-us/library/dd547590.aspx
  - For new development, we recommend that you choose web application projects.
  - For example, the next Visual Studio release after Visual Studio 2012 will have new tooling for creating web projects, and this new tooling will work only with web application projects.

### About mixture of MVC and WebAPI
Do not mix because it become difficult to understand.

### Reference
- Walkthrough: Converting a Web Site Project to a Web Application Project in Visual Studio  
https://msdn.microsoft.com/en-us/library/aa983476.aspx
- ASP.NET構成（Webサイト・Webアプリ） - マイクロソフト系技術情報 Wiki  
ASP.NETアプリケーションの種類について > 回答 > 選択の観点  
http://techinfoofmicrosofttech.osscons.jp/index.php?ASP.NET%E6%A7%8B%E6%88%90%EF%BC%88Web%E3%82%B5%E3%82%A4%E3%83%88%E3%83%BBWeb%E3%82%A2%E3%83%97%E3%83%AA%EF%BC%89#md58660b

**Comment by daisukenishino** [comment]
@supragyan 

The path has been changed.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/01-72/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/

▼ ▼ ▼

- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/

Please correct as soon as possible.

e.g. : Sessionタイムアウト防止機能 - Open 棟梁 Wiki
https://opentouryo.osscons.jp/index.php?Session%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%A2%E3%82%A6%E3%83%88%E9%98%B2%E6%AD%A2%E6%A9%9F%E8%83%BD

The following link has become a link broken.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L57
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/Framework/Js/common.js#L57

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>https://github.com/OpenTouryoProject/OpenTouryo/issues/173#issuecomment-234822343

This also affects your https://github.com/OpenTouryoProject/OpenTouryo/issues/184.

**Comment by supragyan** [comment]
@daisukenishino 

>The path has been changed.

At the moment of creating web application,,the web application is being created in this path https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/ProjectX_sample/
So we have not changed this path manually.

>Please correct as soon as possible.

Ok we will modify accordingly.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> https://github.com/OpenTouryoProject/OpenTouryo/issues/173#issuecomment-234833927

Yes it will affect.
But, no problem. I will re-create the feature branch without affecting code changes.
