### ISSUE TITLE
D-layer automatic generation tool: the message "Completion of generation of the D-layer definition information!" is always shown even if user cancel the operation.

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#176]
# Requirement
### The problem of display of finish message
The message "Completion of generation of the D-layer definition information!" is always shown even if user cancel the operation.

1. Launch D-layer automatic generation tool.
1. Connect DB.
1. Click "▼Generate D layer definition info▼" button.
1. Click "Cancel" button in Save File Dialog.
1. Even though user cancelled the operation, the message "Completion of generation of the D-layer definition information!" is shown.

I think that you should show the message such as "The operation was canceled." if user cancelled the operation.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Correspondence of [Can't invalidate an F1 key in IE11. #174](https://github.com/OpenTouryoProject/OpenTouryo/issues/174) will make modifications [to the ie_key_event.js](https://github.com/SymphonyTeleca/OpenTouryo/pull/124/files).

**Comment by daisukenishino** [comment]
@supragyan 

Please carry out this modyfication at https://github.com/OpenTouryoProject/OpenTouryo/issues/166.

**Comment by supragyan** [comment]
@daisukenishino 

We also thought about this issue.
So we have pointed this as new proposal and also explained in https://github.com/OpenTouryoProject/OpenTouryo/issues/166#issuecomment-229939737
such as 
**In Generate button**
 - Cancel should not display pop up message.
 - Save only should display pop up message.

but we gave this proposal as bit different such as when Click "Cancel" button in Save File Dialog it should not show the  message "Completion of generation of the D-layer definition information!"

>I think that you should show the message such as "The operation was canceled." if user cancelled the operation.

Ok. We will do accordingly.

For this sprint Merge activity has assigned to me.
Do we need to take this task in this sprint before started merge activity?
Please confirm.

**Comment by supragyan** [comment]
@daisukenishino 

>https://github.com/OpenTouryoProject/OpenTouryo/issues/176#issue-156191768

We have implemented code for Cancel message in D-layer automatic generation tool.
And did code commit in **dgenui-imrov** existing feature branch.
[#135](https://github.com/SymphonyTeleca/OpenTouryo/pull/135/commits/a737ffa8e57177ad2cdd83c154003936401e865e)

Please review and let us know.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Please close this issue If this issue has been resolved.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I confirmed that this issue was fixed by pull request #192.
