### ISSUE TITLE
Reflect the latest update of common.js to the MVC version.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#182]
# Requirement
Reflect the latest update of common.js to the MVC version.

### Content
[Cross-browser-compatible correspondence of the double submission prevention function. #161](https://github.com/OpenTouryoProject/OpenTouryo/issues/161)

### Supplement
Correspondence of [Can't invalidate an F1 key in IE11. #174](https://github.com/OpenTouryoProject/OpenTouryo/issues/174) will make modifications [to the ie_key_event.js file](https://github.com/SymphonyTeleca/OpenTouryo/pull/124/files). This correspondence is not necessary for MVC because MVC does not have the ie_key_event.js file.

**Comment by daisukenishino** [comment]
@SandeepNayak077 
@supragyan 

This is included in the merged work.

**Comment by supragyan** [comment]
@daisukenishino 

>This is included in the merged work.

Thank you for your valuable information.
However we have already merged common.js to the MVC_Sample in root_2013 and root_2015 for C# version.

**Comment by daisukenishino** [comment]
@supragyan 

I see.
