### ISSUE TITLE
Review of the build system ( ビルドの見直し

### ISSUE THREAD

**Issue by bleis-tift** [OpenTouryoProject/OpenTouryo#19]
現状の問題点を挙げます。

* ビルドにdevenvが必要(MSBuildではだめなのか)
* rootやroot_VSxxxx_TemplateBaseでコードがかなり重複している
* 大量のbatファイルの必要性が不明(MSBuildではだめなのか)
* DBのデータプロバイダが必要(NuGetから取るのではだめなのか)

.NETではMSBuildやNuGetによる管理が標準的であり、それに従った方がメリットが大きいと考えます。

**Comment by daisukenishino** [comment]
# 対応状況
#### ビルドにdevenvが必要(MSBuildではだめなのか)
[ビルドの標準をdevenvからMSBuildに変更しました](https://github.com/OpenTouryoProject/OpenTouryo/issues/119)。

#### 大量のbatファイルの必要性が不明(MSBuildではだめなのか)
[ビルドの標準をdevenvからMSBuildに変更しました](https://github.com/OpenTouryoProject/OpenTouryo/issues/119)が、
MSBuildのタスクは使用せず、未だ*.batを使用しています。

#### DBのデータプロバイダが必要(NuGetから取るのではだめなのか)
VS2015でNugetのサポートが充実してきたので、
[VS2015バージョンから外部ライブラリをNugetで取得する方式に変更する予定](https://github.com/OpenTouryoProject/OpenTouryo/issues/119)です。

#### rootやroot_VSxxxx_TemplateBaseでコードがかなり重複している
マージ作業にかなりの工数を要するため、重複したコードの解決を必要としていますが、
以下の問題で単純なリンクファイルの採用では解決しないので対応方法を検討中です。

##### .NETバージョンで分割
バイナリ ライブラリで提供するPublicとFramework名前空間は.NETバージョンで分割が適合すると思います。これはプロジェクト・ソリューション ファイルとソースコードのリンクファイルによりただし、以下の存在で「Visual Studioバージョンで分割」が残ります。

##### Visual Studioバージョンで分割
（１）サンプルプログラムやテンプレート部分や、（２）カスタマイズ可能レイヤであるベースクラス2、
カスタムコントロール、サービスインターフェイス、（３）ユーザインタフェースがあるプログラムはVisual Studioを開いてカスタマイズする可能性を考慮し、ユーザにコンバージョン作業を行わせることのないようにするためにVisual Studioバージョンで分割して提供する必要がある。Visual Studioバージョン間で以下が変更されるため、その部分の動作確認も必要だと考えています。

- バージョン違いのプロジェクト・ソリューション ファイルは、コンバージョンする必要がある。
  - *.sln
  - *.csproj, *.vbproj,
- コンバージョンでプロジェクト・ソリューション ファイル以外にも変更が入る。
  - *.configファイル
  - Visual Studioにより自動生成されるファイル
    - *.Designer.cs or vbファイル（UI、リソース）
    - Reference.cs or vbファイル（Webサービスの参照）

**Comment by daisukenishino** [comment]
このIssueをクローズします。
必要に応じて未完了のIssueを別のIssueに挙げて下さい。
