### ISSUE TITLE
The window collapses when the dpi size is Medium 125% or Larger 150%.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#191]
# Requirement 
Check the UI of all the tools at the condition that dpi size is Medium-125% or Larger-150%.

See:
https://github.com/SymphonyTeleca/OpenTouryo/pull/135#issuecomment-243039879
~ https://github.com/SymphonyTeleca/OpenTouryo/pull/135#issuecomment-243087470

### note:

This work is not included in the work until end of September.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

It seems that the window which collapses when the dpi size is not small - 100% is *OPTION* window only in *D layer auto generation tool*.

It might be a good idea to add the following code:
- [Form2.Designer.cs](https://github.com/SymphonyTeleca/OpenTouryo/blob/dgenui-imrov/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.Designer.cs)

```c#
// 
// tabControl1
// 
this.tabControl1.Controls.Add(this.tabPage1);
this.tabControl1.Controls.Add(this.tabPage2);  // Add this code.
resources.ApplyResources(this.tabControl1, "tabControl1");
this.tabControl1.Name = "tabControl1";
this.tabControl1.SelectedIndex = 0;
```

- [Form2.cs](https://github.com/SymphonyTeleca/OpenTouryo/blob/dgenui-imrov/root/programs/C%23/Frameworks/Tools/DaoGen_Tool/Form2.cs)

```c#
/// <summary>コンストラクタ</summary>
public Form2()
{
    InitializeComponent();
    this.tabControl1.Controls.Remove(this.tabPage2);  // Add this code.
}
```

**Comment by daisukenishino** [comment]
@supragyan 

In https://github.com/SymphonyTeleca/OpenTouryo/pull/135, please correspond in accordance with [the contents of the above](https://github.com/OpenTouryoProject/OpenTouryo/issues/191#issuecomment-243341115).

**Comment by supragyan** [comment]
@daisukenishino 
@yusukemaegawa 

>It might be a good idea to add the following code:

Thank you for your valuable information.

We have implemented as above and also tested by changing the dpi size is Medium-125%.
Now the Options screen is not collapses.

And also did code commit in [#135](https://github.com/SymphonyTeleca/OpenTouryo/pull/135/commits/65d063f936a8223aac1866a57098ebee967c6ca7#diff-0f21d148be8d2fb12238fde55fa85c35R925)

Please review and merge.
