### ISSUE TITLE
Change the encryption library used by the encryption wrapper from CAPI to CNG.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#212]
# Requirement
- マイクロソフト系技術情報 Wiki
  - [暗号化アルゴリズム](https://techinfoofmicrosofttech.osscons.jp/index.php?%E6%9A%97%E5%8F%B7%E5%8C%96%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0)
  - [.NETの署名・暗号化アルゴリズム](https://techinfoofmicrosofttech.osscons.jp/index.php?.NET%E3%81%AE%E7%BD%B2%E5%90%8D%E3%83%BB%E6%9A%97%E5%8F%B7%E5%8C%96%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0)
- [暗号・復号化 部品 - Open 棟梁 Wiki](https://opentouryo.osscons.jp/index.php?%E6%9A%97%E5%8F%B7%E3%83%BB%E5%BE%A9%E5%8F%B7%E5%8C%96%20%E9%83%A8%E5%93%81)

**Comment by daisukenishino2** [comment]
>- Using managed library takes precedence (Consider .NET Standard compliance)
>- Implemented with policy that CSP is used if there is no managed library.

https://github.com/OpenTouryoProject/OpenTouryo/pull/271/commits/f2061dea082c350869d2f225178971959c2b828b
- Since there is a part where AesCryptoServiceProvider is used instead of AesManaged.
- It is necessary to check the existence of similar problems.

**Comment by daisukenishino2** [comment]
It's easy after the situation has been seen. It is possible to support by adding an enumeration type of the CNG provider of the following encryption processing.

- MD5
- SHA1
- TripleDES
- RSA
- DSA
