### ISSUE TITLE
Rename the sample project for ASP.NET

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#233]
# Requirement
Most of the name of sample project contain the word that expresses architecture of the sample project. (e.g. MVC_Sample, SPA_Sample, UWP_Sample)

However, the sample project for ASP.NET is named *ProjectX_sample*. This name does not contain the architecture. So, user may not understand what is this a sample of.

How about renaming the sample project for ASP.NET? (e.g. ASPNET_Sample)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

- I will consider this requirement.
- This modification requires modification of the link source.
- It is necessary to find and fix the link source by [Google search](https://www.google.co.jp/search?q=ProjectX_Sample) etc.
