### ISSUE TITLE
Feature Request: Set menu page as start page

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#242]
# Requirement
Currently, the *start action* of Open Touryo sample web applications, that is, *ProjectX_sample*, *MVC_sample*, and *SPA_sample*, are set to *Current Page*. So, the page, that is selected in Visual Studio solution explorer, is shown in a browser.

When selecting the root of the project or the solution, the root of virtual directory is shown in a browser.
```txt
http://site-name/virtual-directory-name/
```

Here, because the default page is not set in Open Touryo sample web application, HTTP 403 error occurs.
![image](https://cloud.githubusercontent.com/assets/9585990/26087685/2326ac8c-3a2d-11e7-85ea-ba84298232b9.png)

It might be a good idea to set menu page, e.g. `Aspx/start/menu.aspx` in ProjectX_sample, to start page.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I think that the setting of the start page will be recorded to except the "*.sln" and "*. csproj" files.
Maybe, I think that it will be recorded to the "*.csproj.user" or "*. sou" files.

Alternatively, We can add "index.html" to the root.
This can lead this request to the menu by relative path.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

- Should users wait 10 seconds? I think 10 seconds are slightly long.
  - Is it necessary to show this *Index.html*?
  - It might be a good idea to jump to *menu.aspx* immediately.

    ```html
    <meta http-equiv="refresh" content="0;URL=/virtual-directory-name/Aspx/Start/menu.aspx">
    ```

- If it is necessary to show this *Index.html*, what do you think about the globalization of this *Index.html*?

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Change this Index.html as follows.
It could see the Index.html even if refresh is set to 0 second.

```XML
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta http-equiv="refresh" content="0;URL=/WebForms_Sample/Aspx/Start/menu.aspx">
    <title>menu画面</title>
    <script>
        // 最優先の言語だけ取得
        var language = (window.navigator.languages && window.navigator.languages[0]) ||
                    window.navigator.language ||
                    window.navigator.userLanguage ||
                    window.navigator.browserLanguage;

        //alert(language);
    </script>
</head>
<body>
    <script>
        if (language === "ja")
        {    
            document.write("自動的に menu 画面にジャンプします。");
        }
        else
        {
            document.write("Automatically jumps to the menu screen.");
        }
    </script>
    <br />
    <a href="/virtual-directory-name/Aspx/Start/menu.aspx">/WebForms_Sample/Aspx/Start/menu.aspx</a><br />
</body>
</html>
```
