### ISSUE TITLE
Add SSO processing by the ”OpenID Connect” to the template2.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#248]
# Requirement
Add SSO processing by the  "OpenID Connect"
  to the template by use a multi-purpose authentication site that is added soon.

#### WSClientWin_sample
- Resource Owner Password Credentials grant

#### SPA_Sample
- Add Implicit Grant Flow to get access_token on user agent.

#### ASPNETWebService
Implement JWT verification processing to the following method.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/ASPNETWebService/ASPNETWebService/
  - ServiceForFx.asmx
  - WCFHTTPSvcForFx.svc
  - Controllers/FxController
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WS_sample/ASPNETWebService/ASPNETWebService/
  - ServiceForSb.asmx (Individual)
  - Controllers/JsonController (Individual)

## see
#230, #232.

**Comment by daisukenishino2** [comment]
# Carry over
## Target
###  UWP_Sample
- Implicit Grant Flow ?
- Resource Owner Password Credentials grant ?
