### ISSUE TITLE
Where is "Authentication\OAuth2ProviderHelper.cs"

### ISSUE THREAD

**Issue by shamohai** [OpenTouryoProject/OpenTouryo#256]
**\root\programs\Frameworks\Infrastructure\Framework\Authentication\OAuth2ProviderHelper.cs' could not be found.

**Comment by daisukenishino** [comment]
@shamohai 

Some time ago,
the OAuth2ProviderHelper module was renamed to OAuth2AndOIDCClient.
I forgot to merge this into *_net47.csproj.
