### ISSUE TITLE
Refactoring and quality Improvement (2)

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#258]
# Requirement
These pointed out items have potential that will be refactored.

## Please correct the following defects.
- #### [No.1](#issuecomment-331066882).
- #### [No.2](#issuecomment-332108538).
>- #### [No.3](#issuecomment-370384418). fixed
>- #### [No.4](#issuecomment-422660379). fixed
>- #### [No.5](#issuecomment-423730580). fixed

**Comment by daisukenishino** [comment]
# The name written Ht which means HashTable.

## Pointing out
https://github.com/OpenTouryoProject/OpenTouryo/pull/253#discussion_r139857339
Is Ht an abbreviation for HashTable?
If so, since the type of return value is Dictionary, use Dic instead.

## Correspondence

**Comment by daisukenishino** [comment]
# Feedback from Multi-purpose authentication site

## /Controllers/ErrorController.cs
- https://github.com/OpenTouryoProject/MultiPurposeAuthSite/pull/46#discussion_r140943796
- https://github.com/OpenTouryoProject/MultiPurposeAuthSite/blob/develop/root/programs/MultiPurposeAuthSite/MultiPurposeAuthSite/Controllers/ErrorController.cs#L158

## /Infrastructure/Business/AsyncProcessingService/LayerD.cs 
- https://github.com/OpenTouryoProject/MultiPurposeAuthSite/pull/46#discussion_r140939206

**Comment by daisukenishino2** [comment]
# null check method in JavaScript 

ex: oauthimplicit.js

```JS
if (queryString == null) {
```
↓ ↓ ↓
```JS
if (!queryString) {
```

**Comment by daisukenishino2** [comment]
# There is a method with the async keyword that does not execute await.

## Pointing out
https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/76#discussion_r218651940

## Correspondence
Under consideration of the correspondence method.

**Comment by daisukenishino2** [comment]
# Typo

## ベーククラス ---> ベースクラス
https://github.com/OpenTouryoProject/MultiPurposeAuthSite/pull/85#discussion_r219421974
