### ISSUE TITLE
DPQuery_Tool generates invalid tag

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#261]
# Requirement
DPQuery_Tool generates `<DECMA></DECMA>` tag.

![image](https://user-images.githubusercontent.com/9585990/31160555-0ccc21b2-a90c-11e7-9b87-fcb562c65e2a.png)

However, when executing the above query, a runtime error occurs. Error message is "Invalid tags are included".
I think that `<DELCMA></DELCMA>` tag is correct, not `<DECMA></DECMA>` tag.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

It is as you have pointed out.

The `<DELCMA></DELCMA>` tag is mainly used for automatic generation,
and users have few opportunities to use directly.

So, I think that discovery of the problem was delayed.
