### ISSUE TITLE
Usage for the specific target framework is unclear.

### ISSUE THREAD

**Issue by yusukemaegawa** [OpenTouryoProject/OpenTouryo#265]
# Requirement
Usage for the specific target framework is unclear.

### In [Readme.md](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root)
- 3_Build_NuGet_net45.bat
Build the framework (Base class 1) to make NuGet package that targets .NET Framework 4.5.2.
- 3_Build_NuGet_net47.bat
Build the framework (Base class 1) to make NuGet package that targets .NET Framework 4.7.

---> How can we make NuGet package that targets *.NET Framework 4.6*? (In [Infrastructure](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure) folder, *Nuget_net45.sln* and *Nuget_net47.sln* solutions exist. But *Nuget.sln* or *Nuget_net46.sln* solution does not exist.)

### In [Infrastructure](https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure) folder
- AllComponent.sln solution contains the projects that target .NET Framework 4.6.

---> How can we customize this solution to target *.NET Framework 4.5.2* or *.NET Framework 4.7*? (i.e. For .NET Framework 4.7, is it necessary that we create new solution file, such as *AllComponent_net47.sln*?)

Please add the above to readme.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

> How can we make NuGet package that targets .NET Framework 4.6? (In Infrastructure folder, Nuget_net45.sln and Nuget_net47.sln solutions exist. But Nuget.sln or Nuget_net46.sln solution does not exist.)

Does this mean that you need to specify the procedure from build to package upload? Or does this mean that the existence of *.bat file targeting _net46_ is unclear? _3_Build_Framework.bat_ is a *.bat file for net 46.

> How can we customize this solution to target .NET Framework 4.5.2 or .NET Framework 4.7? (i.e. For .NET Framework 4.7, is it necessary that we create new solution file, such as AllComponent_net47.sln?)

All source files are commonized between all targetFramework by _conditional compilation_.

Therefore basically, you can use _AllComponent.sln_ to customize the source file, and you can commit the modification if build error has not been output when the customized source files are building with _3_Build_NuGet_net*.bat_.

see : https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root#build-program

**Comment by daisukenishino2** [comment]
@yusukemaegawa 

Although it had been done as below.
- The net46 package creation, used the existing bat.
- The net47 package creation, used new bat.
- The net452 package creation, used new bat.

As you can see in the list below,
- 3_Build_Framework_net45.bat
- 3_Build_Framework_net46.bat
- 3_Build_Framework_net47.bat

I decided to create net46.bat as new, and separate with existing batch.
