### ISSUE TITLE
Expand the JWT (JWS, JWK) creation class libraries.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#266]
# Requirement
Recently, in the problem domain of authentication, processing such as creation of JWS and JWK and verification of JWS using JWK have been required. Therefore, it is necessary to expand such a class libraries.

It is necessary to read some RFC related to JWT for this fixes.

**Comment by daisukenishino** [comment]
# Details

**Comment by daisukenishino** [comment]
# Reference
- JWS - マイクロソフト系技術情報 Wiki
https://techinfoofmicrosofttech.osscons.jp/index.php?JWS
- JWK - マイクロソフト系技術情報 Wiki
https://techinfoofmicrosofttech.osscons.jp/index.php?JWK
- JWTの生成と検証 - Open 棟梁 Wiki
https://opentouryo.osscons.jp/index.php?JWT%E3%81%AE%E7%94%9F%E6%88%90%E3%81%A8%E6%A4%9C%E8%A8%BC

**Comment by daisukenishino2** [comment]
### Backlog
- Key conversion class method of RSA.
- JWT assertion generation and verification library using XML key
