### ISSUE TITLE
Item transfer is troublesome.

### ISSUE THREAD

**Issue by daisukenishino2** [OpenTouryoProject/OpenTouryo#27]
# Sumally
### Item transfer is troublesome.
- Screen Item be set for transfer to parameter properties.
- Parameter properties be set for transfer to Dao properties.  
### The following is expected.
- Screen item can be set for transfer to Dao property, directly.
- Or, there is a library that is supported the item transfer.

**Comment by daisukenishino** [comment]
The following libraries may be available.
https://www.nuget.org/packages/AutoMapper/

**Comment by daisukenishino2** [comment]
- AutoMapper - マイクロソフト系技術情報 Wiki
https://techinfoofmicrosofttech.osscons.jp/index.php?AutoMapper

**Comment by daisukenishino** [comment]
Shoud be changed the MVC sample to use AutoMapper.

- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/CS/Samples/WebApp_sample/MVC_Sample/MVC_Sample/Models/DataSets
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/CS/Samples4NetCore/Backend/MVC_Sample/MVC_Sample/Models/ViewModels

**Comment by daisukenishino2** [comment]
AutoMapper.Data does not work well. I Consider support of Dapper.
