### ISSUE TITLE
It is necessary to clarify the process of creating and registering the NuGet package.

### ISSUE THREAD

**Issue by daisukenishino2** [OpenTouryoProject/OpenTouryo#272]
# Requirement
- It is necessary to clarify the process of creating and registering the NuGet package.
- Therefore, these explanations need to be described below.
  - /root/Readme.md
  - /root/Readme.ja.md

### Reference
- NuGetパッケージの作成手順 - Open 棟梁 Wiki
https://opentouryo.osscons.jp/index.php?NuGetパッケージの作成手順

**Comment by daisukenishino2** [comment]
@yusukemaegawa 

以下を、
- https://github.com/daisukenishino2/SupportOpenTouryopPJ/wiki/CreateNuGetPackage
- https://github.com/daisukenishino2/SupportOpenTouryopPJ/wiki/CreateNuGetPackage.ja

以下に組み込む形にしようと思いますが問題無いでしょうか？
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/README.md
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/Readme.ja.md

※ "NuGet パッケージの作成用"の所からリンクさせる。

**Comment by yusukemaegawa** [comment]
@daisukenishino2 

- Wiki があちこちに点在するのはよくありません。Wiki を新規作成するのであれば、[OpenTouryo リポジトリの Wiki](https://github.com/OpenTouryoProject/OpenTouryo/wiki) に作成してください。
- 誰向けの Wiki か、どういうときに必要になる Wiki かを書いてください。
  - Readme からたどってきた人はわかると思うが、いきなりこの Wiki を見た人でも分かるように。
- 今の手順では、現状の Open 棟梁の NuGet パッケージと同じものができるだけだと思うので、**カスタマイズ**の項目が必要では？
- 「NuGet パッケージの作成手順」では、一般的な NuGet パッケージの作成手順と読めてしまいます。「**Open 棟梁の** NuGet パッケージの作成手順」としたほうが良いと思います。

**Comment by daisukenishino** [comment]
@yusukemaegawa 
それでは、上記指定を反映しつつ、[OpenTouryo リポジトリの Wiki](https://github.com/OpenTouryoProject/OpenTouryo/wiki) に移行します。

**Comment by daisukenishino2** [comment]
@yusukemaegawa 

上記指定を反映しつつ、移行を行いました。
- https://github.com/OpenTouryoProject/OpenTouryo/wiki/HowToCreateOpenTouryoNuGetPackages
- https://github.com/OpenTouryoProject/OpenTouryo/wiki/HowToCreateOpenTouryoNuGetPackages.ja

カスタマイズの項目については、現時点では、特に無いと思います。

**Comment by yusukemaegawa** [comment]
@daisukenishino2 

- 「若しくは」→「または」
  - 文章がかたい
  - 常用漢字でない

**Comment by yusukemaegawa** [comment]
@daisukenishino2 

- Open棟梁のNuGetパッケージをNuGet登録する開発者
  - 「NuGet」という言葉が重複している
  - すでに Open 棟梁の NuGet パッケージがあるのに、なぜわざわざ「NuGet パッケージを登録したい」という動機が生まれるのか
    - 自分自身で Open 棟梁のプログラムをカスタマイズして、そのカスタマイズしたプログラムを NuGet パッケージ化して登録したい、ということなのでは？
    - [ここ](https://github.com/OpenTouryoProject/OpenTouryo/issues/272#issuecomment-419760903)で、カスタマイズの項目が必要なのでは、と言ったのはそのため

**Comment by yusukemaegawa** [comment]
@daisukenishino2 

- URL (https://github.com/...) で表記するのは、一番最初だけで良い
  - 実際の手順では、URL からではなく、ZIP 解凍したルートフォルダからの相対パスを扱うはず
  - 実際の手順に則し、2 つ目 (`C:\root` に配置するところ) からは、ルートフォルダからの相対パスとしたほうが良いのでは？

**Comment by yusukemaegawa** [comment]
@daisukenishino2 

- [パッケージのプッシュ †](https://github.com/OpenTouryoProject/OpenTouryo/wiki/HowToCreateOpenTouryoNuGetPackages.ja#%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%81%AE%E3%83%97%E3%83%83%E3%82%B7%E3%83%A5-)の "†" はゴミ？

**Comment by daisukenishino** [comment]
@yusukemaegawa 
- [コレ](#issuecomment-419809622)以外修正しました。
- [コレ](#issuecomment-419809622)を行う必要性は、[この辺の対応](https://github.com/OpenTouryoProject/OpenTouryo/pull/263)が必要、且つ心配なケースです。  
具体的には大規模プロジェクトで、迅速且つ柔軟性の高い対応が必要になるケースです。

**Comment by yusukemaegawa** [comment]
@daisukenishino2 

言わんとしていることが分かりません。もっと噛み砕いて説明してください。

**Comment by daisukenishino** [comment]
@yusukemaegawa 

　例えば、NuGetプライベート・リポジトリを使用すれば、コミュニティに対応できるリソースが無い場合、取り敢えず、NuGetプライベート・リポジトリで対応し、以後、NuGetプライベート・リポジトリで運用を続けるか、コミュニティにプルリクエストするか、選択的に対応可能です。

これは、[ブログ・ネタ](https://www.osscons.jp/dotNetDevelopmentInfrastructure/Blog/)にしても良いかも知れません。

**Comment by daisukenishino** [comment]
@yusukemaegawa 

　[例に挙げた過去事例](https://github.com/OpenTouryoProject/OpenTouryo/pull/263)では、緊急対応として、.NET 4.5.2対応版のリリースを急遽 行いました。このような対応をするコミュニティのリソースが無い場合、利用者側のプロジェクトが止まってしまう可能性があるので、そういうケースでは、一時的にでも、NuGetプライベート・リポジトリを運用するメリットがあると思います。

**Comment by yusukemaegawa** [comment]
@daisukenishino 

行間を読むと、こういうことですか？

1. 利用者が、Open 棟梁に不具合 or そのままでは動かず、プログラムの修正が必要になる箇所を発見する
1. その箇所を Issue に登録する
1. 修正を待っていると時間がかかるので、利用者が自ら Open 棟梁プログラムをダウンロードまたはフォークする
1. プログラムの修正を行う
1. その案件で利用できるように、パッケージ化、プライベートリポジトリへの登録を行う
1. Open 棟梁本体への Pull Request を行う

であれば、やはり、何かしらプログラムの修正は行うのではないですか？

今の手順では、ダウンロードしたものをそのままビルドする手順になっているので、今の Open 棟梁の NuGet パッケージとまったく同じものができ上がると思います。

```md
## プログラムの修正

必要に応じて、Open 棟梁のプログラムを修正する。
```

の一文だけでもあったほうが良いと思います。

**Comment by daisukenishino** [comment]
@yusukemaegawa 

　なるほど、ご指摘の通りですね。NuGetプライベート・リポジトリの利用は、ダウンロードしてきたNuGetパッケージをイントラ配布のために使用するだけでもOKですが、Open棟梁のNuGetパッケージ作成をわざわざ行う場合、（１）NuGet登録する開発者か、（２）NuGetプライベート・リポジトリの運用者の２択になりますね。そして後者の場合、プログラム修正がありますね。

**Comment by daisukenishino** [comment]
@yusukemaegawa 
以下、修正しました。
- https://github.com/OpenTouryoProject/OpenTouryo/wiki/HowToCreateOpenTouryoNuGetPackages#fix-of-the-program
- https://github.com/OpenTouryoProject/OpenTouryo/wiki/HowToCreateOpenTouryoNuGetPackages.ja#%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AE%E4%BF%AE%E6%AD%A3

**Comment by yusukemaegawa** [comment]
@daisukenishino 

- fix NuGet package target program of OpenTouryo. → fix the source code of the NuGet packages of Open Touryo.
- ところどころ、半角スペースが混入しているように思います。
  - 例
    - 3 _ Build_NuGet_net 45. Bat
  - 機械的に翻訳すると、このようなスペースが混入することがあります。

**Comment by daisukenishino2** [comment]
@yusukemaegawa 

　上記の指摘に対応して、以下のように`README.md`に組み込みましたが、
- https://github.com/OpenTouryoProject/OpenTouryo/commit/47f792177b64e92979dc825a475992ff37e23f8c
- https://github.com/OpenTouryoProject/OpenTouryo/commit/b644ace3d1c1e78e015cfa0147d17facaa57d050

　「[データプロバイダの入手、輸出手続き、使用許諾への添付について](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/Readme.ja.md#%E3%83%87%E3%83%BC%E3%82%BF%E3%83%97%E3%83%AD%E3%83%90%E3%82%A4%E3%83%80%E3%81%AE%E5%85%A5%E6%89%8B%E8%BC%B8%E5%87%BA%E6%89%8B%E7%B6%9A%E3%81%8D%E4%BD%BF%E7%94%A8%E8%A8%B1%E8%AB%BE%E3%81%B8%E3%81%AE%E6%B7%BB%E4%BB%98%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)」の部分、修正が必要かもしれません。データプロバイダに限らず、

（１）NuGetで取得可能なライブラリは同梱する必要がないので対象外にできる。
（２）同梱して輸出するライブラリの輸出手続き、使用許諾への添付が必要になる。

とした方が正確ではないか？と考えます。

**Comment by yusukemaegawa** [comment]
@daisukenishino2 

おそらく、この部分は GitHub に公開した当初からあった文章だと思います。

当時はデータプロバイダーだけだったかもしれませんが、今はさまざまな外部ライブラリを使っていると思います。

そのため、以下のようにしたほうが良いと思います。

- タイトルを、「データプロバイダー」ではなく、「Open 棟梁が利用している外部ライブラリ」とかに
- NuGet だけでなく、npm も対象とする

また、この修正は、本 Issue とは直接関係がないので、別 Issue に分けたほうが良いと思います。

**Comment by daisukenishino2** [comment]
@yusukemaegawa 

[上記の件](#issuecomment-421214117)、#306 に追加しました。
