### ISSUE TITLE
EntityTemplate is redundant.

### ISSUE THREAD

**Issue by daisukenishino2** [OpenTouryoProject/OpenTouryo#293]
# Requirement
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/files/tools/DGenTemplates/EntityTemplate.cs
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/files/tools/DGenTemplates/DaoTemplate.vb

Probably initially, I think that it was designed like this for the purpose of item transfer to auto-generated dao. However, given the purpose of generating ViewModel, this template is not appropriate. I think that the default template should be POCO format.

**Comment by daisukenishino** [comment]
This Entity is introduced a Nullable type to correspond to DBNull.
There is a need to  evaluate the affinity this Entity for ViewModel.

**Comment by daisukenishino2** [comment]
These fixes include additional fixes to #290 and #291.

**Comment by daisukenishino2** [comment]
These fixes include additional fixes to #290 and #291.
