### ISSUE TITLE
Add the .NET Core 3.0 project using Visual Studio 2019.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#327]
# Requirement
- There is need to use .NET Core 3.0 for execute ECDsaCng on Windows.
- A library using ECDsaCng is requested from MultiPurposeAuthSite.

# Timing
- The class library has already been verified to be compatible with .NET Core 3.0.
- When .NET Core SDK 3 will be changed from preview to RTM, then corresponds to it officially.
- Also, if correspond ASP.NET to netcoreapp3.0, VS2019 is required.
- Therefore, also wait for a change from preview to RTM about VS2019.

**Comment by daisukenishino2** [comment]
# Correspond ASP.NET to netstandard2.1

### Reference
- .NET Standardへの移行 - マイクロソフト系技術情報 Wiki
 &gt; 参考 > .NET Standard 2.0以降 > .NET Standard 2.1
https://techinfoofmicrosofttech.osscons.jp/index.php?.NET%20Standard%E3%81%B8%E3%81%AE%E7%A7%BB%E8%A1%8C#o2b600b3

**Comment by daisukenishino2** [comment]
# Correspond ASP.NET to netcoreapp3.0

```
NETSDK1079 .NET Core 3.0 以上をターゲットにする場合、Microsoft.AspNetCore.All パッケージはサポートされていません。 代わりに、Microsoft.AspNetCore.App への FrameworkReference を使用する必要があり、それは、Microsoft.NET.Sdk.Web によって暗黙的に含まれます。MVC_Sample C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets
```

```
System.InvalidOperationException: 'EndpointRoutingMiddleware matches endpoints setup by EndpointMiddleware and so must be added to the request execution pipeline before EndpointMiddleware. Please add EndpointRoutingMiddleware by calling 'IApplicationBuilder.UseRouting' inside the call to 'Configure(...)' in the application startup code.'
```


```
System.InvalidOperationException: 'Endpoint Routing does not support 'IApplicationBuilder.UseMvc(...)'. To use 'IApplicationBuilder.UseMvc' set 'MvcOptions.EnableEndpointRouting = false' inside 'ConfigureServices(...).'
```
### Reference
- ASP.NET Coreへの移行 - マイクロソフト系技術情報 Wiki
 &gt; 参考 > .NET Core 2.0以降 > .NET Core 3.0
https://techinfoofmicrosofttech.osscons.jp/index.php?ASP.NET%20Core%E3%81%B8%E3%81%AE%E7%A7%BB%E8%A1%8C#mcd69cf3
