### ISSUE TITLE
Support to Windows Forms/WPF by “Windows Desktop Packs” on NET Core 3.0.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#328]
# Requirement
- Windows Desktop Packsへの移行 - マイクロソフト系技術情報 Wiki
https://techinfoofmicrosofttech.osscons.jp/index.php?Windows%20Desktop%20Packs%E3%81%B8%E3%81%AE%E7%A7%BB%E8%A1%8C

**Comment by daisukenishino2** [comment]
# Research
Check binary serialization compatibility under .NET Framework, .NET Core, Windows, Linux, etc.
