### ISSUE TITLE
Investigate and fix problems derived from updating to .NET Core 2.1 - 2.2.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#329]
# Requirement
Observed one problem is collision of AddHttpContextAccessor helper extension method.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/CS/Samples4NetCore/Backend/MVC_Sample/MVC_Sample/Startup.cs#L232

**Comment by daisukenishino2** [comment]
# Test method
- *.csproj
  - Upgrade TargetFramework to 2.2.
  - Upgrade  Microsoft.AspNetCore.All to 2.2.n.
- Install .NET Core SDK 2.2.n
- Confirm the [MyHttpContext](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/CS/Frameworks/Infrastructure/Framework/StdMigration/MyHttpContext.cs) works well.

### Doubt
It is unknown how to get the HTTPContext in 2.1 or later.
Is the ASP.NET DI applicable to not only controller but also library ?

### Reference
- When ASP.NET Core App (2.1.x or 2.2) fails with:
HTTP Error 502.5 - Process Failure · Issue #8554 · aspnet/Docs
https://github.com/aspnet/Docs/issues/8554
- Microsoft Docs
  - ASP.NET Core で HttpContext にアクセスする | 
https://docs.microsoft.com/ja-jp/aspnet/core/fundamentals/http-context
  - ASP.NET Core での依存関係の挿入
https://docs.microsoft.com/ja-jp/aspnet/core/fundamentals/dependency-injection
