### ISSUE TITLE
Performance improvement of automatically generated Dao.

### ISSUE THREAD

**Issue by daisukenishino2** [OpenTouryoProject/OpenTouryo#332]
# Requirement
I don't want to make the project manager worried too much because there were no cases with OLTP causing performance issues due to OpneTouryo. However, certainly, in large-scale projects, I think that we have to spend management man-hour to avoid risks.

Therefore, I think that to modify the template for the automatically generated Dao so that the following techniques can also be applied with the automatically generated Dao. https://opentouryo.osscons.jp/index.php?%E3%83%90%E3%83%83%E3%83%81%E5%87%A6%E7%90%86%E6%96%B9%E5%BC%8F#y92d7822

**Comment by daisukenishino** [comment]
# In particular,
Cache the SQL processed XML in ConcurrentDictionary<TKey, TValue>. And, use [Class name].[Method name] for Key.

When using DaoX in the class.method concerned, cached SQL can be used if the parameter set does not change. Cached SQL can not be used the case of the parameter set will be changed for dynamic condition search, etc.

To use or not use the cache, it is possible to switch in the constructor.

**Comment by daisukenishino2** [comment]
# How to use
If you set cacheId as below, queries will be cached. Information that can uniquely identify the execution location such as GUID and stack trace can be used as cacheId.

```CS
// 自動生成Daoを生成
DaoShippers genDao = new DaoShippers(this.GetDam());
```

 ↓ ↓ ↓

```CS
// 自動生成Daoを生成
// https://www.guidgenerator.com/online-guid-generator.aspx
DaoShippers genDao = new DaoShippers(this.GetDam(), "f54d4d7bd5c8441187ec6939c4da7303");
```
