### ISSUE TITLE
1_DeleteDir.bat file does not work that is included the Zip file of downloaded.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#333]
# Requirement
`1_DeleteDir.bat` included in downloaded Zip has been confirmed to become unexecutable even if it is unblocked after unzipping. So, if you try to move from the CS version build to the VB version build, the CS version rebuild will fail. Therfore, If you build only the VB version, there is no problem.

### Investigation result
there is possibility that is due to the line feed code.

If you download Zip, the line feed code will be LF. If the line feed code is CRLF, it works well.

Git has a property called `autocrlf`, which defaults to true. When committed to the repository, CRLF becomes LF, and when checked out, LF is converted to CRLF.

Guessing, if you use Git commands such as `git clone` and `git checkout` to get the contents of the repository, the line feed code will be returned to CRLF. so it will execute normally, but if you download Zip, the repository will not use Git commands, but the repository The contents of will be converted to Zip as it is and downloaded, and the line feed code will remain as LF and I think that an execution error will occur. The execution of other batch files may not have affected the line feed code differences, but may affect `1_DeleteDir.bat`.

### Reference
- GitHub で Download ZIP した時に改行コードが
LF になってしまう件(原因は core.autocrlf) - stamemo
http://stakiran.hatenablog.com/entry/2018/11/14/193053
- .gitattributesによる改行コードの変換設定 - 理系学生日記
https://kiririmode.hatenablog.jp/entry/20170416/1492300735
- Git からチェックアウト時に CRLF の改行コードで取得する | ハックノート
https://hacknote.jp/archives/8582/
- .gitattributes で Git LFS の適用をディレクトリごとに変更する
https://mseeeen.msen.jp/override-each-directorys-git-attributes/
- oliversalzburg/.gitattributes
https://gist.github.com/oliversalzburg/ad5dc0a88241e6dae08e9382a65a93d1

**Comment by daisukenishino2** [comment]
Added .gitattributes file as below.

```
# Windows batch files want to use CRLF by default.
*.bat text eol=crlf

# Visual Studio files want to use CRLF by default.
```
