### ISSUE TITLE
DigitalSignECDsaX509.cs X509Certificate.GetECDsaPrivateKey()  windows server 2019 error

### ISSUE THREAD

**Issue by shamohai** [OpenTouryoProject/OpenTouryo#361]
win7 DigitalSignECDsaX509.cs X509Certificate.GetECDsaPrivateKey()   is  success.

But windows 2019 error:
windows log:
Encryption parameters:
Provider name: Microsoft Software Key Storage Provider
Algorithm name: UNKNOWN
Key name: {DEA15931-C8E1-4628-89A3-4BD3658A718B}
Key type: User key.

**Comment by shamohai** [comment]
I found a solution:
[https://www.cnblogs.com/gougou1981/p/11453242.html](url)
![QQ图片20200502223703](https://user-images.githubusercontent.com/7419781/80867216-8a99c280-8cc5-11ea-9637-cc029fe3421b.png)


Simplified Chinese, need to set iis application pool
The first one is effective,
The second option is invalid.

**Comment by shamohai** [comment]
[https://github.com/dotnet/runtime/issues/25143](url)

The error message is similar to this link

**Comment by daisukenishino2** [comment]
@shamohai 

Thank you for your report.
