### ISSUE TITLE
Specifying the WCF options in communication control function.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#40]
# Explanation

If you want to specify the option in the WCF communication control function, In the current implementation, it is possible only in the section of config file.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/web.config#L279

Please modify to possible specify WCF options settings such as proxy and authentication by using the communication control function API.

At the moment, it is only possible in ASP.NET Web service.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Transmission/CallController.cs#L416

**Comment by kishoreandukuri** [comment]
HODC has completed testing using proxy as per your comments.

**Comment by daisukenishino** [comment]
Roger that. I have removed the test task from the task list.
