### ISSUE TITLE
"Portable Class Library" support

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#49]
I want to merge the following two libraries to "Portable Class Library". 

https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2012/programs/C%23/Frameworks
 - Silverlight 
 - WinStore 
 
This merge task will be use the VS2010 "Portable Class Library".
In the beginning, Investigate that the merge is possible or impossible. 
Please merge to "Portable Class Library", if possible.

**Comment by SandeepNayak077** [comment]
HODC has created folder structure for this task is as shown below
     •  PortableClassLibrary
           o  PCLBusiness
           o  PCLFramework
           o  PCLPublic

If the above folder structure is ok, then the above folder structure will be placed in the following location 

Location:  ..\OpenTouryo\root\programs\C#\Frameworks\

please let us know

**Comment by daisukenishino** [comment]
The above structure is the same as my idea.

After this correspondence has been completed, I will ask you to work to change the reference from WSClientSL_samples to PortableClassLibrary.
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples

Change of the following reference settings HISOL corresponds to after the merge work in charge of HISOL.
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2012/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientSL_samples
- https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS201X/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples
- .etc

**Comment by daisukenishino** [comment]
Please send me pullrequest.
