### ISSUE TITLE
Build fails because the path is different depending on the environment.

### ISSUE THREAD

**Issue by daisukenishino2** [OpenTouryoProject/OpenTouryo#55]
The following is considering how to respond.
- I am using the MSbuild.exe in express edition.  
And, I am using the devenv.com at edition other than express edition.  
I wanted to unify the MSBuild.exe. But, I am using devenv.exe for the following reasons.  
  - MSbuild.exe will be spent many time to corresponding that often can't build by some errors.
- If possible, I want to select the path automatically.  
But, I think it's difficult on the environment that contains multiple visual studio version and Edition.
- Environment difference of x86,64 can be overcome by using the "%VS1x0COMNTOOLS%" environment variable for selection of devenv.exe build tool.  
```
VS1x0COMNTOOLS=C:\Program Files\Microsoft Visual Studio 1x.0\Common7\Tools\
VS1x0COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio 1x.0\Common7\Tools\
```

**Comment by daisukenishino** [comment]
Excellent correspondence way could not be found.
