### ISSUE TITLE
How to set commandtimeout value for each query of Automatic Generation Dao and CmnDao

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#57]
# I want to set commandtimeout value for each query.
Please set the commandtimeout value taken out of the Command object before execution of Command.

- (((DamSqlSvr)this.GetDam()).DamSqlCommand).CommandTimeout = xxx;
- DirectCast(GetDam(), DamSqlSvr).DamSqlCommand.CommandTimeout = xxx

However, the above is possible only in your own Dao,

- CmnDao this process can not be implemented.  
If necessary to modify the implementation of CmnDao as follows.
- Similarly, the Automatic Generation Dao this process can not be implemented.  
If necessary to modify the implementation of Automatic Generation Dao template as follows.

Implement the process of setting the CommandTimeout property after the "This.SetSQL ();" statement in ExecXXXX method.

**Comment by daisukenishino** [comment]
There is a problem with the implementation of DGenTemplates/DaoTemplate.
Please implemented in the same manner as CmnDao.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Db/BaseDam.cs#L246
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Dao/CmnDao.cs#L293

CmnDao.SetCommandTimeout method is not required.
Use BaseDam.SetCommandTimeout method.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/files/tools/DGenTemplates/DaoTemplate.cs#L81

**Comment by kishoreandukuri** [comment]
>Use BaseDam.SetCommandTimeout method

HODC

**Comment by daisukenishino** [comment]
I'm sorry, I was wrong. Correctly as follows.

The following implementation has a problem that use DamSqlSvr type.
 Do not function properly when using the other data providers in this implementation.

- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Dao/CmnDao.cs#L428
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/files/tools/DGenTemplates/DaoTemplate.cs#L81

There is a possibility that you can support multiple data provider using the IDbCommand in CmnDao.SetCommandTimeout and DaoTemplate.SetCommandTimeout.

**Comment by daisukenishino** [comment]
IDbCommand has a CommandTimeout property. Therefore, I think that it can be implemented as follows.

(((IDbCommand)this.GetDam()).DamSqlCommand).CommandTimeout = this._commandTimeout;

- IDbCommand.CommandTimeout プロパティ (System.Data)  
https://msdn.microsoft.com/ja-jp/library/system.data.idbcommand.commandtimeout.aspx

**Comment by daisukenishino** [comment]
I was wrong again.
DamXXXCommand property is a property of the specific type at the each data provider.
Therefore, the above implementation is still have a problem.

So I think that there is a way to override to return the command object in each DamClass
 by adding a virtual property that returns a IDbCommand to BaseDam.

About each DamClass.
- DamSqlSvr  
- DamOraClient
- DamODBC
- DamOLEDB
- DamOraOdp
- DamMySQL
- DamPstGrS
- DamDB2
- DamHiRDB

About signature of the virtual function.
```C#
public IDbCommand DamIDbCommand
{
  get
  {
    return this._cmd;
  }
}
```

**Comment by kishoreandukuri** [comment]
HODC is requesting you to share the specification and requirement that
needs to be done. So that HODC will analyse and share you the solution.

Thanks,

**Comment by daisukenishino** [comment]
[#issuecomment-85989159] (https://github.com/OpenTouryoProject/OpenTouryo/issues/57#issuecomment-85989159)

The above is specification by my idea.
- Please Analyze whether there is a problem in the specification.
- And, Please share with us the specification that has been verified by you.

I instructs the start of implementation to you if there is no problem.

**Comment by daisukenishino2** [comment]
there is a need to modify the following modules.
 - CmnDao.cs and .vb
 - DaoTemplate.cs and .vb

Also please fixes for the following modules.
 - DamOraOdp
 - DamMySQL
 - DamPstGrS
 - DamDB2
 - DamHiRDB

Do not Delete the following methods to maintain backward compatibility.
 - public OdbcCommand DamOdbcCommand
 - public OleDbCommand DamOleDbCommand
 - public OracleCommand DamOracleCommand
 - public SqlCommand DamSqlCommand

**Comment by kishoreandukuri** [comment]
Hey,

I just signed the petition ". @narendramodi @PMOIndia @imrankhanPTI @United
Nations: Release of Indian Wing Commander Abhinandan with honour from
Pakistan" and wanted to see if you could help by adding your name.

Our goal is to reach 50,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/wgLhcfgdvz

Thanks!
Kishore
