### ISSUE TITLE
Development of AsyncProcessingService function

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#58]
# Requirement
Windows Service that achieve asynchronous processing by used DBMS as a queue.

## Windows Service
C# - How to Create a Windows Service - Part 1-3 - YouTube
http://www.youtube.com/watch?v=uM9o8GsO_u4

## Specification
I have uploaded to the following URL.
https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/develop/documents/1_User_Guide/en/AsyncProcessingService/AsyncProcessingService_EN.xlsx
Note: Refer to the develop branch.

## User
This function will be used in the Copy tool of Azure Storage.
The following URL is Copy tool of Azure Storage of specifications.
https://github.com/OpenTouryoProject/CloudOS/blob/develop/documents/AzureStorageBlobDataCopyWebsite/Specification_EN.xlsx

**Comment by daisukenishino** [comment]
# In development
Following pullrequest is accepted in during development.
- https://github.com/OpenTouryoProject/OpenTouryo/pull/67
- https://github.com/OpenTouryoProject/OpenTouryo/pull/71
- https://github.com/OpenTouryoProject/OpenTouryo/pull/79

**Comment by daisukenishino2** [comment]
# In response to the problem.
I have added a prototype model to the following URL.
https://github.com/OpenTouryoProject/SampleProgram/tree/master/PrototypeModel/AsyncProcessingService

I forgot to push the latest version before go home yesterday.
I will push the latest prototype model to tomorrow.

**Comment by daisukenishino** [comment]
I have to push the latest version of "prototype model". Please confirm.

**Comment by daisukenishino** [comment]
# How to wait
To the method of waiting, there are two method.
- Spin (Implement in a loop and sleep.)
- Signal (Sends a signal to the thread by using kernel object.)

## Spin method
In Spin method, wait for a change of state by the following way.
Check the such as flag at a loop inside, and to select the next action from below.
- Break the loop.
- after sleep, continue to loop.

## Signal method
Use the kernel object called "Thread synchronization tool kit",
 such as event, mutex, semaphore, waitable timer objects.
- Thread waits by calling the wait method.
- Kernel object to release the wait of Thread by sending a Signal to Thread.

# In the asynchronous processing service.
Can get the workerThreads variable as follows.
```C#
ThreadPool.GetAvailableThreads(out workerThreads, out completionPortThreads);
```
Therefore, to monitor the status change of this variable by selecting the spin method.

**Comment by kishoreandukuri** [comment]
Yes Nishino-san, we have implemented this as per prototype shared by you

**Comment by kishoreandukuri** [comment]
Shall we log exceptions in try catch block using 'LogIF.ErrorLog("OPERATION", ex.Message);'?

Please let us know.

**Comment by daisukenishino** [comment]
# About Log
In order to debug the state of the Thread of asynchronous processing service, and place the following info log output to the required site.
```C#
"LogIF.InfoLog("ASYNC-SERVICE", ex.Message);".
```
If an exception occurs, and outputs the following log in the catch block of try-catch.
```C#
"LogIF.ErrorLog("ASYNC-SERVICE", ex.Message);".
```
## Please create a new config file.
SampleLogConfAsyncProcessingService.xml

## Please define as follows.
Set the MaxSizeRollBackups parameters as number of log files does not increase.
```XML
<!-- Rolling log file output for appender -->
<appender name="ASYNC-SERVICE" type="log4net.Appender.RollingFileAppender">
  <param name="File" value="・・・\ASYNC-SERVICE" />
  <!-- setting of rolling -->
  <param name="StaticLogFileName" value="true" />
  <param name="RollingStyle" value="size" />
  <param name="MaximumFileSize" value="10MB" />
  <param name="MaxSizeRollBackups" value="2" />
  <param name="CountDirection" value="-1" />
  <!-- Writing settings (when adding or overwritten, output encoding) -->
  <param name="AppendToFile" value="true" />
  <encoding value="utf-8" />
  <!-- Message Format -->
  <layout type="log4net.Layout.PatternLayout">
    <param name="ConversionPattern" value="- (omitted) -" />
  </layout>
  <!-- Setting of filters (range) -->
  <filter type="log4net.Filter.LevelRangeFilter">
    <levelMin value="DEBUG" />
    <levelMax value="FATAL" />
  </filter>
</appender>
```
### For more information,
See "1.3　log4net ---> 1.3.4 Option Settings" section of the following Document.
https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/master/documents/1_User_Guide/en/2_User_Guide(Leaders)_EN.doc

**Comment by kishoreandukuri** [comment]
shall we put below code in catch block?
 asyncParam.UserId = asyncParamValue.UserId;
                            asyncParam.StatusId = (int)AsyncProcessingServiceParameterValue.AsyncStatus.End;
                            asyncParam.NumberOfRetries += 1;
                            LayerB myBusiness = new LayerB();

                            DbEnum.IsolationLevelEnum iso = DbEnum.IsolationLevelEnum.DefaultTransaction;

                            asyncReturnValue = (AsyncProcessingServiceReturnValue)myBusiness.DoBusinessLogic((AsyncProcessingServiceParameterValue)asyncParameterValue, iso);

Please let us know.

**Comment by daisukenishino** [comment]
# About Log (2)
I think that the following three of the try-catch block is required.

## asynchronous processing
try-catch block will catch the exception that occurred on the asynchronous processing.
The following Region is enclosed in try-catch.
```C#
asyncReturnValue = (AsyncProcessingServiceReturnValue)myBusiness.DoBusinessLogic((AsyncProcessingServiceParameterValue)asyncParameterValue, iso);
```
And, update the status and progress rate of the state management table.

## Main thread and worker thread.
### main thread
Catch the exception that occurred on the main thread. And, the problem is output to the error log.
Do not stop the main thread of the infinite loop even if an exception occurs.
### worker thread
Catch the exception that occurred in the excepting part of the asynchronous processing on the worker thread. And, the problem is output to the error log.

**Comment by daisukenishino** [comment]
# Change of location of the [ *.cs ] file
## Target files
- /AsyncProcessingServiceParameterValue.cs
- /AsyncProcessingServiceReturnValue.cs
- /LayerB.cs
- /LayerD.cs

Change the location of the above files.

## Location
Change
- to "root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/"
 - from "root/programs/C#/Frameworks/Infrastructure/Framework/AsyncProcessingService/".

## The reason
Circular reference occurs.

**Comment by daisukenishino** [comment]
# Changes about SQL file's location.
## SQL file location
"root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/"

## How to add SQL file
- Add as "linked file" from [Business project](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Business.csproj) as a [linked file](http://support.microsoft.com/en-us/kb/306234).
- SQL file will be sett ["Embedded Resource" to "build action" property](https://msdn.microsoft.com/en-us/library/0c6xyb66.aspx).

## How to load the SQL
Business.dll that is output from the Business project is not the entry assembly.
Therefore, you can load the SQL using the [EmbeddedResourceLoader.LoadAsString](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/IO/EmbeddedResourceLoader.cs#L197) method,
And to set the SQL using the [Dao.SetSqlByCommand](https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Dao/BaseDao.cs#L134) method.

**Comment by SandeepNayak077** [comment]
HODC understanding:

The Business project (Business.dll) must include the following files

"root/programs/C#/Frameworks/Infrastructure/Business/AsyncProcessingService/"
- /AsyncProcessingServiceParameterValue.cs
- /AsyncProcessingServiceReturnValue.cs
- /LayerB.cs
- /LayerD.cs
- /*.sql (Embedded SQL query files related to AsyncProcessingService)

HODC question:
Does '/*.sql' files must be linked from the location '..\root\files\resource\Sql\sqlserver\AsyncProcessingService' ?
Or
Does '/*.sql' files must not be used as linked files?

Please confirm

**Comment by daisukenishino** [comment]
# CR (Change request)
## Monitor the exception information in the state management table.
Write exception information to the above-mentioned management table.

Please check the following.
[specification of asynchronous processing service](https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/develop/documents/1_User_Guide/en/AsyncProcessingService/AsyncProcessingService_EN.xlsx).

# Bug report
## Service stop processing of AsyncProcessingService will not complete.
Steps to Reproduce
- Start the asynchronous processing service.
- Do nothing (Do not register the asynchronous processing)
- Stop the asynchronous processing service.

I do not know why not complete in the code of the current OnStop events.
Please debugging the processing of OnStop event.
I also knew that Onstop event is not end before all WorkerThreads in ThreadPool is completed.

Please check the following.
[Sample program of asynchronous processing service](https://github.com/OpenTouryoProject/SampleProgram/commit/4f25dbe49b5316c99a538dcb280536340d7f126c)
