### ISSUE TITLE
Problem of Table Maintenance screen automatic generation.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#63]
[TableName]ConditionalSearch.aspx and [TableName]SearchAndUpdate.aspx
---
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/files/tools/DGenTemplates

TextBox in GridView is not WebCustomTextBox.
Please correct the template.
```XML
<asp:TemplateField SortExpression="ProductID">
  <ItemTemplate>
    <asp:TextBox ReadOnly="true" BackColor="lightgray" ID="txtProductID" runat="server" Text='<%# Bind("ProductID") %>'></asp:TextBox>
  </ItemTemplate>
</asp:TemplateField>
<asp:TemplateField SortExpression="ProductName">
  <ItemTemplate>
    <asp:TextBox ReadOnly="true" ID="txtProductName" runat="server" Text='<%# Bind("ProductName") %>'></asp:TextBox>
  </ItemTemplate>
</asp:TemplateField>
```

**Comment by daisukenishino2** [comment]
I ask to HODC.
Does this issue is complete by the following pull request ?
https://github.com/OpenTouryoProject/OpenTouryo/pull/81
I think this issue has been completed. Please let me know.

**Comment by daisukenishino** [comment]
TableMaintenance was confirmed to operate properly by the [pullrequest#81] (https://github.com/OpenTouryoProject/OpenTouryo/pull/81).
- Therefore, I will close this Issue.
- You can see the [evidence] (https://github.com/OpenTouryoProject/Imagefiles/tree/master/OpenTouryo/Evidence/Tools/2015-04-02_TableMaintenance).
