### ISSUE TITLE
Satellite assembly of "ja" and "ja-JP" culture is present.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#64]
e.g. :
- \root\programs\C#\Frameworks\Tools\DaoGen_Tool\bin\Debug\ja
- \root\programs\C#\Frameworks\Tools\DaoGen_Tool\bin\Debug\ja-JP

Unify "\root\programs\C#\Frameworks\Tools\" 's culture of resource files to "ja".

**Comment by daisukenishino** [comment]
Only lineage files of ExceptionMessageResource.resx have used "ja" locale.
Therefore, I think that it is good to be unified to "ja-Jp" locale.

**Comment by supragyan** [comment]
HODC has checked but not able to find ExceptionMessageResource.resx project location.
Please confirm

**Comment by daisukenishino** [comment]
It exists in the following locations.
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Resources
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/Resources
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Resources

**Comment by daisukenishino** [comment]
Sorry, Also I had add the following locations.
- https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/VB/Frameworks/Infrastructure/Business/Resources
