### ISSUE TITLE
Problem of Data Maintenance screen automatic generation.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#66]
# The following test case has not been described in the tutorial.
- Time stamp  
Optimism exclusive function using a timestamp column.
- Relevant check and automatic numbering processing  
Implementation of the relevant check and automatic numbering processing.
  - This tool correspond manually numbering and automatic numbering.
  - Method of automatic numbering is different for each DBMS.  
There are two major method those are "Identity" and "Sequence".

**Comment by daisukenishino** [comment]
This function is being evaluated, after the evaluation, I will clarify the specification. And, I will again present the specification to HODC.

**Comment by SandeepNayak077** [comment]
> SQL other than SELECT/JION
> Columns that do not conform to the naming rules for update by this function.

Should above test cases run using Select-Join support Table Maintainence screens? 
or
Using Normal Table Maintainence screens?
Please confirm.

**Comment by daisukenishino** [comment]
## About the features
"Data Maintenance screen automatic generation" function is different from the "Table Maintenance screen automatic generation" function.
- "Table Maintenance screen automatic generation" function to use the DDL (DBMS Metadata) as input information.
- "Data Maintenance screen automatic generation" function is to use the SELECT statement (free SQL) as input information.

## About the test case
I hope that the following SELECT statement (free SQL) will be tested.
- The number of  selected table.
  - In the case of 1 table is selected
  - In the case of 2 table is selected (joined)
- Naming rules of column
  - If the column is follow the naming rules, the column is updated.
  - If the column does not follow the naming rules, the column is not updated.

**Comment by SandeepNayak077** [comment]
HODC understood that 'free SQL' means 'dynamic queries written in .xml' files
For example:
    •	Dao[TableName]_D2_Select.xml (In the case of 1 table is selected)
    •	Dao[TableA]_[TableB]_JOIN_S2_Select.xml (In the case of 2 table is selected (joined))

Please confirm our understanding

**Comment by daisukenishino** [comment]
Your recognition correct.
But, I think that I want to increase the accuracy more,
Please write an example of SQL that is described in two XML at here.

**Comment by SandeepNayak077** [comment]
Thank you for the response.
HODC will write an proper example of SQL and confirm the test cases on the two XML that the XML queries should follow the naming rules as [TableName.ColumnName] at the column level.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

see : https://github.com/OpenTouryoProject/OpenTouryoDocuments/issues/10
