### ISSUE TITLE
Enhancement of general-purpose DTO.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#68]
# Enhancement
## Refactoring

- Code that convert to a string from primitive type is duplicated.  
  - https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTables.cs#L191
  - https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTables.cs#L289

- Also, Code that convert to a primitive type from string is duplicated.
  - https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTables.cs#L422
  - https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTables.cs#L565

I want to move these codes to CustomMarshaler class
 as "StringFromPrimitivetype" and "PrimitivetypeFromString" method.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Util/CustomMarshaler.cs

## Support of SavejqGridJson method
- Support of JSON format corresponding to jqGrid. This method is implemented in DTTable class.
  - DTTable  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTable.cs
  - jqgridwiki - Data Manipulation - JSON String  
http://www.trirand.com/jqgridwiki/doku.php?id=wiki:retrieving_data#json_string

- And, I want to add the sample code below.  
  - https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Aspx/testFxLayerP/table

- Please reference the following sample.
  - https://github.com/OpenTouryoProject/SampleProgram/tree/master/ASPNET/WebForm/jqGridandWCF

- I want to achieve server side paging by a combination of ProductsTableAdapter.cs.
  - https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/App_Code/sample/3TierTableAdapter/ProductsTableAdapter.cs

**Comment by daisukenishino** [comment]
# Additional information about above "sample code".
When WCF output string by JSON serialization of Bean (POCO), then HTTP of Response.Body is enclosed by "double quotes". In this case, it is need that call "JSON.parse()"  to convert JSON object in javascript side. As much as possible, I want you to explore ways that WCF's output string are not granted "double quotes".

**Comment by supragyan** [comment]
Do we need to change wcf code as above .Please confirm

**Comment by daisukenishino** [comment]
# Additional information about above "server side paging" and "SavejqGridJson method".
- You need to get the data table that contains the result set that is paging by calling the existing ProductsTableAdapter.cs on the WebAPI module.
- And, to get the JSON string by specifying the data table to the argument of SavejqGridJson method.
- Enumerate below the argument of SavejqGridJson method.
  - datatable  
contains the result set that is paging.
  - string page  
The number of the current page.
  - int total
Total number of pages.
  - int records  
Total number of records for the query.

**Comment by yusukemaegawa** [comment]
# Additional information.

## The realization method of "server side paging" using "ProductsTableAdapter" class.
  For example, If the number of rows per page is 30, you need to acquire first 30 records (from first records to 30th record), using "ProductsTableAdapter" class.
    And, you need to convert those acquired data to JSON data.
    And, you need to return "converted JSON data" to view.
    And, you need to display "returned JSON data" to jqGrid.
  If user request to display second page, you need to acquire next 30 records (from 31th record to 60th record), using "ProductsTableAdapter" class again.
    (The same hereinafter.)

Original sample indicated "the basic usage of jqGrid" and "the method to return JSON data from WCF service".
Therefore, in original sample, server side paging has not been realized by "ProductsTableAdapter" class.
Therefore, you need to realize server side paging with above method.

**Comment by supragyan** [comment]
Dear Nishino-San,
>>And, you need to return "converted JSON data" to view.
HODC wants to confirm:
Here view means what we did (converted JSON data to CreateTextResponse format to display in JQGrid) or anything else to do?
Please confirm.

**Comment by daisukenishino** [comment]
"view" means "aspx file".
In this sample, "view" is "testJQGridJson.aspx".
