### ISSUE TITLE
Creating a AsyncProcessingService setup procedures

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#77]
# Requirement
I request to create a "readme.md" that is written AsyncProcessingService setup procedures for check the operation by using the sample program to you. Please create "readme.md" at following locations.
https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/ServiceInterface/AsyncProcessingService

**Comment by daisukenishino** [comment]
Content

- Build and setup(install) and configuration of AsyncProcessingService.
- Construction and configuration of database table.
- Develop and deploy of asynchronous processing DLL.
- Registration and execution and confirmation the asynchronous task.

**Comment by kishoreandukuri** [comment]
Shall we start creating this document now?

Please let us know.

Thanks

**Comment by daisukenishino2** [comment]
This task should be started after the completion of the copy tool.

**Comment by daisukenishino** [comment]
I want to change the schedule of this task.
Development support of HISOL has become required, when HODC performing the development of asynchronous processing services.
Therefore, you must be prepared in parallel operation verification procedure of asynchronous processing service from now.

**Comment by daisukenishino** [comment]
# Change of schedule
If a problem occurs in this development, I will recover the progress by our participation.
Therefore, I want to request that you create in parallel with the development this procedure manual for test and debug.

**Comment by daisukenishino** [comment]
We have updated the [specifications](
https://github.com/OpenTouryoProject/OpenTouryoDocuments/blob/develop/documents/1_User_Guide/en/AsyncProcessingService/AsyncProcessingService_EN.xlsx). Please check the writing in red.

**Comment by daisukenishino** [comment]
Close it since received.
We will upload to the document repository, after the brush up.
