### ISSUE TITLE
Problem of "suppress submit by pressing enter key."

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#78]
# Problem of "suppress submit by pressing enter key."
## Problem of Current implementation.
Current implementation is suppressed to submit by pressing enter key. 
There is a requirement to allow submit by pressing the enter key by explicitly attributes.

## Corresponding methods
I think following implementation can cope with it.

- "cansubmitbyenter" attribute of "input type="text"" that has been permitted submit processing by pressing the enter key will be specified "true".
```HTML
<input type="text" size="10" cansubmitbyenter="true">
```

- "input type="text"" that is specified "true" to "cansubmitbyenter" attribute can submit processing by pressing the enter key.
  - [ie_key_event.js - Line236] (https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/ie_key_event.js#L236)

```JS
if ((event.keyCode == 13) && !(event.srcElement.type == "submit" || event.srcElement.type == "textarea")) { 
  // enterの場合 (submitボタンやtextarea領域以外)
  if (event.srcElement.cansubmitbyenter == null || event.srcElement.cansubmitbyenter == undefined) {
    // cansubmitbyenter属性が定義されていない場合、enter不許可
    return false; 
  }
  else {
    // cansubmitbyenter属性が定義されている場合
    if (event.srcElement.cansubmitbyenter == "true") {
      // cansubmitbyenter属性がtrueの場合は、enter許可(TextBoxの場合submit)。
    }
    else {
      // cansubmitbyenter属性がfalseの場合は、enter不許可。
      return false; 
    }
  }
} 
else {
  // enterの場合もsubmitボタンやtextarea領域はenter許可
}

```

## Reference
- フォームでのEnterキー押下について調べてみた - 130単位  
http://d.hatena.ne.jp/deeeki/20090516/formenterkey
  - When the user presses the "Enter key" in the input element,  
it will be post or get to destination that is specified in the action attribute of the form.
  - If the text box is multiple,
    - Behavior is different by the browser.
    - IE / Firefox / Opera : It is not Submit to even if Enter is pressed.
    - Opera / Safari / Chrome : It is Submit When Enter is pressed.

**Comment by daisukenishino** [comment]
I corrected JavaScript code above.

**Comment by kishoreandukuri** [comment]
Please confirm is anything needs to be done by HODC?

**Comment by daisukenishino** [comment]
I'll add this task to the task list of future sprint.

**Comment by daisukenishino** [comment]
# Additional information
## Submit button information
Button information that appears at the top of the DOM is submitted.
Depending on the browser, there is a case in which button information is not submitted.

## If the text box is multiple
- Because it is browser specifications, you do not need to solve this problem.
- However, please report behavior by add new screen (*.aspx) and analyze.

**Comment by daisukenishino** [comment]
# Supplementation to above "Additional information"
About analysis contents of the above.

## Premise
In form tag, there are several text boxes.
A focus is set in one text box.
And there are several "normal button" and "submit button".
- "normal button" is &lt;input type="button"&gt; or <button&gt;.
  (&lt;asp:Button UseSubmitBehavior="false"&gt;)
- "submit button" is &lt;input type="submit"&gt;.
  (&lt;asp:Button UseSubmitBehavior="true"&gt;)

## Our questions
Please investigate what will happen when user presses "Enter" key in one text box.
- Does the form submit? or not?
- Does the "Button.Click" event occur? or not?
- Does the event of which button carry it out?
  (The "submit button" which appears in DOM tree first?)
- By the number of text box(es), Is there difference in above behavior?
- By the browser, is there difference in above behavior?
  (Target browser: Major browser such as IE, Firefox, Chrome, etc.)

**Comment by supragyan** [comment]
HISOL Questions:
Does the form submit? or not?
HODC Answer:
 Yes, the form is submitted.

HISOL Questions:
Does the "Button. Click" event occur? or not?
HODC Answer:
Yes, the button click event is fired. 

HISOL Questions:
Does the event of which button carry it out?
 (The "submit button" which appears in DOM tree first?)
HODC Answer:
If the button is multiple (normal button and submit button) :
The only Submit button (which appears in DOM tree first) is submitted.
	
HISOL Questions:
By the number of text box(es), Is there difference in above behavior?
HODC Answer:
If the textbox is multiple:
When user click on each textbox, The Submit button (which appears in DOM tree first) is submitted.

HISOL Questions:
By the browser, is there difference in above behavior?
HODC Answer:
HODC did test in IE11, Firefox19.0, Chrome 42.0.2311.90, Safari 5.1.7, and Opera 24.0.1558.53 browsers. There is no difference. In all above versions of browsers, for single textbox or multiple textbox, it is Submit When Enter is pressed.
Do we need to test on any otter versions of browsers.
Please confirm?

**Comment by daisukenishino** [comment]
# The answers to Investigation result.
- Please add the validation of case that there is only one TextBox.

- In addition, please use as much as possible "mark down".  
  - GitHub Flavored Markdown - User Documentation  
https://help.github.com/articles/github-flavored-markdown/

**Comment by daisukenishino** [comment]
Modification of ie_key_event.js also included in this task.

**Comment by supragyan** [comment]
Dear Nishino-San,

>>Please add the validation of case that there is only one TextBox.
<HODC Understanding>
If in a form only one textbox is available,then we can submit the form by Enter key.For that we should implement validation for one textbox in testScreen3.aspx page. 

>>Modification of ie_key_event.js also included in this task.
HODC did commit modified ie_key_event.js file in ResolvedIssues branch.
But now HODC will create new feature  branch for 'suppress submit by pressing enter key' and will commit to that new feature branch.
Please confirm.

**Comment by daisukenishino** [comment]
>>"HODC Understanding"
>>If in a form only one textbox is available,
>>then we can submit the form by Enter key.
>>For that we should implement validation for one textbox in testScreen3.aspx page. 

Please tell us only the result.
 I will fill in [here](https://github.com/OpenTouryoProject/OpenTouryo/issues/78#issuecomment-93964169).

>>But now HODC will create new feature  branch for 'suppress submit by pressing enter key' and will commit to that new feature branch.

I have confirmed that the javascript file is included [here](https://github.com/SymphonyTeleca/OpenTouryo/pull/25/files).
