### ISSUE TITLE
Recommended method of "null and undefined" check in javascript.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#89]
# Requirement
I want to derive the recommended method in this project.

## The current implementation.
I have checked javascript's "null and undefined" value for just in case.
e.g. : https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L82
```JS
// hiddenがnullになることがある・・・ 
if (childScreenType == null || childScreenType == undefined) { 
  return; 
} 
```
## The suggestion on the Internet.
The information on the Internet, there is a lot of suggestion of a variety of ways.
- [JavaScript] null とか undefined とか 0 とか 空文字('') とか false とかの判定について - Qiita  
http://qiita.com/phi/items/723aa59851b0716a87e3
- オブジェクトがnullやundefindでないか評価する。 - うなの日記  
http://unageanu.hatenablog.com/entry/20070705/1183627496
- JavaScript：undefined値の判定 - 泥のように  
http://blog.tojiru.net/article/205007468.html

**Comment by yusukemaegawa** [comment]
The results in my environment are as follows.
Target Browsers: IE 9, Chrome 42, Firefox 36.

*  if property "aaa" is undefined...
  * "aaa === void 0" is true.
  * "aaa == void 0" is true.
  * "typeof aaa === 'undefined'" is true.
  * "typeof aaa == 'undefined'" is true.
  * "aaa === undefined" is true.
  * "aaa == undefined" is true.
  * "aaa === null" is false.
  * "aaa == null" is true.
* if property 'aaa' is null...
  * "aaa === void 0" is false.
  * "aaa == void 0" is true.
  * "typeof aaa === 'undefined'" is false.
  * "typeof aaa == 'undefined'" is false.
  * "aaa === undefined" is false.
  * "aaa == undefined" is true.
  * "aaa === null" is true.
  * "aaa == null" is true.

Is it necessary to distinguish "undefined" from "null" exactly?
* If necessary, you should use '==='.
* If not necessary, you should use '=='.

**Comment by daisukenishino** [comment]
# Conclusion
## Proper use.
Is it necessary to distinguish "undefined" from "null" exactly?
* If necessary, you should use '==='.
* If not necessary, you should use '=='.

Therefore, following the error.
e.g. : https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Framework/Js/common.js#L82
```JS
// hiddenがnullになることがある・・・ 
if (childScreenType == null || childScreenType == undefined) { 
  return; 
} 
```

Properly, as follows.
```JS
// hiddenがnullになることがある・・・ 
if (childScreenType == undefined) { 
  return; 
}
```
