### ISSUE TITLE
Column name that begin with "AND" or "OR" characters in the SQL is cut at the editing process of the "Where tag".

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#96]
# Phenomenon
Column name that begin with "AND" or "OR" characters in the SQL is cut at the editing process of the "Where tag".

```XML
<?xml version="1.0" encoding="utf-8" ?>
<ROOT>
  SELECT 
    XXX,
    YYY,
  FROM
    ZZZ
  <WHERE>
    WHERE
      <IF> ANDXXX = @ANDXXX</IF>
  </WHERE>
  <PARAM> ANDXXX, String, AAA </PARAM>
</ROOT>
```

If you give the parameters to "@ANDXXX",

- Expected results
```SQL
  SELECT 
    XXX,
    YYY,
  FROM
    ZZZ
  WHERE
    ANDXXX = @ANDXXX
```

- Actual results
```SQL
  SELECT 
    XXX,
    YYY,
  FROM
    ZZZ
  WHERE
    XXX = @ANDXXX
```
The head of the "AND" or "OR" is deleted.

# Countermeasure
- There is a need to modify the code of the following parts.  
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Db/BaseDam.cs#L2178

Is it like this.

- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Db/BaseDam.cs#L2191
```C#
　// ANDが最初に現れる位置（★半角スペースを追加）
　andIndex = where.IndexOf("AND ", startIndex, StringComparison.OrdinalIgnoreCase); 
　// ORが最初に現れる位置 （★半角スペースを追加）
　orIndex = where.IndexOf("OR ", startIndex, StringComparison.OrdinalIgnoreCase);
```

- Or, put around a column in the enclosure character of DBMS.
  - For SQLServer : [OR_ColumnName]
  - For Oracle : "AND_ColumnName"

**Comment by kishoreandukuri** [comment]
Dear Nishino-san,

We are not able to reproduce the bug.

Please share the steps to reproduce the bug

Thanks,

**Comment by daisukenishino** [comment]
I described how to reproduce to at the above "Phenomenon".

**Comment by kishoreandukuri** [comment]
Thank you for the information.

We will fix this issue

Thanks

**Comment by kishoreandukuri** [comment]
Dear Nishino-san,

We have found one more solution.

in the code if we give "AND "

 andIndex = where.IndexOf("AND ", startIndex, StringComparison.OrdinalIgnoreCase);

instead of 

 andIndex = where.IndexOf("AND", startIndex, StringComparison.OrdinalIgnoreCase);

The problem is fixing.

Please let us know.

Thanks and Regrads,

**Comment by daisukenishino** [comment]
I do not understand well the contents of your proposal.

>andIndex = where.IndexOf("AND ", startIndex, StringComparison.OrdinalIgnoreCase);

For the above, we also described at the "countermeasures" part in the following URL.

There is also a need to change the value of the string length.
- "AND" ---> "AND "　3 ---> 4
- "OR" ---> "OR "　2 ---> 3
